### ISSUE TITLE
Add support for Embedded Trigger Binding in Eventlistener

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#1004]
`tkn evenlistener describe` needs to have support for embedded trigger binding in Eventlistener. This feature got added in latest v0.5.0 release.

# Additional Info

Tkn: v0.9.0
Triggers: v0.5.0

/kind feature

cc @khrm @savitaashture

**Comment by savitaashture** [comment]
Describe display format
https://gist.github.com/savitaashture/4903807eb7b780640d016d78ca49ad4a
