### ISSUE TITLE
tkn pr ls <pipeline_name> doesn't show Failed(CouldntGetTask) pr

### ISSUE THREAD

**Issue by lstocchi** [tektoncd/cli#1007]
# Version and Operating System

**tkn Version:**
0.9.0

**Operating System:** 
Linux Fedora

# Expected Behavior
`tkn pr ls <pipeline_name> -n <namespace>` should show all pipelineruns for pipeline {pipeline_name}

# Actual Behavior
`tkn pr ls <pipeline_name> -n <namespace>` doesn't show pr which failed to start

# Steps to Reproduce the Problem

1. Create a pipeline that will never start. E.g a pipeline that refers a task that doesn't exist
2. Start the pipeline. It will have a status `Failed(CouldntGetTask)`
3. Execute the `tkn pr ls <pipeline_name> -n <namespace>` . The pr doesn't show up in the list

# Additional Info
Below you can see an example. 
In the first command i retrieve the prs for a specific pipeline and the failing pr is not shown. 
In the second i retrieve all prs and the failing one is correctly shown.
![image](https://user-images.githubusercontent.com/49404737/83629267-17bc8980-a59a-11ea-9e06-7e64c359038c.png)

**Comment by piyush-garg** [comment]
@lstocchi Can you please check one more thing if the `pipeline` name label got added to the failed run? Or also if you can put the yaml here.

When we filter by pipeline name, we basically filter by the label. Here is the code https://github.com/tektoncd/cli/blob/master/pkg/cmd/pipelinerun/list.go#L168

And this label is added by pipeline controller.

**Comment by lstocchi** [comment]
@piyush-garg ah ok, i see. No there is no pipeline name label, this is why. Below the yaml for the failing run.
```
[luca@localhost 0.9.0]$ ./tkn pipelinerun describe workspace-test-pp-run-9bpll -o yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: "2020-06-03T10:20:48Z"
  generateName: workspace-test-pp-run-
  generation: 1
  name: workspace-test-pp-run-9bpll
  namespace: tekton-pipelines
  resourceVersion: "875971"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/tekton-pipelines/pipelineruns/workspace-test-pp-run-9bpll
  uid: 1a9c4586-f9d6-4ab5-94b6-a16281d31f83
spec:
  params:
  - name: testo
    value: eeee
  pipelineRef:
    name: workspace-test-pp
  timeout: 1h0m0s
  workspaces:
  - name: work2
    persistentVolumeClaim:
      claimName: my-pvc-2
  - name: work1
    persistentVolumeClaim:
      claimName: my-pvc-2
  - name: secret1
    secret:
      secretName: secret-workspace-test
status:
  completionTime: "2020-06-03T10:20:48Z"
  conditions:
  - lastTransitionTime: "2020-06-03T10:20:48Z"
    message: 'Pipeline tekton-pipelines/workspace-test-pp can''t be Run; it contains
      Tasks that don''t exist: Couldn''t retrieve Task "mix-workspaces2": task.tekton.dev
      "mix-workspaces2" not found'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
  pipelineSpec:
    params:
    - name: testo
      type: string
    tasks:
    - name: use-works
      params:
      - name: textprint
        value: $(params.testo)
      taskRef:
        kind: Task
        name: mix-workspaces2
      workspaces:
      - name: custompvc
        workspace: work1
      - name: custompvc-2
        workspace: work2
      - name: customsecret
        workspace: secret1
    workspaces:
    - name: work1
    - name: work2
    - name: secret1
  startTime: "2020-06-03T10:20:48Z"
```

**Comment by piyush-garg** [comment]
@vdemeester Something to look into pipeline controller? Is it something like labels get added after validation?
