### ISSUE TITLE
Propagate kubectl style flags (specifically --context) to example commands

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/cli#1021]
# Version and Operating System

**tkn Version:**

I've built from checking it out so the version is dev, I built from 1a3c15d97ba73f57b47d480531f7682176494aa5 (june 10)

**Operating System:** 

Mac os

# Expected Behavior

I use the `--context` flag a lot with kubectl and tkn so that I can have multiple clusters in my kubeconfig but default to my personal one. I used --context for the dogfooding and prow clusters for tekton in particular.

I really like that tkn supports `--context` and I really like that tkn will provide me with helpful tkn commands I can run, e.g. to watch logs, and what I'd really like is if the --context flag (and any other flags I guess, not sure if there are others to be concerned with) would be propagated to the example command as well.

e.g. If I run `tkn --context dogfood pipeline start` I'd like the prompt afterward to say:

```
tkn --context pipelinerun logs pipeline-release-run-fwrpr -f -n default
```

That way I can easily copy paste it and use it.

# Actual Behavior

Here is an example from running the Tekton Pipelines release:

```
tkn --context dogfood pipeline start \
        --param=versionTag=${TEKTON_VERSION} \
        --param=imageRegistry=${IMAGE_REGISTRY} \
        --serviceaccount=release-right-meow \
        --resource=source-repo=${TEKTON_RELEASE_GIT_RESOURCE} \
        --resource=bucket=${TEKTON_BUCKET_RESOURCE} \
        --resource=builtBaseImage=base-image \
        --resource=builtEntrypointImage=entrypoint-image \
        --resource=builtKubeconfigWriterImage=kubeconfigwriter-image \
        --resource=builtCredsInitImage=creds-init-image \
        --resource=builtGitInitImage=git-init-image \
        --resource=builtControllerImage=controller-image \
        --resource=builtWebhookImage=webhook-image \
        --resource=builtDigestExporterImage=digest-exporter-image \
        --resource=builtPullRequestInitImage=pull-request-init-image \
        --resource=builtGcsFetcherImage=gcs-fetcher-image \
        --resource=notification=post-release-trigger \
        pipeline-release
Pipelinerun started: pipeline-release-run-fwrpr

In order to track the pipelinerun progress run:
tkn pipelinerun logs pipeline-release-run-fwrpr -f -n default
```

No --context flag in the logs command.

# Steps to Reproduce the Problem

1. Start a pipeline using --context
2. Observe the logs command does not contain --context

**Comment by chmouel** [comment]
Thanks for reporting this, we will get this fixed.

tip, you could probably use `--showlog` if you wanted to show the logs straight away after starting a task/pipeline,
