### ISSUE TITLE
Remove Namespace Validation for tkn subcommands

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/cli#1031]
### Feature request
Remove namespace validation from all the tkn subcommands
As per the actual discussion [#1011 ](https://github.com/tektoncd/cli/pull/1011) some users may not have access to list the namespaces so we should remove the namespace validation from all the tkn subcommands

#### Scenario:
```
$ oc whoami
user

$ oc get pipelines -n openshift
NAME                      AGE
buildah                   5h8m
buildah-deployment        5h8m
s2i-dotnet-3              5h8m
s2i-dotnet-3-deployment   5h8m
s2i-go                    5h8m
...

$ tkn pipelines list -n openshift
Error: namespaces "openshift" is forbidden: User "user" cannot get resource "namespaces" in API group "" in the namespace "openshift"
```

**Comment by danielhelfand** [comment]
As mentioned on the cli slack, the following issue also occurs on the dogfooding cluster for Tekton:

```
[cleanup-pr-tr] + '[[' 200 -eq 0 -o 200 '=='  ]]
[cleanup-pr-tr] + tkn pr delete -n tektonci --all --keep 200
[cleanup-pr-tr] Error: namespaces "tektonci" is forbidden: User "system:serviceaccount:default:tekton-cleaner" cannot get resource "namespaces" in API group "" in the namespace "tektonci"
```

Perhaps we should reclassify this as a bug and discuss formally removing it from `tkn`. My personal thought is to remove it by next release.

**Comment by danielhelfand** [comment]
I could repurpose #1026 to address this as it begins to break up the package where namespace validation occurs.

**Comment by chmouel** [comment]
👍

**Comment by vdemeester** [comment]
agreed !
