### ISSUE TITLE
Delete taskruns not owned by a pipelinerun

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/cli#1034]
### Feature request

I'd like to be able to delete taskruns not owned by a pipelinerun.
Alternatively an ability to filter the taskruns to be deleted that covers the "owner" would also solve the issue.

### Use case

I'm trying to keep the number of runs under control on the dogfooding cluster, using `tkn`. 
I will delete everything but the last N pipeline runs, and then everything but the last M task runs.
However I have no way to specify that I want to preserve N pipeline runs when I delete the task runs, so I will probably end up deleting taskruns that were created by a pipelinerun.

### UI Example

I'm not very good at naming, but perhaps something like:
```
tkn delete --all -n [namespace] --keep 200 --exclude-pipelineruns
```

**Comment by danielhelfand** [comment]
Could potentially be a good opportunity for `--field-selector` or `--label` based approach with delete.
