### ISSUE TITLE
Show EventListener Status with tkn eventlistener list

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1042]
### Feature request

I would like the ability to see whether an EventListener has been created successfully and is available when using `tkn`. This `STATUS` could possibly come from whether the minimum replicas are available for the deployment associated with an EventListener and whether the service exists that is associated with the EventListener.

### Use case

The use case is that a user wants to verify an EventListener was both created successfully and is available to accept requests. This could help identify the need for further debugging if an EventListener deployment experiences an issue. 

A follow up to this might be to also include a reason for errors with an EventListener deployment in `tkn el desc`. 

### UI Example

```
tkn el ls

NAME                          AGE           STATUS
github-listener-interceptor   2 hours ago   AVAILABLE
github-listener-interceptor2  2 hours ago   ERROR
```

Or

```
tkn el ls

NAME                          AGE           AVAILABLE
github-listener-interceptor   2 hours ago   TRUE
github-listener-interceptor2  2 hours ago   FALSE
```

**Comment by piyush-garg** [comment]
@pratikjagrut Can we close this issue, seems like the PR is merged

**Comment by danielhelfand** [comment]
This was added in v0.12.0. We can close it.
