### ISSUE TITLE
Pipeline/PipelineRun describe: display workspace

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#1048]
### Feature request

When doing a `tkn pipeline describe` (and `tkn pipelinerun describe`) I would like to see the declared workspace in the output.

### Use case

Being able to see what workspace  I need to provide to execute the pipeline.

### UI Example

```bash
$ tkn pipelinerun desc pipeline-release-run-z9557
Name:              pipeline-release-run-z9557
Namespace:         default
Pipeline Ref:          golang-test
Service Account:   release-right-meow
Timeout:           1h0m0s

# […]

📨 Workspace

 NAME       RESOURCE REF
 ∙ source   tekton-pipelines-git-v0-14-0

📡 Output Resources

 No output resources

⚓ Params

 NAME        VALUE
 ∙ package   github.com/tektoncd/pipeline
 ∙ flags     -v -mod=vendor


                  
```

**Comment by vinamra28** [comment]
@chetan-rns needs this urgently so taking this from you :sweat_smile: 
/assign

**Comment by chetan-rns** [comment]
@vinamra28 No issues :) I was actually waiting for your PR to get merged since the functions used in tasks/taskruns can be reused here
