### ISSUE TITLE
Add  an option to logs to not show the task name on the left

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#105]
We currently show the task name in blue on the left :

```[build-skaffold-app : step-build-and-push]       --cache                                     Use cache when building image```

which is nice and all but sometime you want to copy and paste nicely the output of the task and have only whatever logs output not something change,

let's have an option like --porcelain (like git porcelain https://stackoverflow.com/questions/6976473/what-does-the-term-porcelain-mean-in-git) to output only the logs and nothing else.

**Comment by girishramnani** [comment]
I can work on this
