### ISSUE TITLE
Pipeline version shows "devel" instead of "0.14.0"

### ISSUE THREAD

**Issue by ckadner** [tektoncd/cli#1055]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11+IKS", GitCommit:"c33b093e937d1f9eee340f9bddfa14e1e54ad1a4", GitTreeState:"clean", BuildDate:"2020-06-17T21:37:54Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version`:**

  ```
  Client version: 0.10.0
  Pipeline version: devel
  Triggers version: unknown
  ```

  **Output of `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```v0.14.0```

- Operating System:

  ```
  Mac OS 10.15.5
  ```

# Expected Behavior

`tkn version` should show `Pipeline version: 0.14.0`

# Actual Behavior

`tkn version` shows `Pipeline version: devel`

# Steps to Reproduce the Problem

1. Install `tektoncd/pipeline` release `0.14.0`:

   `kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/v0.14.0/release.yaml`

2. Run `tkn version`:

   ```
   Client version: 0.10.0
   Pipeline version: devel
   Triggers version: unknown
   ```

# Additional Info

Related issue in `tektoncd/pipeline`: https://github.com/tektoncd/pipeline/issues/2898

**Comment by danielhelfand** [comment]
@savitaashture Can you comment on if this issue is taking place server side with pipelines, or is this an issue we need to look further into for `tkn`? 

https://github.com/tektoncd/pipeline/issues/2898

**Comment by ckadner** [comment]
> @savitaashture Can you comment on if this issue is taking place server side with pipelines, or is this an issue we need to look further into for `tkn`?
> 
> [tektoncd/pipeline#2898](https://github.com/tektoncd/pipeline/issues/2898)

Unless there is a "patch"-release for Tekton, i.e. `0.14.1` coming soon, I think this would need to be addressed in the upcoming `tektoncd/cli` release, no?

**Comment by danielhelfand** [comment]
So I think this will be addressed by https://github.com/tektoncd/pipeline/pull/2900 and appears to have nothing to do with `tkn`'s version implementation. I think the challenge with adding a version case for `v0.14.0` is that `devel` is used as the version when doing development work with pipelines. Putting in a specific case to display `v0.14.0` if `devel` is returned would cause `v0.14.0` to be displayed when doing development work. I think the better approach would be to wait for a minor release of pipelines. Unless there is some other approach that I am not considering here?

**Comment by ckadner** [comment]
> So I think this will be addressed by [tektoncd/pipeline#2900](https://github.com/tektoncd/pipeline/pull/2900) and appears to have nothing to do with `tkn`'s version implementation. I think the challenge with adding a version case for `v0.14.0` is that `devel` is used as the version when doing development work with pipelines. Putting in a specific case to display `v0.14.0` if `devel` is returned would cause `v0.14.0` to be displayed when doing development work. I think the better approach would be to wait for a minor release of pipelines. Unless there is some other approach that I am not considering here?

If the actual `tektoncd/pipelines` `0.14.0` release gets replaced, or if a patch release comes very soon, then I would agree with you. But if the `0.14.0` release remains the latest release for a while, then there may be a lot of future bug reports which ask users to run `tkn version` that won't clearly show which Tekton version was used to produce an error. Unless all the Tekton developers know that `devel` most likely means `0.14.0`.

A special case for `0.14.0` could do the same as `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'` which reveals `v0.14.0`

**Comment by danielhelfand** [comment]
It looks like something may have been backported already:

```
$ tkn version
Client version: 0.10.0
Pipeline version: v0.14.0
Triggers version: unknown
```

Can you verify it's working for you?

**Comment by vdemeester** [comment]
@danielhelfand @ckadner yeah I fixed the release.yaml for the time being (and there is a bugfix for this not to happen in the next releases, will be in a 0.14.1 too).

**Comment by danielhelfand** [comment]
@vdemeester Thanks! Going to close this for now, but please feel free to reopen if something isn't working as expected @ckadner.

**Comment by ckadner** [comment]
Verified it works for me as well. Thanks @vdemeester
