### ISSUE TITLE
Release pipeline: migrate to use workspace and results instead of PipelineResource

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#1057]
We should use workspace and results instead of PipelineResource, mainly to be able to use up-to-date catalog tasks (from `master`).

Related to https://github.com/tektoncd/pipeline/pull/2897 and https://github.com/tektoncd/plumbing/pull/456 (in pipeline and plumbing).

**Comment by vinamra28** [comment]
Hi @vdemeester , there is already an existing issue #1019  related to this I guess 😅

**Comment by vdemeester** [comment]
Indeed :facepalm: 
/close
