### ISSUE TITLE
Add makefile at the top of the directory

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#106]
- if like me you rather press `make` than `go build ./...`
- so we can have a `make check` which does all the checks we want without
remembering which tool to launch before submitting PR.
- so we can have a `make release` all centralised and not just in @vdemeester 
brain.
- cause makefile were cool in the late 90s, became lame in the 2000s and are
cool again with the go and scala hipsters crowd.

**Comment by vdemeester** [comment]
/close
It is now the case
