### ISSUE TITLE
Bug: cluster task list in nonexistence namespace 

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/cli#1062]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", 
   GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", 
   GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"aa10b5b", GitTreeState:"clean", 
   BuildDate:"2020-03-16T18:11:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  v0.14.1
  ```

- Operating System:

  ```
  fedora-31
  ```

# Expected Behavior
When we try to list clustertask from nonexistence 
```
$ tkn ct ls -n lllays
Error: namespaces "lllays" not found
```
# Actual Behavior
```
$ tkn ct ls -n lllays
NAME            DESCRIPTION   AGE
clustertask-1                 24 seconds ago
clustertask-2                 24 seconds ago
```
# Steps to Reproduce the Problem

1. Create any cluster task
2. Try to run `tkn clustertask list -n <non-existence-namespace>`

**Comment by vdemeester** [comment]
I wonder if that's a bug. Or more accurately, we may print a warning (or error out?) if the user provide a `--namespace`/`-n` when listing ClusterTask… because by definition, the namespace filter doesn't apply :upside_down_face:

**Comment by piyush-garg** [comment]
Which version of `tkn` you are using, we have removed the namespace flag from clustertask and clustertriggerbinding using the PR https://github.com/tektoncd/cli/pull/943

**Comment by piyush-garg** [comment]
I see the flag is mark hidden, but if someone provide with command it accepts.

may be we need to mark it deprecated and remove later.

**Comment by praveen4g0** [comment]
I agree, but for consistency it's better to restrict user to use namespace flag, as it is misleading in some aspects

**Comment by praveen4g0** [comment]
> Which version of `tkn` you are using, we have removed the namespace flag from clustertask and clustertriggerbinding using the PR #943

I am using latest cli build from master
