### ISSUE TITLE
Only Display Version of a Particular Tekton Component with tkn version

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1067]
### Feature request

The ability to only display a version of a specific Tekton component using `tkn version`. 

### Use case

For purposes of scripting using `tkn`:

```
pipelineversion = $(tkn version --pipeline)
```

It will also aid with helping test `tkn` in e2e scenarios. An example of this is #1066, which is adding support for a feature that doesn't exist in pipelines version v0.10.2, but all e2e tests are run against version v0.10.2 as part of our CI process. It would be helpful to be able to get the pipeline version as output to help understand whether to skip a test for a feature that doesn't exist in older versions of pipelines.

### UI Example

```
$ tkn version --pipeline
v0.14.0

$ tkn version --triggers
v0.6.1
```

**Comment by anshulvermapatel** [comment]
@danielhelfand , So the basic ask for this feature is just to add `--pipeline` and `--triggers` option to print only their version respectively to benefit the CI process which would be able to filter the test against a version. Can you please confirm?

**Comment by danielhelfand** [comment]
@anshulvermapatel Yes, that is correct. 

I would say let's wait to discuss this in the working group to make sure this is worthwhile first and see if there are different opinions on it.

**Comment by anshulvermapatel** [comment]
@danielhelfand , sure!

**Comment by csantanapr** [comment]
More flexible option for the UX would be to use a single flag and the value the component like "tkn version --component=pipelines" instead

**Comment by anshulvermapatel** [comment]
@danielhelfand @csantanapr , created a [PR](https://github.com/tektoncd/cli/pull/1093) for this. Please review.
