### ISSUE TITLE
Darwin CLI should be built with `CGO_ENABLE=1` and/or `GODEBUG=netdns=cgo`

### ISSUE THREAD

**Issue by pierretasci** [tektoncd/cli#1079]
# Versions and Operating System

- Kubernetes version: any

- Tekton Pipeline version: any

- Operating System: MacOS

# Expected Behavior

When using a VPN on MacOS as many corporations do (especially in a remote environment), `tkn` is able to perform all functions against a Kubernetes cluster.

# Actual Behavior

When using a split-tunnel VPN with custom rules, `tkn` will fail to resolve the host.

# Additional Info

Because of how go's `netdns` resolver works, the go implementation doesn't necessarily work with Darwin's dns resolver chain. Instead, it would need to use the `cgo` version as that uses the OS's resolvers which is how most VPNs configure their custom tunnel rules when there is a split tunnel. For reference, when `kubectl` distributes itself via homebrew, it compiles with `CGO_ENABLE=1`: https://github.com/kubernetes/release/issues/469

I believe the fix here is to cross-compile with `cgo` enabled for the binary that is deployed to homebrew There are potential cross-compilation problems here so there is an alternative which is to force the issue and build the code using `GODEBUG=netdns=cgo` which will also force go to use the cgo dns resolver.

**Comment by chmouel** [comment]
This should be solved for "free" with go 1.20 fyi : 

https://danp.net/posts/macos-dns-change-in-go-1-20/

**Comment by piyush-garg** [comment]
We have done 0.33 release with go 1.20, closing this now
