### ISSUE TITLE
Get pipeline or task status for scripts

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1090]
### Feature request

It would be great if a user with the CLI was able to get the task or pipeline status easily for scripts. This which will just show the status of the pipeline and set the exit code with the status.

### Use case

I have a script which use tkn and I would like to know if my TaskRun has failed or not, the way I am doing is parsing the current describe command with a Regexp : 

`/^STARTED\s*DURATION\s*STATUS\n(.*)$/m`

and get if the status of my Task like this to know if it has failed or succeeded.

### UI Example

`tkn describe --status [pipeline/task]run`

output:

* success
* failed
* running 
* unkown
* or others

etc...

* **success** =>  exit 0
* **failed** => exit 1
* **running** => exit 2
* **unkown** => exit 3
* or others

(etc...)

**Comment by rudeigerc** [comment]
Hi, I have created a PR (#1291) for the issue, but I'm not sure whether it meets the need. Please have a look at it. Thanks a lot!
I have implemented the issue by adding a `--status` flag when executing `tkn describe taskrun` (i.e., `tkn describe taskrun --status`.
