### ISSUE TITLE
Better UX for restarting taskrun/pipelinerun

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1091]
### Feature request

Have an easy way to restart taskruns or pipelineruns

### Use case

A user can use the feature `--use-taskrun` to `tkn task` or the pipeline equivalent. That's not an obvious wayfor the user who wants to restart a taskrun/pipelinerun for something as common as restarting a pipelinerun/taskrun

### UI Example

Something like this : 

`tkn taskrun restart taskrun-abcd`

would do the same thing as 

`tkn task start taskrun --use-taskrun taskrun-abcd`

same goes for `pipelinerun`

**Comment by danielhelfand** [comment]
@rudeigerc We should probably discuss this a bit more before adding this. You are welcome to put together something for it, but it might be good for us to put together some research on what is the preferred UX for this within the community.

**Comment by rudeigerc** [comment]
@danielhelfand Of course! I will keep following the issue.

Actually I have noticed that the dashboard provides the command of rerun for PipelineRun (and only for PipelineRun) with a rerun suffix (i.e., -r-\<new-id\>). Should the same command across the components follow a consistent rule when numbering?

**Comment by danielhelfand** [comment]
I think this makes sense to move forward with, but we should probably just formally discuss this in the working group next week to make sure folks are onboard with it.

**Comment by danielhelfand** [comment]
Personal preference would be to have this implemented for `taskrun`/`pipelinerun` commands. `restart` sounds good to me as a subcommand name. My thought is that should be as simple as providing a name arg (name of TaskRun or PipelineRun) to the command, get the previous run, build a new run by adding the spec of the previous run, and then come up with a naming strategy for renaming the new run that is created. Not sure if there are certain options that should be included as well, but I think starting simple here makes sense.

**Comment by chumaltd** [comment]
+1 to `tkn tr|pr start` directly. It can utilize taskRef | pipelineRef.

I just wrote a plugin for interactive selection.
https://github.com/chumaltd/tkn-runner

I treat PipelineRun / TaskRun that doesn't have `generateName` as a template, and others are instances.
I think we need to preserve templates on delete in most cases.

**Comment by muja** [comment]
This isn't just a UI issue. The tkn cli requires an existent task which somehow just isn't there. For example, you can have a TaskRun with an inline taskSpec or a taskRef using the hub or git resolver. AFAIU it is impossible to rerun such a task with the tkn cli, since it expects the name of a Task.

Given the same isn't possible in the web view as well but it is possible for PipelineRuns without a corresponding Pipeline in the web ui but again, not using the tkn cli.

Why was this closed? And also, is there a workaround (besides copy pasting parts of the taskrun manifest?)
