### ISSUE TITLE
The status of step stays in `Running` state when the taskrun fails with `TaskRunTimeout`

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#1095]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-01-29T21:26:39Z", GoVersion:"go1.14beta1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+6025c28", GitCommit:"6025c28", GitTreeState:"clean", BuildDate:"2020-07-01T23:26:48Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  tkn version
  Client version: 0.11.0
  Pipeline version: v0.14.3
  Triggers version: v0.6.1

  ```

- Operating System:

  ```
  Linux
  ```

# Expected Behavior
The status of step should be `failed` or `Error` state

# Actual Behavior
The status of step is in 'Running` state

# Steps to Reproduce the Problem

1. Create a task
2. Start the task with timeout `tkn t start <task-name> --timeout 1m`
3. Check the status of the step when taskrun fails with error `TaskRunTimeout`

# Additional Info
`tkn tr description` output:
```
$ tkn tr describe finally-task-run-j6dfj 
Name:              finally-task-run-j6dfj
Namespace:         veeresh-testing
Task Ref:          finally-task
Service Account:   pipeline
Timeout:           5m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 tekton.dev/task=finally-task

🌡️  Status

STARTED         DURATION    STATUS
6 minutes ago   5 minutes   Failed(TaskRunTimeout)

Message

TaskRun "finally-task-run-j6dfj" failed to finish within "5m0s"

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

🦶 Steps

 NAME         STATUS
 ∙ step-one   Running

🚗 Sidecars
```

**Comment by danielhelfand** [comment]
This seems to be the status being returned from pipelines for the TaskRun's steps. One thing of curiosity to me is that it seems the TaskRun pod is deleted immediately after it fails from the timeout. But this seems like it could be a pipelines issue as well. `tkn` can only report the status that is returned from the server, which is what it is doing. I can follow up with the resources I used to reproduce this, but I am not sure there can be much done on the `tkn` side.

**Comment by VeereshAradhya** [comment]
@danielhelfand shall I file this issue in `pipeline`?

**Comment by danielhelfand** [comment]
@VeereshAradhya So I have done some more digging on this, and I guess the reason is that pipelines deletes pods associated with timeout/cancellation TaskRuns and does not update the status of steps for TaskRuns. My personal thought is that pipelines should handle this, but it's tough to know how easy it will be since pipelines needs to really quickly delete the pod to honor a timeout or cancellation. 

Assuming this is not doable with pipelines, we could try to do something client side to at least get rid of the running status. But the information won't necessarily be consistent with what happened sever side. 

/cc @vdemeester Any thoughts on this?

**Comment by vdemeester** [comment]
> So I have done some more digging on this, and I guess the reason is that pipelines deletes pods associated with timeout/cancellation TaskRuns and does not update the status of steps for TaskRuns. My personal thought is that pipelines should handle this, but it's tough to know how easy it will be since pipelines needs to really quickly delete the pod to honor a timeout or cancellation.

I think it's on pipeline side indeed. Pipeline should handle updating the status even after deleting the pod I think. So yeah I think we can transfer this issue to `tektoncd/pipeline`

/cc @bobcatfish @afrittoli

**Comment by danielhelfand** [comment]
My thought on this would be to iterate over the step statuses of the TaskRun [after the pod deletion](https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/pkg/reconciler/taskrun/taskrun.go#L512), assuming the deletion is successful.

I think a question would be what the terminated status would be for the step? Would we want it to be something along the lines of the reason for the TaskRun, or something else?
