### ISSUE TITLE
Disconnected pipeline-run logs with `-f`

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/cli#1097]
# Versions and Operating System

- **Description**
  1. create a pipeline with task which has `retires: 1`
  2. Start pipeline
  3. ```tkn pr logs -f```
  4. If task defined in pipeline fails, pipeline run schedules another task run as we mentioned Retries at pipeline level specific to task
  5. pipeline run logs gets disconnected.
  
- Kubernetes version:

  **Output of `kubectl version`:**

```
 Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"592b165660fbf31430b78575e311837d6e73514f", GitTreeState:"clean", BuildDate:"2020-07-13T19:06:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+a1af596", GitCommit:"a1af596", GitTreeState:"clean", BuildDate:"2020-07-06T06:07:48Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: v0.11.0
Pipeline version: v0.14.3
Triggers version: v0.6.1
```

- Operating System:

 ```
 linux
 ```
 
# Expected Behavior
* Continuous logs from pipeline run.
```
$ tkn pr logs -f
[run-fail-task : step-one] sleeping for 10 seconds
[run-fail-task : step-one] this is first task

[run-fail-task : step-one] sleeping for 10 seconds
[run-fail-task : step-one] this is first task

Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0
```

# Actual Behavior
* pipeline run logs gets disconnected when pipeline run tries to schedule new taskrun/pod, and delete the existing.
``` 
$ tkn pr logs -f
[run-fail-task : step-one] sleeping for 10 seconds
[run-fail-task : step-one] this is first task
```

# Steps to Reproduce the Problem
1. oc apply -f https://gist.githubusercontent.com/praveen4g0/4672bd88461b9aee572b4ed9ffaca5f4/raw/5b753b3aa14d754516450c6e78a932bf1817307b/fail-task.yaml

2. oc apply -f https://gist.githubusercontent.com/praveen4g0/4672bd88461b9aee572b4ed9ffaca5f4/raw/5b753b3aa14d754516450c6e78a932bf1817307b/fail-pipeline-with-retries.yaml

3. tkn p start pipeline-test

# Additional Info

**Comment by nishpa214** [comment]
@Shivkumar13 @piyush-garg Can I help w/ this one? @Shivkumar13  if you started already, we can pair and split up work. If not, I can take this one also.
