### ISSUE TITLE
0 Value for Timeout with tkn tr/pr describe is reported as Seconds

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1106]
# Versions and Operating System

- Kubernetes version:

N/A

- Tekton Pipeline version:

```
Client version: 0.11.0
Pipeline version: v0.15.0
Triggers version: unknown
```

- Operating System:

N/A

# Expected Behavior

The timeout should not be displayed for TaskRuns/PipelineRuns or the value `0` should be translated into something that communicates that no timeout is applied to the TaskRun or PipelineRun.

# Actual Behavior

The timeout is reported as `0s`:

```
$ tkn tr desc --last

Name:        sleep1s-run-x99fj
Namespace:   default
Task Ref:    sleep1s
Timeout:     0s
```

# Steps to Reproduce the Problem

1. Start a TaskRun or PipelineRun with a timeout of `0`: `tkn t start taskName --timeout 0` or `tkn p start pipelineName --timeout 0`
2. Run `tkn tr desc --last` or `tkn pr desc --last` to see value

**Comment by piyush-garg** [comment]
@rudeigerc Can you please omment `/assign` so that issue will be assigned

**Comment by rudeigerc** [comment]
OK :)
