### ISSUE TITLE
Start a task from a taskrun with embedded task

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/cli#1119]
### Feature request

I would like to be able to re-run a taskrun with embedded task spec.
Today this is not possible:
```
$ tkn task start --use-taskrun plumbing-yamllint-pr-complete-zkg94
Error: either a Task name or a --filename argument must be supplied
```

The `TaskRun` is defined here: https://github.com/tektoncd/plumbing/blob/bde34da7abdec4bd7f63a607d56828b5bdba5833/tekton/resources/ci/github-template.yaml#L26

### Use case

This is useful to re-run taskruns in Tekton CI.

### UI Example

I see two options:
- allow for the task name to be missing in the `--use-taskrun` command
- implement this as `tkn taskrun rerun <taskrun-name>`

In either case, fail if there is no embedded spec or the referenced task cannot be found.

**Comment by danielhelfand** [comment]
@afrittoli Somewhat related to this, we have an [open issue](https://github.com/tektoncd/cli/issues/1091) for improving UX around rerunning taskruns. Curious what your opinion is on using the `--use-taskrun` flag versus having a new taskrun command?

In general though, we should adapt our start approaches to support embedded Task specs regardless of with `tkn task start` or with a new command if that is the preferred UX.

**Comment by danielhelfand** [comment]
@afrittoli Whenever you have a chance, could you see if the if the changes from #1134 address this?

**Comment by danielhelfand** [comment]
In rethinking this over, it makes more sense in my mind to add support for a `taskrun`/`pipelinerun` rerun command. Given how task/pipeline start are very focused around passing the name arg, it might be simpler and also align better with our current structure to support what is outlined in #1091.
