### ISSUE TITLE
tkn pipeline start does not present validation errors

### ISSUE THREAD

**Issue by clux** [tektoncd/cli#1122]
Not sure if this is a bug report or a feature request. Found this a bit strange while goofing around with the yaml from the [kubecon-demo](https://github.com/joellord/handson-tekton) (06-pipeline-order)

# Versions and Operating System
- Kubernetes version:
Minikube 1.18.2

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.11.0
Pipeline version: v0.15.2
Triggers version: unknown
```

- Operating System:

  ```
  Arch Linux
  ```

# Expected Behavior

```
tkn pipeline start say-things-in-order --showlog
```

should present the validation error from the `PipelineRun` 

# Actual Behavior

`tkn` instead just prints these 2 lines then exits zero.
```
PipelineRun started: say-things-in-order-run-7fjrx
Waiting for logs to be available...
```

# Steps to Reproduce the Problem

1. Create a task with parameters.
2. Create a pipeline referencing the task
3. Have the pipeline reference a parameter that does not exist

**Comment by danielhelfand** [comment]
@clux Thanks for opening this. Could you please share the Task and Pipeline definitions and clarify what parameter you are referring to? I can try to reproduce the issue or provide some context with a bit more information.

**Comment by clux** [comment]
They are the two linked ones from the demo:

- [say-something Task](https://github.com/joellord/handson-tekton/blob/master/demo/04-tasks.yaml)
- [say-things-in-order Pipeline](https://github.com/joellord/handson-tekton/blob/master/demo/06-pipeline-order.yaml)

The last file references the first. If we change the `Pipeline`'s parameter to have a parameter not specified in the `Task` by editing the last file:

```yaml
    - name: first-task
      params:
       # edited line:
        - name: mistyped-pause-duration
          value: "2"
        - name: say-what
          value: "Hello, this is the first task"
```

then you get the silent error described above by starting this pipeline via `tkn`
