### ISSUE TITLE
Show only CLI and  Pipeline version in `tkn version` when Triggers and/or Dashboard are not installed

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/cli#1143]
At present, the `tkn version` displays `Unknown` for Triggers version even when they are not installed.

```
$ tkn version

Client version: 0.10.0
Pipeline version: v0.15.2
Triggers version: unknown
```
With this patch S[how the version of dashboard #1138](https://github.com/tektoncd/cli/pull/1138) `Dashboard: unknown` will start to appear if the components are not installed. Especially, with OpenShift `Dashboard: unknown` will be almost always the case, as there is a inbuilt webui for pipelines.

Shall we  hide the Triggers and Dashboard items from the `tkn version` output, 
when the version information is not available.

**Comment by vdemeester** [comment]
I vote for hiding versions of components that we can't "find" :upside_down_face:

**Comment by vdemeester** [comment]
@danielhelfand adding this to 0.12.0 to make sure we discuss this before the release :wink:

**Comment by danielhelfand** [comment]
Yes, I think hiding the versions if not installed makes a lot of sense. The argument could even be made for hiding pipelines version as well, but hiding Triggers and similarly the Dashboard version as you pointed out in #1138 I think would be better presentation.

**Comment by chmouel** [comment]
With the addition of dashboard, I would really love to have this, the `tkn version`is becoming busier and busier
