### ISSUE TITLE
Allow PipelineRuns created by Pipeline Start to embed ownerReference information.

### ISSUE THREAD

**Issue by mhaddon** [tektoncd/cli#1163]
### Feature request

For compatibility with ArgoCD it will need to know the owner of created resources: https://github.com/tektoncd/pipeline/issues/3202

Otherwise they will be automatically pruned.

### Use case

Either as a default for `tkn pipeline start` or `tkn pipeline start --referenceOwner`

**Comment by danielhelfand** [comment]
I think it makes sense to add an option both for PipelineRuns/TaskRuns. I think the question here is what should the UX look like? 

OwnerReferences is a list of owner references, so would it be better to allow a user to specify several as part of a TaskRun/PipelineRun:

```
tkn pipeline start pipelineName --owner-reference ... --owner-reference ... 
```

Or possibly define all the owner references via a file definition:

```
tkn pipeline start pipelineName --owner-references ./path/to/file/owner-refs.yaml
```

**Comment by mhaddon** [comment]
It could also just be the parent object. For example, the owner of a pipelinerun could be the pipeline.
I am not sure what the preferred solution is, it makes Tekton play nice with ArgoCD though. See the referenced ticket for more information.

**Comment by danielhelfand** [comment]
Yes, I see your point. This may be something that can actually take place server side with pipelines. We can keep this open though until there is further clarity on the right approach, and we can follow along with the pipeline issue.
