### ISSUE TITLE
Show a message when no logs available yet

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#117]
When a pipelinerun is just created and no logs are available, the `tkn pipelinerun logs` returns silently:

```
$ tkn pipelinerun logs mapit-build-pipelinerun-1 -f                                                                                                                 
$
```

It should print out a message instead to say no logs are available yet or something similar.

**Comment by chmouel** [comment]
@siamaksade how would you know if this is the actual output of the application it may be a stretch but usually when there is no logs I would expect the emptyness is valid, isnt it ?

**Comment by siamaksade** [comment]
Given that pipelineruns have always some infra containers (git clone, etc)
running, is it possible for a pipelinerune to produce no logs at all?

**Comment by vdemeester** [comment]
@siamaksade yes, by default we don't show the infra logs (aka init logs), so my guess is there is a tiny tiny possibility of having no logs :angel:. But in any case, we know the status of the pipelinerun (aka if it succeeded, failed, so we can act based on it)

**Comment by siamaksade** [comment]
@chmouel  @vdemeester I see. Does the following make sense?
- If the pipelinerun is running and no logs: "No logs found yet..."
- If the pipelinerun is NOT running and no logs: "No logs found."

**Comment by chmouel** [comment]
sounds good, but what about for the second case to say instead :

`Pipeline hasn't started...`

**Comment by vdemeester** [comment]
> If the pipelinerun is running and no logs: "No logs found yet..."
If `-f` is present, it will not return until it's not running, so there is not need for this case :angel: — if `-f`is not present, that's another story :wink:

**Comment by chmouel** [comment]
can someone sum up the conclusion? i am confused 🥺

**Comment by siamaksade** [comment]
Here is a summary with a slight change :)

When `-f` present
- Logs command should wait for output (current implementation)

When `-f` is **NOT** present
- If pipelinerun is running and no logs available, logs command should wait (not return)
- If the pipelinerun is **NOT** running and no logs are available, the command should return and print: “No logs available.”
