### ISSUE TITLE
Move goreleaser from tekton/goreleaser.yaml to official catalog

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1170]
We have a release task in [tekton/goreleaser.yaml](https://github.com/tektoncd/cli/blob/d5a15bd20aed5627ddee8d504521aca98d7a3a05/tekton/goreleaser.yml) which
could be useful for other people, let's move it to the official catalog and use
that for release.

/kind cleanup

**Comment by danielhelfand** [comment]
I think we should probably keep this open until we change `release.sh` to use the catalog Task, right?

**Comment by vinamra28** [comment]
ohh....so sorry :sweat_smile:

**Comment by danielhelfand** [comment]
@vinamra28 No worries. We can convert process and close this after v0.13.0 is released.
