### ISSUE TITLE
Add tkn Logo to README

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1175]
We should make use of the [logo created for `tkn`](https://github.com/cdfoundation/foundation/issues/147) by CDF.

The artwork is available [here](https://github.com/cdfoundation/artwork/tree/main/tekton/additional-artwork/tekton-cli). It would be nice to add this to the top of the README.

**Comment by bartkalanski** [comment]
Would you mind if I do this ?

**Comment by danielhelfand** [comment]
@bartkalanski That would be awesome. Thank you! I'll go ahead and assign you. For reference, the [triggers project](https://github.com/tektoncd/triggers#tekton-triggers) has done something similar to this, but we're open to suggestions on however you would like to approach this.

/assign @bartkalansk

**Comment by danielhelfand** [comment]
Closing from #1176
