### ISSUE TITLE
Automate Release Process via Tekton or Prow

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1199]
As of now, the release process for the CLI is carried out manually by executing a [release script](https://github.com/tektoncd/cli/blob/763657b92d6e9fe681ae56e28719ece75739ac29/tekton/release.sh) locally and following these [instructions](https://github.com/tektoncd/cli/blob/763657b92d6e9fe681ae56e28719ece75739ac29/RELEASE_PROCESS.md). 

Similar to what was accomplished in https://github.com/tektoncd/pipeline/issues/537, the `tkn` release process could be carried out via Prow to create the release PipelineRun/TaskRuns for rpm/deb builds. Alternatively, we could add a Triggers approach to execute the release process just via Tekton itself. 

Regardless of what approach is used, further automating the process will hopefully simplify the process for future releases/new maintainers who will have to carry out the process. 

Questions for how to accomplish this include:
* Infrastructure that will be used
* Triggering event for the process

**Comment by 06kellyjac** [comment]
Would the changes for this need to be done in https://github.com/tektoncd/plumbing ?

**Comment by vdemeester** [comment]
@06kellyjac yes
