### ISSUE TITLE
tkn pr describe failing with spec having conditions

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#1204]
# Versions and Operating System

- Kubernetes version:

  ```
  Kubernetes Version: v1.18.3+5302882
  ```

- Tekton Pipeline version:

  ```
  tkn version
  Client version: 0.13.0
  Pipeline version: v0.16.3
  ```

- Operating System:

  ```
  Fedora
  ```

# Expected Behavior

tkn pr desc command should work.

# Actual Behavior

tkn pr desc command failing

```
tkn pr desc pipelinerun-fail
Name:           pipelinerun-fail
Namespace:      tekton-pipelines
Pipeline Ref:   pipeline-fail
Timeout:        1h0m0s
Labels:
 tekton.dev/pipeline=pipeline-fail

🌡️  Status

failed to execute template: Error: template: Describe Pipelinerun:25:12: executing "Describe Pipelinerun" at <hasFailed .PipelineRun>: error calling hasFailed: runtime error: invalid memory address or nil pointer dereference
```

# Steps to Reproduce the Problem

1. Create a Pipeline with 2 tasks (one normal task and one with condition task) and the conditioned task should run after normal task. The norma task should be a failing one.
2. Create a PipelineRun for the above scenario pipeline.
3. Hit `tkn pr desc` command

OR

Use this yaml https://gist.github.com/piyush-garg/82a221f7acc50b90ce94136b6e119c61

# Additional Info

This is an intermittent issue, not happening for all the invocations. Please keep hitting the command 5-10 times to reproduce.

**Comment by danielhelfand** [comment]
In debugging this, I am seeing the TaskRun (pipelinerun-fail-success-) come back with a nil status and is experiencing the panic [here](https://github.com/tektoncd/cli/blob/62784644bb602875ddcbea4667f8b294aa257ec3/pkg/pipelinerun/description/description.go#L217). This is similar to #910.
