### ISSUE TITLE
Completion listing the respective objects

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/cli#122]
Right now after we do `source < (kn completion <shell>)`, its not able to list he existing objects  under respective commands.

e.g. If I run `tkn taskrun logs <tab>` it does not show available taskruns

**Comment by chmouel** [comment]
this should work :

https://asciinema.org/a/QxOwVxJ5ARR7cdhzKG11Thqhq

i am using osx/brew here so your mileage may vary, are you sure you have an updated ? we have only added that sometime last week,

**Comment by kameshsampath** [comment]
i am also using macOS+brew + zsh

**Comment by chmouel** [comment]
this should work, not sure why you setup is not working,  I just tested it on my workstation and it completed : 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/98980/60049156-fb4b7800-96cd-11e9-8400-29257c987c67.png">

**Comment by kameshsampath** [comment]
let me check, reinstalled the tkn

**Comment by kameshsampath** [comment]
@chmouel  - it seem to work with v0.1.2, but i do notice some other discrepancy when using it. let me open a different issue if its consistent.

**Comment by chmouel** [comment]
yeah you probably want to keep it up to date and fyi there is a brew repository here : 

https://github.com/chmouel/homebrew-tektoncd-cli/

/close
