### ISSUE TITLE
Support for when expressions

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#1222]
### Feature request

We need to add support for the new feature - When Expressions in the Cli and also deprecate the conditions along with this.

The new feature we can target is

 - Support in pipeline/pipeleinrun describe commands
 - Support in pipeline/pipeleinrun logs commands.

Feel free to add other things related to this

**Comment by danielhelfand** [comment]
Adding [When Expressions](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#guard-task-execution-using-whenexpressions) documentation here.
