### ISSUE TITLE
Display version of task in tkn task ls

### ISSUE THREAD

**Issue by sm43** [tektoncd/cli#1264]
### Feature request

It would be helpful to know which version of the task is installed. Currently, to know the version 
user has to see the YAML of the task.

### Use case

hub cli will soon have a feature to install/upgrade a task. so, to know which version is currently installed would
be helpful.

In the catalog, the version for a Task is defined as a label `app.kubernetes.io/version`

/kind feature

**Comment by PuneetPunamiya** [comment]
Is this output fine for the above issue 
```
 ./tkn task list
NAME   VERSION   DESCRIPTION              AGE
az     0.1       This task performs ...   2 days ago
```

cc @SM43  @piyush-garg  @danielhelfand

**Comment by piyush-garg** [comment]
> Is this output fine for the above issue
> 
> ```
>  ./tkn task list
> 
> NAME   VERSION   DESCRIPTION              AGE
> az     0.1       This task performs ...   2 days ago
> ```
> 
> cc @SM43 @piyush-garg @danielhelfand

This looks good, also handle the case if there is no version label/annotation

**Comment by PuneetPunamiya** [comment]
> > Is this output fine for the above issue
> > ```
> >  ./tkn task list
> > 
> > NAME   VERSION   DESCRIPTION              AGE
> > az     0.1       This task performs ...   2 days ago
> > ```
> > 
> > 
> > cc @SM43 @piyush-garg @danielhelfand
> 
> This looks good, also handle the case if there is no version label/annotation

Yes but according to TEP a resource should have version

**Comment by piyush-garg** [comment]
> > > Is this output fine for the above issue
> > > ```
> > >  ./tkn task list
> > > 
> > > NAME   VERSION   DESCRIPTION              AGE
> > > az     0.1       This task performs ...   2 days ago
> > > ```
> > > 
> > > 
> > > cc @SM43 @piyush-garg @danielhelfand
> > 
> > 
> > This looks good, also handle the case if there is no version label/annotation
> 
> Yes but according to TEP a resource should have version

But a user can create its own task or can install task from other sources

**Comment by piyush-garg** [comment]
Also, I think we should add the same for ClusterTask also

**Comment by PuneetPunamiya** [comment]
> > > > Is this output fine for the above issue
> > > > ```
> > > >  ./tkn task list
> > > > 
> > > > NAME   VERSION   DESCRIPTION              AGE
> > > > az     0.1       This task performs ...   2 days ago
> > > > ```
> > > > 
> > > > 
> > > > cc @SM43 @piyush-garg @danielhelfand
> > > 
> > > 
> > > This looks good, also handle the case if there is no version label/annotation
> > 
> > 
> > Yes but according to TEP a resource should have version
> 
> But a user can create its own task or can install task from other sources

Yes got it thanks

**Comment by chmouel** [comment]
In a further improvement for another PR it would be nice to have the version information of a task used on the *describe commands

**Comment by PuneetPunamiya** [comment]
> In a further improvement for another PR it would be nice to have the version information of a task used on the *describe commands

@chmouel  Yes sure I'll do that thanks, but what fields more need to be added to show or is it just what is the version of the resource installed ?

**Comment by chmouel** [comment]
@PuneetPunamiya what do you mean ? just the version information just under Task Ref: as Task Version (for example for taskrun describe)

**Comment by PuneetPunamiya** [comment]
@chmouel  what I meant is in the describe we just need to show only the version of the task right ??
