### ISSUE TITLE
Releases don't have version information

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/cli#1275]
# Versions and Operating System

- Operating System:

  ```
  nixOS (was using a debian container)
  ```

# Expected Behavior

From my copy I've made using `make bin/tkn` on the repo
```
./tkn version
Client version: 0.15.0
Pipeline version: unknown, pipeline controller may be installed in another namespace please use tkn version -n {namespace}
```

# Actual Behavior

```
$ wget https://github.com/tektoncd/cli/releases/download/v0.15.0/tkn_0.15.0_Linux_x86_64.tar.gz
$ ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tkn_0.15.0_Linux_x86_64.tar.gz  tmp  usr  var
$ tar xvf tkn_0.15.0_Linux_x86_64.tar.gz
LICENSE
README.md
tkn
$ ./tkn version
Error: Couldn't get kubeConfiguration namespace: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

# Steps to Reproduce the Problem

1. `wget` or `curl` release `tar.gz`
2. `tar xvf` the tar
3. `./tkn version`

**Comment by danielhelfand** [comment]
@06kellyjac Thanks for reporting this. This seems to be an unfortunate side effect of #1269 where `tkn version` is now dependent on having a kubeconfig set. We can rework our [`InitParams` func](https://github.com/tektoncd/cli/blob/e4fa245d9ba668aece6002c4677f60d63160d6e4/pkg/flags/flags.go#L92) to account for this case, but a workaround for now is to include your kubeconfig in the container you are running `tkn` in.

**Comment by 06kellyjac** [comment]
Ahh ok that makes sense.

I dont personally require version to always be available but I guess others might.
Feel free to close the issue if you don't fancy resolving this, up to you

**Comment by danielhelfand** [comment]
@06kellyjac I certainly think it's worth addressing and thanks again for raising this. Users should be able to verify the version without a cluster, so we can adapt it. Hopefully shouldn't be a difficult fix.
