### ISSUE TITLE
tkn completion foo exit=0

### ISSUE THREAD

**Issue by NissesSenap** [tektoncd/cli#1282]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"ffd68360997854d442e2ad2f40b099f5198b6471", GitTreeState:"clean", BuildDate:"2020-11-18T13:35:49Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.15.0

  ```

- Operating System:

  ```
  rhel 8.3
  ```

# Expected Behavior
tkn completion foo

Error: requires valid option got foo, expected zsh or bash

echo $?
1
# Actual Behavior
tkn completion foo

echo $?
0
# Steps to Reproduce the Problem

1. tkn completion foo
2. echo $?
3.

# Additional Info

**Comment by rupalibehera** [comment]
We can close this issue now, the fix is merged.

**Comment by chmouel** [comment]
thanks!

/close

**Comment by NissesSenap** [comment]
Thanks for the quick response as always ☺️
