### ISSUE TITLE
Start task/pipeline with optional workspace does not work properly

### ISSUE THREAD

**Issue by lstocchi** [tektoncd/cli#1290]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+6c42de8", GitCommit:"6c42de8", GitTreeState:"clean", BuildDate:"2020-09-04T14:16:02Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
 ./tkn version
Client version: 0.15.0
Pipeline version: v0.20.1
Triggers version: v0.8.1
```

- Operating System:

```
Fedora
```

# Expected Behavior

Being able to start a task/pipeline that has an optional workspace without specifying the workspace.
If the task has 2 params and 1 workspace (optional) as inputs i should be able to start the task by only passing the two params values

# Actual Behavior

Even if my task has a workspace which is optional, the cli keeps asking me to add it when i try to start the task
![image](https://user-images.githubusercontent.com/49404737/105513454-9d7c7900-5cd2-11eb-8e45-e33e5991d745.png)

# Steps to Reproduce the Problem

1. Have a task/pipeline with a param and an optional workspace
2. Try to start the task by only passing it the param value

# Additional Info

I faced this error while working on the IJ Tekton plugin. Let me know if there is a way to bypass it. Do we need to feed the cli somehow?

**Comment by vinamra28** [comment]
resolved in https://github.com/tektoncd/cli/pull/1377
/close
