### ISSUE TITLE
TestClusterTaskInteractiveStartE2E/Start_ClusterTask_with_flags consistently fails

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#1319]
`TestClusterTaskInteractiveStartE2E/Start_ClusterTask_with_flags` consistently fails on the CI, I am not sure why, but I am willing to skip it in order to unblock PRs and release.

/cc @tektoncd/cli-maintainers 
/kind test

**Comment by chmouel** [comment]
👍🏻 

I agree
