### ISSUE TITLE
`tkn pr ls <pipeline-name>` does not list the pipelinerun which is in `Running(PipelineRunPending)` state

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#1327]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5797eaecac19b9c0e4d10d3d6b559c074e3c3c88", GitTreeState:"clean", BuildDate:"2021-01-27T07:28:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bd9e442", GitCommit:"bd9e4421804c212e6ac7ee074050096f08dda543", GitTreeState:"clean", BuildDate:"2021-02-11T23:05:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.17.0
  Pipeline version: v0.22.0
  Triggers version: v0.12.0
  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior
`tkn pr ls <pipeline-name>` should list all the pipelineruns of pipeline `<pipeline-name>`

# Actual Behavior
`tkn pr ls <pipeline-name>` does not list the pipelinerun with status `Running(PipelineRunPending)`

# Steps to Reproduce the Problem

1. Create a pipeline
2. Create a pipelinerun with status `Running(PipelineRunPending)` state ([Steps](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#pending-pipelineruns))
3. List the pipelinerun using `tkn pr ls <pipeline-name>`

# Additional Info
Command logs
```
$ tkn pr ls
NAME                           STARTED       DURATION    STATUS
new-pipeline-timeout-check-1   ---           ---         Running(PipelineRunPending)
new-pipeline-run-d26zs         5 hours ago   3 minutes   Succeeded
$ 
$ tkn pr describe new-pipeline-timeout-check-1
Name:              new-pipeline-timeout-check-1
Namespace:         veeresh-testing
Pipeline Ref:      new-pipeline
Service Account:   pipeline
Timeout:           2m0s

🌡️  Status

STARTED   DURATION   STATUS
---       ---        Running(PipelineRunPending)

📦 Resources

 No resources

⚓ Params

 No params

📝 Results

 No results

📂 Workspaces

 No workspaces

🗂  Taskruns

 No taskruns
$ 
$ tkn pr ls new-pipeline
NAME                     STARTED       DURATION    STATUS
new-pipeline-run-d26zs   5 hours ago   3 minutes   Succeeded

```

**Comment by pratap0007** [comment]
@piyush-garg  This  bug has been fixed in  [pipeline v0.27.2 release ](https://github.com/tektoncd/pipeline/releases/tag/v0.27.2) , gave a try to fix it but couldn't fix.
