### ISSUE TITLE
was v0.17.1 re-released?

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/cli#1343]
I'd calculated a hash from the source tagged at v0.17.1 of `sha256-TmQJfu8tCL1sbkrEzbKM51Yev0N2Pl341ZTyOfTtR5U=` and now it's `sha256-xwUTSJ0rlNzQqGQp6jL03L4SuHUvvD3aWXxa1Xp0UyM=`

Either the hash calculation the first time messed up, or v0.17.1 was re-tagged and re-released.

**Comment by piyush-garg** [comment]
@06kellyjac I remember in the first go, some commits were missed to cherry-pick in the script, so did the branch and tagging again. But for the first wrong tag, I did not build binaries, etc. it was just branch and non-published tag

**Comment by 06kellyjac** [comment]
@piyush-garg yeah generated the hash against the source.

Thanks, good to know 🙂
I just wanted to know if there was an issue with the hashing process or a networking issue etc
