### ISSUE TITLE
Auto select the `task/pipeline` to start when there is only one `task/pipeline` installed 

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/cli#1362]
Currently when we have to start a `task/pipeline` even if there is one `task/pipeline` installed then we have to specify the name of the `task/pipeline` i.e

For task :
```
$ tkn task start <taskName>
```
OR 

For Pipeline:
```
$ tkn pipeline start <pipelineName>
```

So if there is only one task/pipeline installed then `tkn task start` or `tkn pipeline start` should start the respective `task/pipeline`

**Comment by pradeepitm12** [comment]
@PuneetPunamiya 
Thanks for creating this issue, at initial it looks very interesting to me, and this would also keep the tkn consistent with other commands to select the resource by default if only one is available.

But suppose if we have a `task/pipeline` which clears your complete cluster or something which is very less desirable and someone by mistake runs `tkn pipeline/task start`.
This will lead to unwanted outcomes.
