### ISSUE TITLE
`tkn pr logs <pr-name>` does not show logs of the task in the order that they are executed

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#1372]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5797eaecac19b9c0e4d10d3d6b559c074e3c3c88", GitTreeState:"clean", BuildDate:"2021-01-27T07:28:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+7d0a2b2", GitCommit:"7d0a2b269a27413f5f125d30c9d726684886c69a", GitTreeState:"clean", BuildDate:"2021-04-16T13:08:35Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  $ tkn version
  Client version: 0.18.0
  Pipeline version: v0.22.0
  Triggers version: v0.12.1

  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior
`tkn pr logs <pr-name>` should show logs of the task in the order that they are executed

# Actual Behavior
`tkn pr logs <pr-name>` shows the logs of the task in the order that they have been written whilte creating the pipeline.
Ex: for the below Pipeline, when the pipeline is still running the logs are shown in proper order but when the pipelinerun is completed the `tkn pr logs <pr-name> shows the log of `second-task` first and shows the log of `first-task`
```
tasks:
    - name: secondt-ask
      params:
        - name: print-message
          value: second-task
      runAfter:
        - first-task
      taskRef:
        kind: Task
        name: echo-task
    - name: first-task
      params:
        - name: print-message
          value: first-task
      taskRef:
        kind: Task
        name: echo-task
```

# Additional Info
**Command Execution logs:**
```
$ tkn p start echo-pipeline --showlog
PipelineRun started: echo-pipeline-run-2xt2t
Waiting for logs to be available...
[first-task : unnamed-0] first-task
[first-task : unnamed-0] + echo first-task

[secondt-ask : unnamed-0] + echo second-task
[secondt-ask : unnamed-0] second-task

$ 
$ tkn pr logs echo-pipeline-run-2xt2t
[secondt-ask : unnamed-0] + echo second-task
[secondt-ask : unnamed-0] second-task

[first-task : unnamed-0] first-task
[first-task : unnamed-0] + echo first-task
```

**Comment by nikhil-thomas** [comment]
im working on an update to `SortTasks` mechanismhttps://github.com/tektoncd/cli/blob/a97fa80b1b9b8362445edb94ae909f7efba16f15/pkg/taskrun/taskrun.go#L65:6

what im targetting is as follows.
if the pipeline DAG is this:
```
       A
       |
       B
     /   \
   C      D
   |      |
   |      F
    \    /
      G
       |
       H
 ```
 Then the logs from TaskRuns will be displayed in this order:  `A,B,C,D,F,G,H`

**Comment by nikhil-thomas** [comment]
In addition, I wonder what will be the default expectation of a user.
Will a user want to see the logs in the order the Tasks are defined in a Pipeline (current Behavior), while debugging.
or will a user want to see logs in the logical order in which Tasks were run in a pipeline.

**Comment by nikhil-thomas** [comment]
cc @chmouel

**Comment by chmouel** [comment]
I think your second option make sense, at least for live logs, for non live logs your first option would make more sense if that's not too much work to have to resolve the whole dag.

**Comment by nikhil-thomas** [comment]
> (maybe dashboard or pipeline would already have that logic coded in so we may want to investigate in there)

in dashboard, logs are shown per task.. they don't appear continuously in a pipelinerun scope.

> non live logs your first option would make more sense if that's not too much work to have to resolve the whole dag.

we will have to do a `reverse breadth first` traversal to generate a set, then reverse it and print logs. 🤓 
Interesting to attack, but i don't know whether it will confuse the end user. We might get complains that the taskruns are shown in some "random" (logical not pipelinespec) order. 

I will implement and try to present the difference. Then it might be easier to decide. 🧑‍💻

**Comment by nikhil-thomas** [comment]
a simpler approach might be to sort TaskRuns base on startTime. 🧑‍💻
