### ISSUE TITLE
Add a "spinner" for long running action

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1383]
### Feature request

For long running actions (i.e: gathering the logs or waiting for some stuff) we should add a spinner which make the user fuzzy and comfortable that something is happening instead of watching an empty void of nothing.

### Use case

Instead of watching voidness watch happiness with a spinner 

### UI Example

[gh cli](https://github.com/github/cli) has it you can test it when you do any action but there  is plenty of example in the spinner library : 

https://github.com/briandowns/spinner

I guess this is the one gh use and it's good enough for us :

![14](https://user-images.githubusercontent.com/98980/120528617-f1fbd780-c3db-11eb-9a03-648dc10da76f.gif)

**Comment by PuneetPunamiya** [comment]
@chmouel I have added a gif below which adds a spinner for a taskrun 

![cli-spinner](https://user-images.githubusercontent.com/32545638/145933909-ef29a5f5-fc68-4c9d-b5c3-4fe4d1ed5d7f.gif)

Is it the same what is expected ?

**Comment by chmouel** [comment]
yep perfect for a start!

**Comment by PuneetPunamiya** [comment]
Thanks!
I'll assign it to me 🙂 
/assign
