### ISSUE TITLE
prune resource  in cli

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/cli#1388]
### Feature request 
A way in tkn prune/delete resources with more options.
Maybe we can add a new `prune` command with multiple pruning  option 
or 
add more flags and param to pre-existing `delete` command 
### Use case
With tekton pipeline very soon user have hundreds of taskruns/pipelineruns in their cluster, user would like to prune some of it.
With this feature user will have an option to create a cron job with tkn cli and prune resource as required.

### UI Example

tkn taskrun prune/delete <--keep-younger-than=96h --keep-max=100 ... >

**Comment by chmouel** [comment]
Ah I didn't realise if you were working on this, feel free to improve on #1392 after it gets merged..

**Comment by vdemeester** [comment]
@chmouel @pradeepitm12 can we close this one ?
