### ISSUE TITLE
Is there a way to 'follow' or 'watch' a pipeline run? 

### ISSUE THREAD

**Issue by itscatherinelam** [tektoncd/cli#1394]
We are looking to kick off tkn pipelines using the cli tool, but find it inefficient to periodically check the status using 'tkn pipeline run describe'. Ideally, it would look something like:

- tkn pipeline start foobar --follow
- [... output of generated pipelinerun as it runs]
- [exit code]

**Comment by danielhelfand** [comment]
Would something like `--showlog` for `tkn pipeline start` meet your use case? It would basically show the logs of the PipelineRun and produce a non zero exit code if something fails during the run.

**Comment by pradeepitm12** [comment]
Hey @itscatherinelam 
I am not sure if I get this right but whenever you start a pipeline using tkn, you may get an output similar to this
```
PipelineRun started: foo-pipeline-run-zjc2d

In order to track the PipelineRun progress run:
tkn pipelinerun logs foo-pipeline-run-zjc2d -f -n namespace
```
You can use this command ` tkn pipelinerun logs foo-pipeline-run-zjc2d -f -n namespace` to get the logs and `-f` is used to follow the running pipelinrun

**Comment by itscatherinelam** [comment]
> Would something like `--showlog` for `tkn pipeline start` meet your use case? It would basically show the logs of the PipelineRun and produce a non zero exit code if something fails during the run.

This is perfect! :) No need to grep for a command. Thank you!

**Comment by itscatherinelam** [comment]
> Hey @itscatherinelam
> I am not sure if I get this right but whenever you start a pipeline using tkn, you may get an output similar to this
> 
> ```
> PipelineRun started: foo-pipeline-run-zjc2d
> 
> In order to track the PipelineRun progress run:
> tkn pipelinerun logs foo-pipeline-run-zjc2d -f -n namespace
> ```
> 
> You can use this command ` tkn pipelinerun logs foo-pipeline-run-zjc2d -f -n namespace` to get the logs and `-f` is used to follow the running pipelinrun

I'll give this option a shot, too. Although I have tried the option in the first comment in this thread and it's exactly what I was looking for :) Thank you!
