### ISSUE TITLE
Client version command doesn't work on 0.19.0 release

### ISSUE THREAD

**Issue by electrocucaracha** [tektoncd/cli#1395]
# Versions and Operating System
- Tekton Pipeline version:
`0.19.0`

- Operating System:
```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

# Expected Behavior

```bash
$ tkn version
Client version: 0.19.0
```

# Actual Behavior

```bash
$ tkn version
```
# Steps to Reproduce the Problem

1. Download [tarball](https://github.com/tektoncd/cli/releases/download/v0.19.0/tkn_0.19.0_Linux_x86_64.tar.gz)
2. Extract the binary
3. Execute `version` command

# Additional Info

**Comment by tanwald** [comment]
Same here on Fedora Server:
```
$ tkn version --component client && cat /etc/os-release | sed -n 2p && uname -r && echo $TERM
VERSION="34 (Server Edition)"
5.12.12-300.fc34.x86_64
xterm-256color
```
but not on Fedora Workstation:
```
$ tkn version --component client && cat /etc/os-release | sed -n 2p && uname -r && echo $TERM
0.19.0
VERSION="34 (Workstation Edition)"
5.12.12-300.fc34.x86_64
xterm-256color
```

**Comment by pradeepitm12** [comment]
Hey @anshulvermapatel,
Thanks for taking this up.
As we are planning for a v0.19.1 release this is something we would like to get in.
Just wanted to check if you are still on it?

**Comment by vdemeester** [comment]
@tanwald both installed through the RPMs ? 🤔

**Comment by pradeepitm12** [comment]
Fixed : https://github.com/tektoncd/cli/pull/1390
/close

**Comment by tanwald** [comment]
> @tanwald both installed through the RPMs ? 🤔 
No, I have a script that compares my version with github releases and installs the binary. That script failed on the server edition because it couldn't get the installed version any longer.

**Comment by anshulvermapatel** [comment]
Hi everyone, 

I apologize for replying late.
[#1390](https://github.com/tektoncd/cli/pull/1390) does resolve the issue where normal client version is required to be printed but if we add `--component` it still give the full output -

~~~
patel@anshuls-workstation ~  () 
$ ./tkn-linux-amd64 version
Client version: dev
patel@anshuls-workstation ~  () 
$ ./tkn-linux-amd64 version --component client
Client version: dev
~~~

After adding `--component client` the output should be 
~~~
$ ./tkn-linux-amd64 version --component client
dev
~~~

I will create a PR for this.

**Comment by anshulvermapatel** [comment]
Created [1408](https://github.com/tektoncd/cli/pull/1408)
