### ISSUE TITLE
`tkn <pr|tr> logs` to return only the available logs of a running PipelineRun/TaskRun.

### ISSUE THREAD

**Issue by riceluxs1t** [tektoncd/cli#1421]
### Feature request

Currently, `tkn` CLI  either (a) waits until completion and returns all the logs of a PR/TR (no-follow behavior) or (b) streams the logs of a running PR/TR (follow behavior).

I think a variant of the first behavior can be useful for certain use cases: return all the available logs of a running PR/TR at some point in time.

### Use case

A caller may want to **periodically** pull the logs of a running PR/TR but don't want to stay around and stream the logs until completion.

**Comment by bobcatfish** [comment]
@riceluxs1t this looks like a CLI request so I'm going to transfer this issue over there but let us know if I got it wrong. Thanks!

**Comment by riceluxs1t** [comment]
I think there is a way to achieve the behavior I want by setting the timeout value of 0s in the (a) case.
