### ISSUE TITLE
`tkn bundle push` misses the flag `--remote-registry`

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/cli#1423]
# Versions and Operating System

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  0.19.0
  ```

- Operating System:

  ```
  All
  ```

# Expected Behavior

`tkn bundle push` should have the flag `--remote-registry` through which we can specify to which registry we want to push.

# Actual Behavior

`tkn bundle push` misses the flag `--remote-registry`

**Comment by digglife** [comment]
@vinamra28 Is this supposed to be implied by the repository URL? 

```
# push to quay.io
tkn bundle push quay.io/digglife/bundle:v0.1 -f bundle.yaml
# push to docker.io
tkn bundle push docker.io/digglife/bundle:v0.1 -f bundle.yaml
```

**Comment by vinamra28** [comment]
yeah I forgot to close this :sweat_smile:. Actually `github.com/google/go-containerregistry` handles this itself so it's not required anymore.
/close
