### ISSUE TITLE
Completion doesn't work well with aliases

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#144]
# Expected Behavior

`tkn` with aliases command should still complete correctly.

```shell
$ tkn pr <tab>
describe  list      logs
```

# Actual Behavior

It does not.

```shell
$ tkn pr <tab>
completion   pipeline     pipelinerun  task         taskrun      version
```

/assign @chmouel 
/kind bug

**Comment by chmouel** [comment]
note that it only affects zsh not bash https://asciinema.org/a/UG68rjHxsw4pIz13YsokdoRQC
