### ISSUE TITLE
Start pipeline/task with empty optional workspace without answering for specifications questions

### ISSUE THREAD

**Issue by lstocchi** [tektoncd/cli#1444]
### Feature request

If you try to start a pipeline which has an optional workspace and this is voluntarily left blank the user is still asked `Do you want to give specifications for the optional workspace?`. Is there a way to bypass/prevent it?

### Use case

We are adding support for optional workspaces in our IDE tekton plugins. Users fill in the wizard with all params/workspaces to start the pipeline/task. If a workspace is optional and it's left empty, i shouldn't ask users if they are sure of their choice.

**Comment by piyush-garg** [comment]
Yup, this makes sense. If the workspace is optional, we should not ask for values in interactive flow.

cc @vdemeester @pradeepitm12

**Comment by lstocchi** [comment]
Hi @pratap0007 and sorry for the late response, i completely miss the notification.
Yes, what we need is a way to run the start command through the cli without specifying a workspace (if optional).

Something like ... if the task has 3 inputs (2 params and 1 optional workspace) i would like to run `tkn pipeline start -p .. -p ...` without that the cli asks me if i'm sure about it. Or having some other way to achieve it (a flag ... `tkn pipeline start -p .. -p ... --skip-optional`. or whatever)  

In IntelliJ/vscode we show a wizard to allow user select workspaces and other inputs required to start a task/pipeline, but, if a workspace is optional, user is free to not pick anything and click on `start`. If this happens, I should be able to run the start command in the cli without setting that optional workspace and without the cli asks me for confirmation.

Let me know if it's clear. Thank you!!

**Comment by pratap0007** [comment]
@lstocchi yes, it's clear now and thank you for clarifying it.
