### ISSUE TITLE
Remove ` --azure-container-registry-config` from docs

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#146]
Based on https://github.com/tektoncd/cli/pull/128#discussion_r299849854, and https://github.com/tektoncd/cli/pull/140 that removed this flag, we need to update the `docs` file to remove this as well

/cc @hrishin 
/kind documentation

**Comment by chmouel** [comment]
IMHO we need to spend time auto generating the documentation instead of updating it manually, ie #129

**Comment by vdemeester** [comment]
@chmouel yes might be a better investment :angel: I just wanted to make sure we get those updated, one way or another.
