### ISSUE TITLE
Should pipelineresource be grouped in the list

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#148]
Do we want to group pipelineresource by type in `tkn pipelineresource list` ? Or do we want to add an option for that ?

/cc @siamaksade  @sthaha 

Based on https://github.com/tektoncd/cli/pull/128/files#r297645542

/kind question
/kind feature

**Comment by siamaksade** [comment]
Makes sense to me. Grouping means to show as separate blocks or rather sort on type, and then creation time?

**Comment by vdemeester** [comment]
> Makes sense to me. Grouping means to show as separate blocks or rather sort on type, and then creation time?

I would pictures it like that yes

**Comment by hrishin** [comment]
Yes. Would be also nice to filter resources by one or more types like `tkn list resources -t ImageResource`
