### ISSUE TITLE
Injecting breakpoint for failed task

### ISSUE THREAD

**Issue by ileixe** [tektoncd/cli#1488]
### Feature request

I'd like to rerun task or pipeline injecting breakpoint(https://tekton.dev/docs/pipelines/debug/#breakpoint-on-failure) when the task was failed to verify what's the cause. 

### Use case

I think it's fairly common that several failures come from the environment and it's great to have the control to decide breakpoint from the failed tasks.

### UI Example

With this new parameter so called `--break-when-failed`

```bash
task start buildkit-daemonless --use-taskrun npu-tools-run-pkwbd-build --showlog --break-when-failed
```

User can access the pod using `exec` so that they can verify what the environment look like (e.g. see ssh credential, source repo mount etc..)

Thanks

**Comment by vinamra28** [comment]
Hi @ileixe, thank you for creating this. There is one more issue #1476 from @waveywaves which looks similar to this. Can you please check and see whether this issue can be tracked over there or not?

**Comment by ileixe** [comment]
@vinamra28 Cool, thanks. I think we can track from it.
