### ISSUE TITLE
how to start a pipline programmatically (generally missing examples)

### ISSUE THREAD

**Issue by lostiniceland** [tektoncd/cli#1489]
In order to build some automation we would like to integrate tkn in another simple Go program, basically just starting an existing pipeline in the cluster with some parameters.

Do I have to import tektoncd/cli or tektoncd/pipline (propably the first)? Without examples it is really hard to figure out what packages are needed and how they need to be connected.

I would be great to have some example folder like [go-git](https://github.com/go-git/go-git/tree/master/_examples) does

**Comment by jbpratt** [comment]
Hi @lostiniceland , while this isn't exactly an example and will require some digging, it may help to take a look at how the CLI is achieving this such as here to create a pipeline run:
https://github.com/tektoncd/cli/blob/2b7970b0e011dc0b64a43859893612613b126fdc/pkg/cmd/pipeline/start.go#L338-L341

**Comment by lostiniceland** [comment]
Thanks for the hint. I did some digging and found a working solution by running the cmd itself


```
import (
	"github.com/tektoncd/cli/pkg/cli"
	"github.com/tektoncd/cli/pkg/cmd/pipeline"
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

tp := &cli.TektonParams{}
tp.SetNamespace(buildNamespace)
pipelineCmd := pipeline.Command(tp)

params := []string{"start", "my-pipeline"}
pipelineCmd.SetArgs(params)
err := pipelineCmd.Execute()
```

Maybe I can utilise your sample
