### ISSUE TITLE
Wrong timie/duration appears in list/describe commands

### ISSUE THREAD

**Issue by hrishin** [tektoncd/cli#151]
# Expected Behavior
tkn list/describe commands should show the correct timing and duration information

# Actual Behavior
![image](https://user-images.githubusercontent.com/28615674/60594340-59f5ad80-9dc2-11e9-9886-e9cd35d4f7af.png)

This how it shows if a client is one timezone and cluster in a different timezone.

/kind bug

**Comment by vdemeester** [comment]
@hrishin I think it got fixed or at least I don't really see it anymore ? I think we can close (and re-open a new issue if it happens again)

/close

**Comment by hrishin** [comment]
@vdemeester :+1:
