### ISSUE TITLE
Support --task/--pipeline flag in tkn tr/pr ls

### ISSUE THREAD

**Issue by divyansh42** [tektoncd/cli#1534]
### Feature request

Similar to `tkn tr delete --task task1`, it will be good if we can list `TaskRuns/PipelineRuns` associated only with the specific `Task/Pipeline` 

### Use case

Use case will be to list out the `TaskRuns/PipelineRuns` started by a specific `Task/Pipeline`

### UI Example
```
tkn tr ls --task task1
```
or
```
tkn pr ls --pipeline pipeline1
```

**Comment by digglife** [comment]
I think you can do it with the current `tkn` by passing task/pipeline name as argument(instead of option).

List `TaskRuns` started by `task1`, or `PipelineRun` started by `pipeline1`:

```bash
$ tkn tr ls task1
$ tkn pr ls pipeline1
```

**Comment by divyansh42** [comment]
@digglife Thanks, I wasn't aware of this.
Is there any way to filter TaskRuns that are started by cluster tasks? (in the same way as a task)

**Comment by digglife** [comment]
@divyansh42 
yes we can use `--lable` selector, for example, list `taskruns` associated with `ClsuterTask` named `ct1`:

```
$ tkn tr ls --label tekton.dev/clusterTask=ct1
```

**Comment by divyansh42** [comment]
Thanks for the info!
I don't think we need this issue anymore.
