### ISSUE TITLE
Support for `tektoncd/pipeline` v1 API

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#1546]
Work on the V1 API is tracked here : https://github.com/orgs/tektoncd/projects/10

Once `tektoncd/pipeline` releases a `v1`, the cli needs to be able to support it. Creating this issue already as we should be able to add support and test ahead of time as `tektoncd/pipeline` will probably ship v1 api without publishing it to start with.

Work here will imply
- [ ] setup a "temporary" job to run an experimental pipeline version with v1 (once ready)
- [ ] implement v1 support ahead of time (behind build tag, conditional, …)

**Comment by piyush-garg** [comment]
this is done, i think we can close this issue.

cc @vdemeester if anything remaining under this epic
