### ISSUE TITLE
Remove depricated field PR.Status.TaskRuns

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/cli#1559]
With dependency bump of pipeline to v0.35.0, we need to remove `PipelineRun.Status.TaskRuns` and instead use `PipelineRun.Status.ChildStatusReference` .
[TEP](https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md) For more details

**Comment by vinamra28** [comment]
This issue was fixed in PR https://github.com/tektoncd/cli/pull/1617 and corresponding issue is https://github.com/tektoncd/cli/issues/1618. Closing this for now. Feel free to reopen it again if it seems that the issue is not fixed
/close
