### ISSUE TITLE
tkn client unable to pick up params defined in Tasks

### ISSUE THREAD

**Issue by durera** [tektoncd/cli#1569]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8+ee73ea2", GitCommit:"f7310cc5b1c14454dcd067838ca8407e9da13a26", GitTreeState:"clean", BuildDate:"2022-03-10T05:52:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
tkn version
Client version: 2020-04-01T10:57:38Z
Pipeline version: unknown

kubectl get pods -n openshift-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
v0.24.3
```

- Operating System:

```
Ubuntu 20.0.4 LTS (Windows Subsystem for Linux)
```

# Expected Behavior
We should be able to use `tkn` CLI instead of `oc create -f <pathtotaskrun>.yaml` to achieve the same end result, but without needing to faff around with yaml files.

# Actual Behavior
When we try to use `tkn` CLI it doesn't seem to recognise the task parameters correctly.

```
kubectl -n mas-fvtdev-pipelines get task mas-devops-cert-manager -o yaml
<snip>
spec:
  params:
  - default: ""
    name: mas_channel
    type: string
<snip>
```

When inspected using `tkn`, it doesn't pick up the params:
```
tkn -n mas-fvtdev-pipelines task describe mas-devops-cert-manager
Name:        mas-devops-cert-manager
Namespace:   mas-fvtdev-pipelines

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

🦶 Steps

 ∙ cert-manager

🗂   Taskruns

NAME                                STARTED       DURATION    STATUS
fvtdev-fvt-693-cert-manager-cltn9   3 hours ago   3 minutes   Succeeded
```

Similarly, if try to use the task it will throw an error saying that the parameter provided is not supported.
```
tkn task start mas-devops-cert-manager -s pipeline -n mas-djp1105-pipelines -p "mas_channel=m4dev88" --dry-run
Error: param 'mas_channel' not present in spec
```

# Steps to Reproduce the Problem

1. Have a Task with params
2. Use `tkn task describe` to view the Task, no params will be shown
3. Use `tkn task start` to start a Taskrun and provide at least one parameter, error will be thrown

# Additional Info
I wondered whether it was a version incompatability thing between the `tkn` client and the version of tekton pipelines, or whether it's some incompatability with OpenShift Pipelines, which is how we're consuming tekton ... https://docs.openshift.com/container-platform/4.8/cicd/pipelines/op-release-notes.html

**Comment by vdemeester** [comment]
> Client version: 2020-04-01T10:57:38Z

This seems to be a **very** old version. It probably means that cli version doesn't support `v1beta1` at all, making it hardly usable with most recent version of pipeline. Tekton is about 3 years old, and it moves fast (the cli as well). So a 2 year old cli is kind-of implicitely expected not to work with more recent version — *especially* as 2 years ago, Pipeline API were alpha, so they could change and break with every release.
I would suggest to update the cli to a more recent version because I am pretty sure this would fix your issue. 
It is definitely not OpenShift Pipelines as we do not modify the API or anything, we just wrap and build on top of tekton pipelines, so any cli (upstream, the one we ship, …) should work with it.

**Comment by durera** [comment]
Doh!  You know what, I didn't even notice that it was a 2020 CLI version, I was reading it as **2022-04-01**!

I followed the documention for installing the CLI here: https://tekton.dev/docs/cli/

Specifically this bit: 

> If you are using the latest releases of Ubuntu or Debian, you may use the TektonCD CLI PPA instead:
> ```
> sudo apt update;sudo apt install -y gnupg
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA
> echo "deb http://ppa.launchpad.net/tektoncd/cli/ubuntu eoan main"|sudo tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list
> sudo apt update && sudo apt install -y tektoncd-cli
> ```

The result of running that was the 2020 build of the CLI so the doc might need a touchup.  I've downloaded the latest release from the GitHub releases page and it works a treat!

**Comment by vdemeester** [comment]
/cc @chmouel @pradeepitm12 
There might be, indeed, something wrong with our launchpad setup.. or the documentation.. or both.. 🤔

**Comment by piyush-garg** [comment]
@chmouel Your PR https://github.com/tektoncd/cli/pull/1503 seems to update docs for this, this looks fixed now.

@durera Can we close this if the updated docs work ?
