### ISSUE TITLE
Way of Seeing Tekton Pipeline Version Through CLI

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#159]
/kind feature

This is a request to be able to see what version of Tekton Pipeline is being used through the CLI. These versions would correspond to these [releases](https://github.com/tektoncd/pipeline/releases).

Maybe something like `tkn pipeline version` would respond with `Pipeline Version 0.5` depending on what Pipeline version is being used.

**Comment by vdemeester** [comment]
@danielhelfand Thanks for the issue. As of now, it's a bit tricky to know the exact version deployed on the cluster as the image used in the release.yaml are using digests (and thus we can't guess the version from there).

cc @bobcatfish I feel we could have some sort of label or annotation on the controller and/or webhook service/deployment that would help *any* client know which version it is.
