### ISSUE TITLE
Add support for Parameter Array types

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#164]
See https://github.com/tektoncd/pipeline/pull/1080 (https://github.com/tektoncd/pipeline/pull/1080#issuecomment-511829354)

We may also find a way to not fail in those case (when we don't know or can't unmarshal the type :angel: )

**Comment by piyush-garg** [comment]
Seems like this has been resolved with https://github.com/tektoncd/cli/pull/223

Any other things we need to handle?

**Comment by vdemeester** [comment]
@piyush-garg I think it's all good, so let's close :stuck_out_tongue: 

/close
