### ISSUE TITLE
Pass result of a Pipeline/Task execution via exit code

### ISSUE THREAD

**Issue by keskad** [tektoncd/cli#1667]
Hi, is it intentional that the started and observed (using `--showlog`) Task/Pipeline does not have passed a result as an exit code to the shell?

**Example:**
`tkn pipeline run ...` -> Pipeline fails -> exit 1
`tkn pipeline run ...` -> Pipeline succeds -> exit 0

What about implementing a commandline switch e.g. `--pass-result-as-exitcode` to not introduce a BC but allow to return the exit code when using `--showlog`?

**Comment by pradeepitm12** [comment]
@tektoncd/cli-maintainers 
IMHO, if we are passing a specific flag to get the exit code that should be fine. Please feel free to comment suggest on this.

**Comment by chmouel** [comment]
@keskad I gave up debating which flags or commands to implement and wrote an extension addressing exactly this :-D

https://github.com/chmouel/tkn-watch/
