### ISSUE TITLE
Incomplete TaskRuns deleted when --ignore-running=true

### ISSUE THREAD

**Issue by colinodell** [tektoncd/cli#1707]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  v1.21.14-gke.700
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  v0.27.3
  ```

- Operating System:

  ```
  Alpine Linux v3.11
  ```

# Expected Behavior

Running the following command should avoid deleting TaskRuns that have not completed yet (because they are running or will run in the near future):

```
tkn tr delete -n some-namespace --keep 25 --ignore-running --force
```

# Actual Behavior

TaskRuns experiencing `ExceededResourceQuota` are unexpectedly removed, even though `Pending` TaskRuns are kept.

# Steps to Reproduce the Problem

1. Set a low pod resource quota on your namespace
2. Fill up your TaskRun queue with lots of work
3. Wait for TaskRuns to experience `ExceededResourceQuota`
4. Run `tkn tr delete --ignore-running ...`
5. Watch as those not-yet-running TaskRuns get removed

# Additional Info

I have `tkn tr delete` running periodically to help minimize the total number of TaskRun objects in my cluster, as I don't need them for more than a few minutes after they have finished running.  Although `--ignore-running=true` seems like the correct way to do this, it has the unfortunate side effect of also removing TaskRuns that haven't run yet because we've temporarily hit our pod resource quota.

I suppose `--ignore-running=true` technically works in the strictest sense, as TaskRuns waiting on available quota are not actually in a "running" state.  But given that `--ignore-running=true` preserves `Pending` TaskRuns as seen here...

https://github.com/tektoncd/cli/blob/8aa0ead4a5b8de4d012cc40b486ee41c6d55971d/pkg/cmd/taskrun/delete.go#L293-L308

... I believe the actual intent of this flag is to only delete TaskRuns that have actually completed, and this behavior does not perfectly align with that understanding.

# Proposed Solution

Perhaps instead of relying on the `reason`, we could instead check whether `completionTime` is set?  According to the docs, this seems to only be set once a TaskRun has completed for any reason (including success, failed steps, validation errors, cancellation, timeouts, etc).  Those are the exact types of TaskRuns I don't want to keep around in my cluster.

Alternatively, we could expand the 'allowlist' of reasons to include `ExceededResourceQuota` and others, but that seems less robust.

I'd love to contribute to Tekton, so if you agree that a change should be made, please let me know which approach is preferred and I'll submit a PR accordingly :)

**Comment by pradeepitm12** [comment]
@colinodell :wave: 
We did added a few more reasons to check if the taskrun has completed(:crying_cat_face: which is not perfect). 
Your proposal seems reasonable, we will be happy to get contribution. Please assign this issue to yourself.
