### ISSUE TITLE
Group commands in help message

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#179]
The help message should group the commands into logical groups and order of relevance:

Current behavior:
```
$ tkn --help

Available Commands:
  clustertask Manage clustertasks
  completion  Prints shell completion scripts
  help        Help about any command
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  resource    Manage pipeline resources
  task        Manage tasks
  taskrun     Manage taskruns
  version     Prints version information
```

Expected behavior:
```
Available Commands:
  clustertask Manage clustertasks
  task        Manage tasks
  pipeline    Manage pipelines
  pipelinerun Manage pipelineruns
  taskrun     Manage taskruns
  resource    Manage pipeline resources

  completion  Prints shell completion scripts
  help        Help about any command
  version     Prints version information
```

**Comment by girishramnani** [comment]
I can work on this.
Thinking of using Cobra Annotations. https://github.com/spf13/cobra/blob/993cc5372a05240dfd59e3ba952748b36b2cd117/command.go#L82

key for the annotation can be `command_type` or `type` and then two types for now `main` and `utility`. Then I will add the line break the Usage Template of the root command ( currently I cannot find it so probably create one ).
Thoughts?


Example of a usage template [here](https://github.com/openshift/odo/blob/0f2b414a57da63fdafa5f1908dd88da19a170fd9/pkg/odo/cli/cli.go#L44)

**Comment by girishramnani** [comment]
moving forward on this issue
