### ISSUE TITLE
integrate chocolateay with goreleaser

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1808]
goreleaser now supports chocolatery in latest version, maybe we should just include it part of goreleaser? 

cf: https://goreleaser.com/customization/chocolatey/

_Originally posted by @chmouel in https://github.com/tektoncd/cli/issues/1806#issuecomment-1327103857_

**Comment by danielhelfand** [comment]
Happy to provide account access to anyone interested in this. Definitely open to letting others manage the package.

Looks like api key will need to be set as environment var to provide goreleaser permission to push to chocolatey.org.
