### ISSUE TITLE
Missing GPG public key for version 0.29.0

### ISSUE THREAD

**Issue by shibumi** [tektoncd/cli#1848]
Hey,

version 0.29.0 is missing a public key. Do you know where I can find it? At Arch Linux we track the following keys for tekton-cli:

  '20B135DCAACDFBD90507288B52C556331AC51BFF'
  '2B68199819C7A977A9C7F5928E00E7B02807E02D'
  '426DA722C9ED3DDF28557E3D1F23F99E99873FBA'
  'D3409ED2C4FF2FFD842F26674C3B1CE0A1809F57'
  '1CA4F4F5B3F48519EDF0AF0B44B5C531CBDF0149'

**Comment by piyush-garg** [comment]
This has been fixed, thanks for reporting. Closing this.
