### ISSUE TITLE
Migrate off `pipelineResources` for cli

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/cli#1867]
Since the  `pipelineResources` are going to be removed in pipeline _v0.45_  as designed in [TEP074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md) and according to [deprecation.md](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md),  _(some have already been removed eg. [cloudevent ](https://github.com/tektoncd/pipeline/pull/5995)and [cluster](https://github.com/tektoncd/pipeline/pull/5996) PipelineResources)_, we need to migrate off the `pipelineResources` for the related in cli.

Related issue: [Handle PipelineResources when swapping v1 to the storage version #5967](https://github.com/tektoncd/pipeline/issues/5967)

**Comment by vdemeester** [comment]
@JeromeJu I think this is a duplicate of https://github.com/tektoncd/cli/issues/1657 😛

**Comment by JeromeJu** [comment]
> @JeromeJu I think this is a duplicate of #1657 😛

Thanks, I will mark this as closed and continue on #1657
