### ISSUE TITLE
Support for `minimal` to-be-removed `EmbeddedStatus`

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/cli#1868]
According to [TEP100](https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md), In pipeline _v0.44_ we have changed the `default-embedded-status` to `minimal` and are planning to remove `embedded-status`  feature flag and keep all the pipelineRunStatus behavior under minimal status in v0.45. And thus it would be much appreciated to have cli support for the updates on the `PipelineRunStatus` from cli.

cc @dibyom @vdemeester

**Comment by JeromeJu** [comment]
cc @dibyom @vdemeester

**Comment by vinamra28** [comment]
@piyush-garg  based on the reply from @JeromeJu, can we mark this issue as completed?

**Comment by vinamra28** [comment]
also I can see that there was one related PR https://github.com/tektoncd/cli/pull/1985

**Comment by vdemeester** [comment]
I think so yes 👍🏼
