### ISSUE TITLE
Add Command for Pipeline, Resource, and Task Resources

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#192]
This issue is a feature request for the ability to add custom resource definitions for `tekton.dev` resources to a Kubernetes cluster. These resources include:
* `Pipeline`
* `Resource`
* `Task`

Currently, a user must use a second tool to add these custom resources, such as `kubectl` or `oc`. Being able to do this directly through `tkn` would help with having a user not have to go back and forth with another tool while using `tkn`.

# Expected Behavior

The add command should add a particular resource under a Kubernetes namespace.

Example with `Pipeline`:

`tkn pipeline add pipeline.yaml`
* This should also be able to use raw content from a git repository url

# Additional Info

Since these features are already implemented in other Kubernetes tools, the question is how what should `tkn` overlap with for these other tools in terms of functionality versus leave to the other tools completely. 

In my opinion, I think it makes sense in this case to have the ability to also add through `tkn` along with other Kubernetes tools.

**Comment by vdemeester** [comment]
@danielhelfand can we split this issue in two ? (one for deletion, one for addition)
Thank for creating this ! :hugs:

**Comment by danielhelfand** [comment]
@vdemeester Yup, no worries. I'll separate this out.

**Comment by gavinfish** [comment]
Anyone is working this? If not, I want to take it, thanks.

**Comment by danielhelfand** [comment]
@gavinfish Thanks for your interest! It doesn't appear anyone is working on this, so feel free to pick it up and put in a pr.

**Comment by gavinfish** [comment]
Before I start to work, I want to discuss some details of this command.

1. What is the command name, `add` or `create`? Personally I prefer `create` which is compatible with `kubectl`.
2. For the input resource, I prefer to only support single yaml file(local or remote) for now. Maybe we could support stdin, directory later. 
2. What happens when adding a resource several times? Throw an exception or overwrite it?

**Comment by danielhelfand** [comment]
1. I think it makes sense to go with `create` to keep it similar to `kubectl` as you've said.

2. I think a local yaml or remote yaml is a reasonable starting point.

3. This is where we get into Imperative Management and Declarative Management. I would think we would want to keep this similar to `kubectl` again. So the create command here would respond with an error that the resource already exists. 

It probably would make sense to open another issue for replace/apply commands as well. But for the purpose of this issue, I would think not overwriting the resource if it already exists is something users will be familiar with.

**Comment by chmouel** [comment]
+1  on @danielhelfand comments!

**Comment by vdemeester** [comment]
Also see https://docs.google.com/document/d/1U712Je4gKNVcAgcGmqxdeIRS6DNXzVqQWOqZU-N7W8A/edit# :angel:

**Comment by gavinfish** [comment]
@vdemeester I do not have permission for the doc, could you please grant access to the account of drfish.me@gmail.com? thanks.

**Comment by chmouel** [comment]
@gavinfish you need to join the mailing list and you will get access to all tekton docs, see here https://github.com/tektoncd/community/blob/master/contact.md#shared-drive

**Comment by jeffmaury** [comment]
That would be a great addition for our effort around IntelliJ Tekton support (which is based on the `tkn` CLI) as it will prevent us to use `kubectl` to do Tekton resources creation

**Comment by danielhelfand** [comment]
Picking up `tkn pipeline create` for this issue.
