### ISSUE TITLE
Delete Command for Pipeline, Resource, and Task Resources

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#193]
This issue is a feature request for the ability to delete custom resource definitions for `tekton.dev` resources on a Kubernetes cluster. These resources include:
* `Pipeline`
* `Resource`
* `Task`

Currently, a user must use a second tool to delete these custom resources, such as `kubectl` or `oc`. Being able to do this directly through `tkn` would help with having a user not have to go back and forth with another tool while using `tkn`.

# Expected Behavior

The delete command should remove a particular resource from a Kubernetes namespace.

Example with `Pipeline`:

`tkn pipeline delete pipeline_name`
* This should use the name of the already created `pipeline` to find and remove the `pipeline` from the cluster namespace

# Additional Info

Since these features are already implemented in other Kubernetes tools, the question is how what should `tkn` overlap with for these other tools in terms of functionality versus leave to the other tools completely. 

In my opinion, I think it makes sense in this case to have the ability to also delete through `tkn` along with other Kubernetes tools.

**Comment by 16yuki0702** [comment]
Could I take a remaining tasks (Pipeline, Task) ??
I wrote a command for Resource on https://github.com/tektoncd/cli/pull/222

**Comment by danielhelfand** [comment]
@16yuki0702 Go for it!

**Comment by 16yuki0702** [comment]
@danielhelfand Thanks!!

**Comment by chmouel** [comment]
@16yuki0702 Thanks for working on this, can you confirm you are working on all the delete resources? I.e: Task, TaskRun, Pipeline,PipelineRun 

Thanks,

**Comment by 16yuki0702** [comment]
@chmouel yes, I'm working on all resources (Task, TaskRun, Pipeline, PipelineRun).
I'm sorry, I missed writing TaskRun, PipelineRun :sweat_smile:

Thanks !!

**Comment by 16yuki0702** [comment]
I thinks this is completed.
Could I close it??

**Comment by danielhelfand** [comment]
Yup, looks like delete is covered for every resource. Thanks, @16yuki0702!

**Comment by 16yuki0702** [comment]
@danielhelfand Thank you for your confirming!
