### ISSUE TITLE
use of Complete-Validate-Run pattern followed by oc and kubectl

### ISSUE THREAD

**Issue by girishramnani** [tektoncd/cli#197]
A suggestion to consider using complete-validate-run pattern ( used by kubectl and oc ) for cli commands.

Resources that will help with refactoring:

Kubernetes extracted some of the kubectl stuff to re-usable libraries https://github.com/kubernetes/cli-runtime
OpenShift released nice CLI Hacking Guide https://github.com/openshift/origin/blob/master/docs/cli_hacking_guide.adoc

**Comment by vdemeester** [comment]
@girishramnani this issue has stale a bit, and I don't really see any value of doing it just for the sake of it, so I'll close for now :wink:

/close
