### ISSUE TITLE
Validate resources on pipeline start

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#199]
When starting a pipeline, the CLI should validate that the resources required are provided to the CLI. Currently the CLI creates a pipeline run anyways, which fails due to missing resources

**Comment by vdemeester** [comment]
@siamaksade with interactive mode I think this is taken care of (as it will ask you for the resource if you don't provide them through flags)

**Comment by siamaksade** [comment]
@vdemeester the none-interactive mode is still available though. Wouldn't that be needed?

**Comment by vdemeester** [comment]
@siamaksade ah I think I see what you mean. If a user doesn't provide the required `--resource` and explicitely disallow interactive (which is something we are missing today) we should fail instead of silently succeeding, right ?
