### ISSUE TITLE
Failed PipelineRuns should show info about their TaskRuns when describing them `tkn pr describe`

### ISSUE THREAD

**Issue by ronanww** [tektoncd/cli#2020]
### Feature request

I have a PipelineRun that has a TaskRun which fails to schedule the pod due to PodSecurity issues

`tkn pr describe` shows the PipelineRun failed but it doesn't show any info about the TaskRun
```
$ tkn pr describe <PR_ID> -n <NAMESPACE>
...

🗂  Taskruns

 No taskruns

⏭️  Skipped Tasks

 No Skipped Tasks
```

`kubectl get pr` shows info about the TaskRun
```
$ kubectl get pr <PR_ID> -n <NAMESPACE> -o yaml
...
status:
  childReferences:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: <TR_ID>
    pipelineTaskName: <task_name>
```

It would be great if `tkn pr describe` shows info about its related TaskRuns

### Use case

Debugging issues with failed PipelineRuns

**Comment by jerop** [comment]
@ronanww thanks for opening the issue -- @tektoncd/cli-maintainers can we consider supporting `childReferences` in the CLI?

**Comment by piyush-garg** [comment]
@ronanww can you please give detail about the cli version and pipeline version you are using?

**Comment by ronanww** [comment]
@piyush-garg here it is
```
$ tkn version
Client version: 0.20.0
Pipeline version: v0.47.0-gcb.0
```

**Comment by vinamra28** [comment]
> @piyush-garg here it is
> 
> ```
> $ tkn version
> Client version: 0.20.0
> Pipeline version: v0.47.0-gcb.0
> ```

@ronanww, tkn `v0.20.0` seems to be very old release, dated `Jul 14, 2021` 😅 . We added support for `childReferences` in tkn `v0.30.0`. Can you please upgrade you tkn to newer version?

**Comment by ronanww** [comment]
thanks for noticing! I upgraded my tkn version and I now see the `childReferences`, thanks!
