### ISSUE TITLE
tkn cli fails to produce logs for older versions of the operator

### ISSUE THREAD

**Issue by acornett21** [tektoncd/cli#2035]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

Cluster that doesn't work
  ```
oc version                                                                          
Client Version: 4.12.0-202208031327
Kustomize Version: v4.5.4
Server Version: 4.10.17
Kubernetes Version: v1.23.5+3afdacb
  ```

Cluster that does work
```
oc version                                                                            
Client Version: 4.12.0-202208031327
Kustomize Version: v4.5.4
Server Version: 4.12.14
Kubernetes Version: v1.25.8+27e744f
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

TKN version that doesn't work
  ```
tkn version                                                                        
Client version: 0.31.0
Pipeline version: v0.37.5
Triggers version: v0.20.2
Operator version: v0.60.1
  ```

TKN version that does work
```
tkn version                                                                          
Client version: 0.31.0
Pipeline version: v0.44.2
Triggers version: v0.23.1
Operator version: v0.65.1
```

- Operating System:
```
sw_vers                                                                             
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
  ```

# Expected Behavior
I'd expect that any version of the CLI produces logs for any version of the operator, and there to not be mismatches from one version to the next.

# Actual Behavior
Certain version of the operator do not produce logs with the new version of the cli.

# Steps to Reproduce the Problem

1. Get the latest CLI
2. Get an older version of the operator
3. Trigger `tkn` and see that no logs ever show up in the terminal

# Additional Info

**Comment by piyush-garg** [comment]
Hey @acornett21 

```
I'd expect that any version of the CLI produces logs for any version of the operator, and there to not be mismatches from one version to the next.
```

this is not true, we cant support unlimited backward compatibility.

**Comment by acornett21** [comment]
@piyush-garg I completely disagree that it's `unlimited backwards compatibility`. If a given version of tkn cli can _trigger_ a given operator version, the cli should produce logs, simple as that. Now, if a given version of of tkn cli **can't** _trigger_ a given version of the operator, that kind of breakage in compatibility is understandable.

**Comment by joeyslalom** [comment]
Also fails for me `Pipeline version: v0.41.0` which is an LTS release

**Comment by vdemeester** [comment]
> @piyush-garg I completely disagree that it's `unlimited backwards compatibility`. If a given version of tkn cli can _trigger_ a given operator version, the cli should produce logs, simple as that. Now, if a given version of of tkn cli **can't** _trigger_ a given version of the operator, that kind of breakage in compatibility is understandable.

What "trigger" means here ?

**Comment by acornett21** [comment]
Hi @vdemeester `trigger` in this context means `kick off`, `run`, `start the process`, `initiate`, I hope this helps clarify, let me know if there are other questions.

**Comment by vdemeester** [comment]
@acornett21 ah ok, thanks. 

> @piyush-garg I completely disagree that it's `unlimited backwards compatibility`. If a given version of tkn cli can _trigger_ a given operator version, the cli should produce logs, simple as that. Now, if a given version of of tkn cli **can't** _trigger_ a given version of the operator, that kind of breakage in compatibility is understandable.

So for context on a possible explanation of why this wouldn't work — aka you can trigger a PipelineRun but not read the log — I'll *explain* what probably happens and why.

First, "triggering" a Pipeline (or Task, …), is just about creating an object. It either succeeds or fail, depending on if how the cli "creates" it is still supported or not by the server side of things.
This is, however, slightly different, from getting the logs. Getting the logs, with Tekton and `tkn`, is, *today*, solely about finding the Pods from that `PipelineRun`/`TaskRun` and fetching the logs from it. If, for some reason, something change into how we can find the pods, it "might" affect thi cli (`tkn`) or any client to that matter. And this is essentially what happened with this [TEP](https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md). It went over a few releases, but we went from having all the `TaskRun` status (and thus the `podname` as well) directly in a `PipelineRun` status to not having those any more and having to query `TaskRun`s to get that extra information. That means, older version of the cli, on recent version of a `tektoncd/pipeline` instance cannot get the `Pod` information and thus the logs, *even though* they can trigger a `Pipeline` (aka create a `PipelineRun`).

> I'd expect that any version of the CLI produces logs for any version of the operator, and there to not be mismatches from one version to the next.

This can only be true, in the Tekton world, with stable `v1` APIs (according to [API compatibility policy](https://github.com/tektoncd/pipeline/blob/main/api_compatibility_policy.md)), as only `v1` gives us the guarantee that *no field* will be deleted. The `v1` API of `tektoncd/pipeline` has not being available for that long, which means, a lot of old version of the cli (`tkn`) uses `v1beta1` and thus, we don't have that guarantee, so one version that worked 9 month or a years ago (or more), was not guaranteed to still work.
