### ISSUE TITLE
Tkn bundle list split yamls

### ISSUE THREAD

**Issue by Lima118** [tektoncd/cli#2091]
### Feature request

It would be a useful feature for us when we use tkn bundle list on an OCI image, that contains multiple tasks/pipelines the output would be a valid merged yaml file. Right now it does not separate the yamls with ---. Therefor if we use tkn bundle list, then pipe it to kubectl apply it only applies the last task/pipeline, not all of them.

### Use case

If it would be implemented we could use bundle to bundle a Pipeline with all of its Tasks into one OCI Image, then we could version control our Pipelines and could easily deploy them from CI with one tkn bundle list piped into kubectl apply.

**Comment by piyush-garg** [comment]
/unassign @RohanGlitched 
/assign @lcarva 

as @lcarva has raised the PR
