### ISSUE TITLE
Support `CustomRun` list command.

### ISSUE THREAD

**Issue by stillfox-lee** [tektoncd/cli#2195]
Ref: https://github.com/tektoncd/cli/issues/1623#issuecomment-1848964123

I plan to implement the `List` command for `CustomRun`. Since the label of `CustomTask` is custom, the main difference between it and `TaskRun` is that it does not support filtering by the "Name".

# UI Example

`tkn customruns -h`
Manage CustomRuns

Usage:
tkn customrun [flags]
tkn customrun [command]

Aliases:
  customrun, cr, customruns

Available Commands:
  list        Lists CustomRuns in a namespace

Flags:
  -c, --context string      name of the kubeconfig context to use (default: kubectl config current-context)
  -h, --help                help for customrun
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)
  -C, --no-color            disable coloring (default: false)

--- 

`tkn customruns list -h`
Lists CustomRuns in a namespace

Usage:
tkn customrun list [flags]

Aliases:
  list, ls

Examples:
  List all CustomRuns in namespace 'bar':

    tkn cr list -n bar

Flags:
  -A, --all-namespaces                list CustomRuns from all namespaces
      --allow-missing-template-keys   If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats. (default true)
  -h, --help                          help for list
      --label string                  A selector (label query) to filter on, supports '=', '==', and '!='
      --limit int                     Limits the number of CustomRuns. If the limit value is 0 returns all
      --no-headers                    do not print column headers with output (default print column headers with output)
  -o, --output string                 Output format. One of: (json, yaml, name, go-template, go-template-file, template, templatefile, jsonpath, jsonpath-as-json, jsonpath-file).
      --reverse                       list CustomRuns in reverse order
      --show-managed-fields           If true, keep the managedFields when printing objects in JSON or YAML format.
      --template string               Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].

Global Flags:
  -c, --context string      name of the kubeconfig context to use (default: kubectl config current-context)
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)
  -C, --no-color            disable coloring (default: false)

**Comment by piyush-garg** [comment]
assign @stillfox-lee
