### ISSUE TITLE
`tkn` should fail in case of invalid subcommands

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#22]
When a subcommand is invalid **but** have a flag (here `-n`) it should still fail, but it currently does not.

# Expected Behavior

```bash
$ tkn pipeline foo -n pipeline-demo
# […]
$ echo $?
1
```

# Actual Behavior

```bash
$ tkn pipeline foo -n pipeline-demo
$ echo $?
0
```

**Comment by ndeloof** [comment]
Built from master (9c9cf45286ea294d51e5d62e4b5ae21cc44a4fd5) and an invalid subcommand (with or without flag) don't return a failure status

```
➜ (master ✓) cli ./tkn pipeline foo
➜ (master ✓) cli echo $?
0
```

**Comment by chmouel** [comment]
Just to add a bit more info, from master as of today, I am getting : 

```
% ./tkn pipeline foo
Error: Couldn't get kubeConfiguration namespace: invalid configuration: no configuration has been provided
[....]]
Couldn't get kubeConfiguration namespace: invalid configuration: no configuration has been provided
% echo $?
1
```

but when the kubeConfiguration is set properly it would exit 0 when it should have been 1

**Comment by vdemeester** [comment]
It is still failing :sweat: 

```
$ tkn taskrun foo
$ echo $?
0
```
