### ISSUE TITLE
Released source tarball should have its version number

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#231]
If i take the released source tarball from for example :

https://github.com/tektoncd/cli/archive/v0.2.2.tar.gz

compile it and do a :

```
tkn version
```

It would come back with `Client version: dev` When it should be `0.2.2`

/kind bug

**Comment by chmouel** [comment]
modifying : 

https://github.com/tektoncd/cli/blob/b5a87fd020373ed8c8931c11b226b665a17f1083/pkg/cmd/version/version.go#L32

to the released version with goreleaser?

wdyt @vdemeester

**Comment by vdemeester** [comment]
@chmouel something to think about :angel:

**Comment by chmouel** [comment]
perhaps having a VERSION file created in the source directory from goreleaser, and Makefile would pick it up and pass it the right ldflag

**Comment by chmouel** [comment]
This wasn't fixed, let's find another way

**Comment by chmouel** [comment]
/close

This works now

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/98980/66110985-2d6f4e80-e5c8-11e9-83ca-685ad4e3f8e5.png">
