### ISSUE TITLE
cli option to cascade delete taskrun and pipelinerun while deleting task, pipeline

### ISSUE THREAD

**Issue by nikhil-thomas** [tektoncd/cli#233]
This issue is an improvement on https://github.com/tektoncd/cli/issues/193 (Delete Command for Pipeline, Resource, and Task Resources)

# Expected Behavior

Provide a cli flag to optionally enable cascade deletion of relevant pipelineruns/taskruns while deleting pipelines/tasks.

Keep the option disabled by default.

# Additional Info

I think this feature will be useful while iteratively building a task/pipeline.

**Comment by 16yuki0702** [comment]
Can I take this task too ??
(related to  https://github.com/tektoncd/cli/pull/235)

**Comment by chmouel** [comment]
sure feel free to assign yourself!

**Comment by 16yuki0702** [comment]
Thank you very much !!

**Comment by 16yuki0702** [comment]
I thinks this is completed.
Could I close it??

**Comment by vdemeester** [comment]
@16yuki0702 indeed, thanks :hugs: 
/close
