### ISSUE TITLE
ci: Add a Linter check for incoming PRs

### ISSUE THREAD

**Issue by Pradumnasaraf** [tektoncd/cli#2416]
Hey,

I was looking around and saw no Golang Linters are running (GitHub Workflow) for incoming Pull Requests, there is just a CodeQL running. 

Let me know if you need help with that.

**Comment by AlanGreene** [comment]
Hi @Pradumnasaraf. Thanks for the offer. In general the Tekton projects use a number of tools as part of the CI process. For the most part GitHub Actions are used for CodeQL and Dependabot, but Prow and Tekton itself are used for the majority of the other CI checks such as unit tests, integration tests, linting, etc..

Both gofmt and golangci-lint (among other checks) are already run on all PRs as part of the pull-tekton-cli-build-tests check which currently runs on Prow.

Here's a recent example: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_cli/2411/pull-tekton-cli-build-tests/1846106084037627904

**Comment by Pradumnasaraf** [comment]
Hey Alan,
Thanks for explaining in detail. Got it. 

Then I will go ahaed and close this issue. Good luck, happy Open Source :)
