### ISSUE TITLE
Refactor Limit Option

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#243]
The `--limit` option is available for the following commands:
* `tkn pr ls`
* `tkn tr ls`
* `tkn p logs`

As mentioned in #228, Cobra has [validation features](https://github.com/tektoncd/cli/pull/228#discussion_r316496292) as part of the framework. The validation used for the commands above can be switched over to utilize Cobra's validation methods. The validation would focus on validating whether the user's input is a positive number.

Additionally, `tkn pr ls` and `tkn tr ls` both use `-l` as their shorthand. `tkn p logs` uses `-L` due to the fact the `--last` flag for `tkn p logs` has its shorthand as `-l`. It would be better to try and make this consistent across the CLI by using `-L` instead of `-l` for `--limit`.

**Comment by piyush-garg** [comment]
@danielhelfand  I think this has been fixed, can you please check and close. We did the refactoring regarding flags

**Comment by danielhelfand** [comment]
@piyush-garg Part of the issue has been addressed (i.e. using `-L` for `--limit`). We are still using a `< 0` check for validation though. By no means is there anything wrong with this, but it would be nice to use what Cobra has built in to remove the need for a check.
