### ISSUE TITLE
Add e2e tests for delete commands

### ISSUE THREAD

**Issue by 16yuki0702** [tektoncd/cli#244]
# Expected Behavior
Delete command for Pipeline, PipelineRun, Resource, Task, TaskRun shoud be included in e2e test.
This will be added after these merged https://github.com/tektoncd/cli/pull/235 https://github.com/tektoncd/cli/pull/236 https://github.com/tektoncd/cli/pull/237 https://github.com/tektoncd/cli/pull/238

# Actual Behavior

# Steps to Reproduce the Problem

# Additional Info

**Comment by 16yuki0702** [comment]
I thinks this is completed.
Could I close it??

**Comment by vdemeester** [comment]
@16yuki0702 indeed, thanks
/close
