### ISSUE TITLE
taskrun logs should have an interactive menu

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#263]
# Expected Behavior

The same way pipelinerun logs ask for an interactive menu, we would like one on the taskrun logs

# Actual Behavior

Nada

**Comment by 16yuki0702** [comment]
Can I take on this task??

**Comment by chmouel** [comment]
Please feel free to do so, 🙇

**Comment by 16yuki0702** [comment]
> Please feel free to do so, 🙇

Thanks!!

**Comment by danielhelfand** [comment]
/close

Addressed by #491
