### ISSUE TITLE
Pipeline logs help has a typo

### ISSUE THREAD

**Issue by VeerMuchandi** [tektoncd/cli#278]
# Expected Behavior
When you run a pipeline it displays a help on how to see logs as below

There is a typo in that help

# Actual Behavior
Pipeline run displays the help
As an example running the pipeline displays the following
```
tkn pipeline start deploy-pipeline -s pipeline -r app-git=sourcecode-git -r app-image=application-image
Pipelinerun started: deploy-pipeline-run-hhxkh

In order to track the pipelinerun progress run:
tkn pipelinerune logs deploy-pipeline-run-hhxkh -f
```

Note the spelling mistake `pipelinerune` instead of `pipelinerun`. If the user copies and pastes the line, it doesnt work.

# Steps to Reproduce the Problem

Run a pipeline as mentioned above

# Additional Info

**Comment by danielhelfand** [comment]
@VeerMuchandi Thanks for pointing this out and sorry for the issue. I believe this was addressed in #271.

**Comment by vdemeester** [comment]
@danielhelfand indeed :angel: 
/close

**Comment by chmouel** [comment]
we probably going to do a 0.3.1 for this, since multiple people has been asking abotu it,
