### ISSUE TITLE
Feature Request: tkn condition list Command

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#286]
This issue is a feature request to be able list conditions available in a namespace. The command would require the addition of a new subcommand for conditions.

My proposal would be `tkn condition` with `tkn cond` as shorthand for the condition subcommand. The full command would be `tkn condition list` for listing conditions in a namespace.

### Expected Behavior

`tkn condition list` should list all conditions available in a namespace. As of now, the only field I can think of to display for conditions returned would be their names and when the conditions were created.

**Comment by 16yuki0702** [comment]
Can I work on this??

**Comment by vdemeester** [comment]
> Can I work on this??

of course :hugs: :heart_eyes_cat:

**Comment by piyush-garg** [comment]
Fixed with #319 

/close
