### ISSUE TITLE
Command Suggestions for Incorrect Subcommands

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#291]
Currently, the CLI is able to recognize when a command does not exist:

```
$ tkn hhhk
Error: unknown command "hhhk" for "tkn"
Run 'tkn --help' for usage.
```

It is also able to recommend commands and make suggestions if an incorrect command is entered that is similar to another command:

```
$ tkn pip
Error: unknown command "pip" for "tkn"

Did you mean this?
	pipeline
	pipelinerun

Run 'tkn --help' for usage.
```

The CLI is not able to do the above mentioned things for commands of a subcommand (e.g. `tkn pr ls` :

```
$ tkn pr lssssssss
Manage pipelineruns

Usage:
  tkn pipelinerun [command]

Aliases:
  pipelinerun, pr, pipelineruns

Available Commands:
  cancel      Cancel the PipelineRun
  delete      Delete a pipelinerun in a namespace
  describe    Describe a pipelinerun in a namespace
  list        Lists pipelineruns in a namespace
  logs        Show the logs of PipelineRun

Flags:
  -h, --help                help for pipelinerun
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)

Use "tkn pipelinerun [command] --help" for more information about a command.
```

# Expected Behavior

The CLI should display an error message that the command does not exist and suggest to the user to run `--help`. It should recommend commands if what is entered is close to a valid command, such as the example below:

```
$ tkn pr l

Error: unknown command "l" for "tkn pr"

Did you mean this?
	list

Run 'tkn pr --help' for usage.
```

# Actual Behavior

```
$ tkn pr l
Manage pipelineruns

Usage:
  tkn pipelinerun [command]

Aliases:
  pipelinerun, pr, pipelineruns

Available Commands:
  cancel      Cancel the PipelineRun
  delete      Delete a pipelinerun in a namespace
  describe    Describe a pipelinerun in a namespace
  list        Lists pipelineruns in a namespace
  logs        Show the logs of PipelineRun

Flags:
  -h, --help                help for pipelinerun
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)

Use "tkn pipelinerun [command] --help" for more information about a command.
```

# Steps to Reproduce the Problem

1. Run `tkn pr l`

# Additional Info

This is similar to #183. The idea here is that displaying the help message doesn't necessarily tell the user what is wrong. In my opinion, it's a better idea to suggest to the user to run `--help` instead of throwing a lot of information from help back at them as a response.

**Comment by hrishin** [comment]
Sounds reasonable 
WDYT?

@chmouel @vincent-pli

**Comment by chmouel** [comment]
Sounds good to me, i made a fix sometime ago for the root command https://github.com/tektoncd/cli/commit/1c270872a047ece618b117c060e6d34a57f064c1 and I guess I should have think about the subcommands!

**Comment by vdemeester** [comment]
:+1:
