### ISSUE TITLE
Cannot compile with go1.13

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#298]
I have just updated to the newly released go 1.13 and cannot seem to compile :

```
% make bin/tkn
go build  -v -o bin/tkn ./cmd/tkn
go: github.com/apache/thrift@v0.12.0 used for two different module paths (git.apache.org/thrift.git and github.com/apache/thrift)
% go version
```

/kind bug

**Comment by chmouel** [comment]
/assign

we are not the only ones it seems https://github.com/minio/minio/issues/8201

**Comment by chmouel** [comment]
/unassign

Things that works on 1.12 doesnt on 1.13 and vice versa, not sure what the solution is but until then i am going to backport to 1.12 on my system

(which do sux)

**Comment by chmouel** [comment]
we finally found a way and this should be working on go1.13 now
(until the next breakage)

**Comment by ChanForPres** [comment]
doesn't work for me.. go1.13

**Comment by chmouel** [comment]
any chances you can get us more details? 

it does work for me : 

![image](https://user-images.githubusercontent.com/98980/64591742-cdabcc00-d3aa-11e9-9311-a52dd1d6d395.png)
