### ISSUE TITLE
 Auto completion support for the zsh shell

### ISSUE THREAD

**Issue by hrishin** [tektoncd/cli#31]
# Expected Behavior
Add `zsh shell` support for `tkn completion SHELL` command. 
```
tkn completion SHELL zsh
```
# Actual Behavior
At this moment `tkn completion SHELL` supports `bash shell`.

**Comment by chmouel** [comment]
/assign

Related :  

https://github.com/tektoncd/cli/blob/92d202682b87f8d92e2f7ecb502c3c78823dcaed/pkg/cmd/completion/completion.go#L46-L56

Trying to enable it with : 

```diff
@@ -34,21 +34,22 @@ Supported Shells:
   source bash_completion.sh
 `
 )
+
 func Command() *cobra.Command {
 	var cmd = &cobra.Command{
 		Use:       "completion SHELL",
 		Short:     "Prints shell completion scripts",
 		Long:      desc,
 		Args:      exactValidArgs(1),
-		ValidArgs: []string{"bash"},
+		ValidArgs: []string{"bash", "zsh"},
 		Example:   eg,
 		RunE: func(cmd *cobra.Command, args []string) error {
 			switch args[0] {
 			case "bash":
 				return cmd.Root().GenBashCompletion(os.Stdout)
-				// TODO add zsh completion
-				// case "zsh":
-				// return cmd.Root().GenZshCompletion(os.Stdout)
+			// TODO add zsh completion
+			case "zsh":
+				return cmd.Root().GenZshCompletion(os.Stdout)
 				// NOTE: cobra v0.0.3 zsh completion seems fail on zsh 5.5.1
 			}
 			return nil

```

and then inspect the generation from `tkn completion zsh` it seems that the completion generated is supposed to go in your [fpath](http://zsh.sourceforge.net/Doc/Release/Functions.html) and cannot be evaluated directly. If I put in my fpath it would then work as per this screen recording : 

https://asciinema.org/a/JbNcp2ftD0Kr2XwvFdsvIl3vF

Kubenertes is doing some nifty trick to be able to do some source <(kubectl completion zsh) with the tail and the head of the generated function : 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion/completion.go#L305

We may want to adjust our completion system to do the same

**Comment by chmouel** [comment]
Reading a bit more about this, kubectl is even sneakier, they won't use any of the stuff from cobra GenZSH completion they are doing it via the `bashcominit` bash completion to zsh  extension, probably because it predate the support of zsh completion in cobra :  

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion/completion.go#L302
