### ISSUE TITLE
Display order of executions

### ISSUE THREAD

**Issue by naiduasn** [tektoncd/cli#314]
# Expected Behavior
When we use DAG with tekton pipelines, we may execute a few tasks in parallel and few in sequential. 
How will I show how these tasks are executed in the pipeline? The current command displays only tasks executed and its status.
 
# Actual Behavior
```
tkn pipelinerun describe demo-pipeline-run-1568365482915
Name:              demo-pipeline-run-1568365482915
Namespace:         default
Pipeline Ref:      demo-pipeline
Service Account:   naidu-sa-git-ssh

Status
STARTED      DURATION    STATUS
2 days ago   7 minutes   Succeeded

Resources
NAME                RESOURCE REF
git-demo-resource   git-demo-resource

Params
No params

Taskruns
NAME                                                       TASK NAME            STARTED      DURATION    STATUS
demo-pipeline-run-1568365482915-demo-unit-tests-2-86ldw    demo-unit-tests-2    2 days ago   3 minutes   Succeeded
demo-pipeline-run-1568365482915-demo-unit-tests-1-d48l2    demo-unit-tests-1    2 days ago   3 minutes   Succeeded
demo-pipeline-run-1568365482915-demo-build-compile-mgw2n   demo-build-compile   2 days ago   3 minutes   Succeeded
```

# Steps to Reproduce the Problem

1. Execute any pipeline with DAG
2. Check tkn pipeline describe 
3.

# Additional Info
Even if this is not possible from CLI, would love to see if i can get this info from any tekton API, so that i can configure my UI.

**Comment by chmouel** [comment]
a tree perhaps? that's probably not going to be trivial to implement and represent,

**Comment by naiduasn** [comment]
@chmouel yes. is it possible to get this info of these tasks order execution via an API?

**Comment by chmouel** [comment]
I don't believe we have this information but i may be wrong, wdyt @vdemeester

**Comment by vdemeester** [comment]
@naiduasn This has nothing to do with `triggers`, but indeed, in order to get the DAG "tree", as of today, you may need to write your own code. We may want to write something in the `dag` package in `tektoncd/pipeline` as a helper though…
