### ISSUE TITLE
How to get logs of pipeline resources?

### ISSUE THREAD

**Issue by naiduasn** [tektoncd/cli#322]
# Expected Behavior
Is there any way I can get pipeline resource logs? i do not see this info logged anywhere.

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by danielhelfand** [comment]
Hey @naiduasn! Thanks for opening this.

Could you describe a use case of this? As in, you want to see a pipeline resource reference appear in a pipelinerun or taskrun logs? Something different?

**Comment by vdemeester** [comment]
@naiduasn `PipelineResource` do not have any logs. When you are using a `PipelineResource`, it will add one or more extra step to the `Pod` executing the `Task`… So the logs *related to* `PipelineResource`(s) are in the `TaskRun` logs. There is a flag (for both `TaskRun` and `PipelineRun`) to display **all** logs from the `Pod` (including internal containers that are related to the `PipelineResource`(s))

```
--all         -- show all logs including init steps injected by tekton
```

/close
