### ISSUE TITLE
Feature Request: Delete Command for Condition Resources

### ISSUE THREAD

**Issue by 16yuki0702** [tektoncd/cli#341]
This issue is a feature request for the ability to delete condition resources like this https://github.com/tektoncd/cli/issues/193

# Expected Behavior
The delete command should remove a condition resource from a Kubernetes namespace.
Example:

```
tkn condition delete condition_name
tkn cond rm condition_name
```

**Comment by piyush-garg** [comment]
Fixed by #346

/close
