### ISSUE TITLE
Start task and follow logs

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#368]
It would be useful to add a flag to immediately follow logs after starting a task since very often that's what user wants to do:

```
$ tkn task start my-task -f
```

Instead of:
```
$ tkn task start my-task 
$ tkn task logs my-taskrun-dwef -f
```

**Comment by vdemeester** [comment]
/kind feature
we have that for `pipeline` (#345), so once #347 gets in we need to make sure we add that

**Comment by chmouel** [comment]
Just want to make sure we have the same behaviour between pipeline and task, we are following the logs immediately after starting a pipeline, if we are only following just after the `-f`  flag for tasks we should standardize that across all the `start` feature,

Either way personally I don't mind,

**Comment by siamaksade** [comment]
@chmouel  Same behaviour as #345 is fine with the `--showlog` flag
