### ISSUE TITLE
Flag to print PipelineRun when calling `tkn pipeline start`

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/cli#372]
# Expected Behavior

I'd like to be able to see the PipelineRun that `tkn` generates before I decide to actually start it.

# Actual Behavior

At the moment `tkn pipeline start` runs the pipeline but cannot show me what the PipelineRun will be before I start it.

# Steps to Reproduce the Problem

1. tkn pipeline start <name-of-pipeline> <flags-for-pipeline>

# Additional Info

I'm using `tkn` for a public release of Tekton Pipelines. Before I commit the PipelineRun that will do the release I'd like to review it (and maybe even copy/paste it somewhere else for other people to see).

**Comment by danielhelfand** [comment]
So this reminds me a lot of how `terraform` has a `terraform plan` command that allows someone to view what is about to happen before an action command is run. 

Perhaps something like `tkn pipeline start pipeline-name -r resource=pipeline_resource --plan` would output a similar description to a `tkn pr describe`?

**Comment by chmouel** [comment]
I would imaging something more like `--dry-run` that would just output a yaml file instead so we can apply it manually after (or use start --dry-run as a generator before versioning)?

**Comment by danielhelfand** [comment]
@chmouel I think supporting both an option for a file but also having an option to view it just via output would make sense. But think `--dry-run` makes sense.

**Comment by chmouel** [comment]
@danielhelfand Fair enough! let's capture both then :)
