### ISSUE TITLE
RFE: Interactive prompt when asking for choices

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#38]
It would be nice when asking for multiple choices unless overriden by a CLI switch to have an interactive prompt like the for example the way `jenkinx-x/jx` is doing.

This is the library used here : 

https://github.com/AlecAivazis/survey

An example of multiple choices :  

![image](https://user-images.githubusercontent.com/98980/58419012-b3631200-8089-11e9-97fe-6b7dfa8d016d.png)

In practice this could look like this, when for example we do : 

`tkn pipelineruns logs`

with no options

ask for a namespace (default to current) 
ask for a pipelinerun from an interactive multiple choices (default to the only one if there is only one)

if -t is specified with no argument and with a task : 

ask for a task  from a list of arguments

**Comment by vdemeester** [comment]
@chmouel as we already have this for a few subcommand, I think we can close this one and make specific issue for the subcommand we want those in.

/close
