### ISSUE TITLE
Cannot set timeout when starting a taskrun

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/cli#433]
# Expected Behavior
I would like to be able to set the timeout when starting a taskrun via
```
tkn task start [task-name] 
``` 

https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#syntax

# Actual Behavior

Timeout is not available
```
Start tasks

Usage:
tkn task start task [RESOURCES...] [PARAMS...] [SERVICEACCOUNT] [flags]

Aliases:
  start, trigger

Examples:

# start task foo by creating a taskrun named "foo-run-xyz123" from the namespace "bar"
tkn task start foo -s ServiceAccountName -n bar

For params value, if you want to provide multiple values, provide them comma separated
like cat,foo,bar


Flags:
  -h, --help                     help for start
  -i, --inputresource strings    pass the input resource name and ref as name=ref
  -l, --labels strings           pass labels as label=value.
  -L, --last                     re-run the task using last taskrun values
  -o, --outputresource strings   pass the output resource name and ref as name=ref
  -p, --param stringArray        pass the param as key=value or key=value1,value2
  -s, --serviceaccount string    pass the serviceaccount name

Global Flags:
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)
  -C, --nocolour            disable colouring (default: false)
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by afrittoli** [comment]
As a side note, `tkn` should have a `dry-run` mode to output the created resource to console (in JSON or YAML), so that the output can be piped to a stream editor (like `sed` or `jq`) and edited on the fly or dumped into a file for future re-use.
I believe there is already an issue open about this

**Comment by danielhelfand** [comment]
@afrittoli #372 discusses the idea of a dry-run option for pipelineruns, but makes sense to have the same idea for taskruns. Specifying a timeout sounds reasonable as well.

#400 is introducing a `waitUntilPodNameAvailable` available method with a timeout parameter. We can add an option to make this configurable via user input.
