### ISSUE TITLE
Chocolatey Package for tkn

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#448]
Would be nice if we could offer a package manager solution for Windows installation. Currently, the installation process we recommend is very manual. Chocolately seems to be the preferred Windows option, so we should look into it at some point. Here is the [creation guideline](https://chocolatey.org/docs/create-packages) for making a package.

# Expected Behavior

`choco install tkn` installs `tkn` on a Windows machine

**Comment by chmouel** [comment]
I think if we are implementing this we will need someone who can step up to be the "windows maintainer", that can test the release on windows, add features/fixes etc....

**Comment by danielhelfand** [comment]
@chmouel Willing to be that person, or at least get it started for someone else who wants to own it. I have a Windows machine, so more than willing to help with the things you have mentioned.

**Comment by chmouel** [comment]
really nice thank you ✌️

>

**Comment by danielhelfand** [comment]
Chocolatey package available [here](https://github.com/danielhelfand/chocolatey-tektoncd-cli) for now. Waiting on approval from Chocolatey reviewers on making the package available. Will wait to include in README until it receives approval.

**Comment by chmouel** [comment]
Really nice, thanks!
