### ISSUE TITLE
Add to the Krew plugin index

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#45]
[Krew](https://github.com/kubernetes-sigs/krew/) is the plugin manager for `kubectl`. Tekton CLI should be added to the Krew plugin index to make it easy to discover and install it:
https://github.com/kubernetes-sigs/krew-index

```
kubectl krew install tkn
```

**Comment by chmouel** [comment]
Relevant: https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md

**Comment by chmouel** [comment]
it only need to have a [manifest](https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md#writing-a-plugin-manifest) written and uploaded to the [krew index,](https://github.com/kubernetes-sigs/krew-index/tree/master/plugins). We may want to wait to release a 1.0 or something stable and feature-ful enough before proposing it to the krew index?

: 

```
 % ln -sf $PWD/tkn $HOME/bin/kubectl-tkn;rehash
 % kubectl tkn pipeline
Error: pipeline requires a subcommand; see help
[...]
```
