### ISSUE TITLE
Cannot `go get github.com/tektoncd/cli/cmd/tkn@latest`

### ISSUE THREAD

**Issue by tkinz27** [tektoncd/cli#454]
# Expected Behavior

The cli would get installed to `$GOBIN`

# Actual Behavior

```
❯ go get -v github.com/tektoncd/cli/cmd/tkn
github.com/tektoncd/cli/pkg/cmd/clustertask
github.com/tektoncd/cli/pkg/cmd/condition
github.com/tektoncd/cli/pkg/cmd/pipelineresource
github.com/tektoncd/cli/pkg/cmd/taskrun
# github.com/tektoncd/cli/pkg/cmd/taskrun
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/taskrun/cancel.go:63:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/taskrun/delete.go:68:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/taskrun/describe.go:133:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/taskrun/logs.go:78:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
# github.com/tektoncd/cli/pkg/cmd/clustertask
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/clustertask/delete.go:69:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
# github.com/tektoncd/cli/pkg/cmd/condition
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/condition/delete.go:68:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
# github.com/tektoncd/cli/pkg/cmd/pipelineresource
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/pipelineresource/delete.go:69:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
/home/kinsley/go/pkg/mod/github.com/tektoncd/cli@v0.5.0/pkg/cmd/pipelineresource/describe.go:88:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
```

# Steps to Reproduce the Problem

```
go get -v github.com/tektoncd/cli/cmd/tkn@{v0.5.0,latest}
```

# Additional Info

```
❯ go version
go version go1.13.3 linux/amd64
```

Also the readme says to run

```
go get github.com/tektoncd/cli@v0.5.0
```

and that runs, but since thats just the module path and not the binary path it doesn't actually install anything.

I've also made sure I was not using `go get -u` in case there was something going on such as when installing [`gopls`](https://github.com/golang/tools/blob/master/gopls/doc/user.md)

> Do not use the -u flag, as it will update your dependencies to incompatible versions.

I do not know what conditions cause `gopls` to run into that issue.

**Comment by tkinz27** [comment]
When I run the build with `-mod=readonly` i get failures.

```
❯ go build -mod=readonly ./cmd/tkn
go: updates to go.sum needed, disabled by -mod=readonly
```

**Comment by chmouel** [comment]
This is weird, I have a fork of cobra for zsh completions fixes (upstream doesnt seem to care to merge them) which would have those functions, 

I don't know much about go modules and go install but is it the `@latest` that cause the problem ?

```
% docker run -v $PWD:/go/src/github.com/tektoncd/cli -it golang:1.13
root@a7e95c16d525:/go# export GO11MODULES=on
root@a7e95c16d525:/go# go get -v github.com/tektoncd/cli/cmd/tkn@latest
go: cannot use path@version syntax in GOPATH mode
root@a7e95c16d525:/go# go get -v github.com/tektoncd/cli/cmd/tkn
github.com/tektoncd/cli/vendor/k8s.io/apimachinery/pkg/selection
[....]
github.com/tektoncd/cli/cmd/tkn
root@a7e95c16d525:/go# ls bin/tkn
bin/tkn
root@a7e95c16d525:/go#
```

which version of golang are you using?

/kind bug

**Comment by vdemeester** [comment]
From https://github.com/golang/go/wiki/Modules#gomod

> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. The replace and exclude statements, therefore, allow the main module complete control over its own build, without also being subject to complete control by dependencies. (See FAQ below for a discussion of when to use a replace directive).

We may want to add an "proxy" main in the root folder so that use doing `go get github.com/tektoncd/cli@v0.5.0` get the binary…

**Comment by chmouel** [comment]
or we can just move `cli/cmd/tkn` to  the root dir, wo/ having to "proxy" ?

**Comment by chmouel** [comment]
I have tried this https://github.com/chmouel/tektoncd-cli/commit/2070778843a10c6cbfc322327086a7e8fbfd8c30#diff-7ddfb3e035b42cd70649cc33393fe32c for fun and still the same issue :(

```
root@26e9c9390fbf:~# export GO111MODULE=on;unset GOPATH;cd;go get github.com/chmouel/tektoncd-cli@master
[...]
go/pkg/mod/github.com/chmouel/tektoncd-cli@v0.3.1-0.20191112123852-6df91da52c74/pkg/cmd/taskrun/logs.go:78:7: c.MarkZshCompPositionalArgumentCustom undefined (type *cobra.Command has no field or method MarkZshCompPositionalArgumentCustom)
```

( i have another dummy [commit](https://github.com/chmouel/tektoncd-cli/commit/6df91da52c74a1c6b50ab5a5a2d4c4de1ab78e0c) that moves from tektoncd/cli to my chmouel/tektoncd-cli to be able to do that)

I am guessing moving to /root is still not enough

What about we just tell people to `git clone url;make bin/tkn` instead?
