### ISSUE TITLE
Set Default to False for Show Logs for TaskRun and PipelineRun

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#455]
It's a bit unexpected to immediately show logs after starting a task run or a pipeline run. I realize that this was an intentional feature added for pipeline runs and task runs, but I think it's not fair to assume that users will want to immediately see logs with the CLI. 

I think the `--show-logs` flag gives users the ability to control whether they immediately want to see logs, but we should not assume they will by default. 

I wanted to open this up to discussion and see if there were any strong opinions as for why logs should be shown by default. 

# Expected Behavior

Starting a pipeline run or task run will not immediately show logs.

# Actual Behavior

Logs are shown.

**Comment by chmouel** [comment]
I am the one who was defending it but I would bow to the majority :D 

/cc @siamaksade

**Comment by danielhelfand** [comment]
I feel like false would be more natural to me, but yeah I differ to the majority as well. If there's a good way to get feedback on this from a broader group, that would help inform this as well.

**Comment by chmouel** [comment]
yeah taking from another cli like OpenShift's `oc`, you do a `oc start-build` and then `oc build-logs`, it's fair to do the same for `tkn`.

I always do a `tkn log` right after a `tkn start` so that's why I have set this up by default, but yeah if we are used to have the logs not showing then be it 👍

**Comment by vdemeester** [comment]
I think we need to also put what is going to be the main use of `tkn`. Showing the logs as soon as we created the taskrun/pipelinerun seems to be a good thing in 80% case when used interactively, and a "bad" thing in 80% when used in a script or something that is not interactive. We should make those choice depending on our main target.

I am a bit like @danielhelfand, it feels a bit weird to have the logs shown directly (implicitely) and I would prefer to be explicit about them showing ; a bit like `oc` does (thanks @chmouel :angel:).

**Comment by chmouel** [comment]
We can detect pty/interactiveness/scripting or not by the way, and automatically enable/disable if we wanted,

**Comment by vdemeester** [comment]
@chmouel I would like that :stuck_out_tongue:
