### ISSUE TITLE
Feature Request: tkn start -f

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/cli#458]
It would be awesome to have a Task definition sitting in a repo, and be able to create a TaskRun from that without needing to first create it in the cluster.

This would work roughly by parsing the Task definition then sticking it into the "taskSpec" field of the generated TaskRun, rather than using a TaskRef.

**Comment by chmouel** [comment]
/kind feature

👍

**Comment by dlorenc** [comment]
Ref: https://github.com/tektoncd/cli/pull/459

**Comment by piyush-garg** [comment]
Fixed by #459 

/close
