### ISSUE TITLE
Sort Steps by Order of Execution for tkn tr desc

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#460]
Following up on #450.

The steps shown by `tkn taskrun describe` don't appear in the order that they are to be executed. Specifically, steps not explicitly defined as part of the task definition that show up as part of a task run make it confusing as to the order of what is to be executed. 

An example of a step not explicitly defined as part of a task but appears as part of a task run is [`s2i-nodejs`](https://github.com/openshift/pipelines-catalog/blob/0157bb7c7161c55fecaa6835137d01c61a360ec8/s2i-nodejs/s2i-nodejs-task.yaml) where an `image-digest-exporter` step appears that is not part of the task definition.

# Expected Behavior

Steps appear in order they are to be executed with `tkn tr desc`.

# Actual Behavior

Steps explicitly defined appear in correct order, but steps not part of task definition appear out of order.

# Steps to Reproduce the Problem

1. Use the `s2i-nodejs` task to create a task run
2. Use what's currently in master for tkn and run `./tkn tr desc <tr_name>`
3. View the `Steps` portion of the output from `tkn tr desc`

**Comment by chmouel** [comment]
just for info, this is how i do it In a small wrapper script I use : 

https://github.com/chmouel/chmouzies/blob/master/kubernetes/tktl#L111

(beware: ninja shell/python hacks)
