### ISSUE TITLE
tkn logs segfaults if run not started

### ISSUE THREAD

**Issue by faust64** [tektoncd/cli#470]
# Expected Behavior

Some info/error/warning, notifying me the job has not started yet

# Actual Behavior

```
$ tkn pipelinerun list
NAME                              STARTED        DURATION     STATUS      
....
nextcloud-wsweet-master-1         ---            ---          ---         
...
$ tkn pipelinerun logs nextcloud-wsweet-master-1
panic: runtime error: index out of range [0] with length 0

goroutine 34 [running]:
github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).readAvailableLogs.func1(0xc000772000, 0xc000772060, 0x23cb680, 0x0, 0x0, 0xc000200720, 0xc0000e0a00)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:137 +0x3a5
created by github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).readAvailableLogs
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:126 +0x2e1
```

# Steps to Reproduce the Problem

1. pile up several pipelineruns
2. use tkn pipelinerun logs against a job that did not start

**Comment by piyush-garg** [comment]
@faust64 Can you please provide the CLI version also? `tkn version`

**Comment by danielhelfand** [comment]
My thought is we need to check if conditions are available. We need to use the [`empty func`](https://github.com/tektoncd/cli/blob/990cb81bfa1097181ab6c65e7ebfe9d190cbb199/pkg/cmd/pipelinerun/log_reader.go#L215) to check before using [index 0 for the conditions list](https://github.com/tektoncd/cli/blob/990cb81bfa1097181ab6c65e7ebfe9d190cbb199/pkg/cmd/pipelinerun/log_reader.go#L137).

**Comment by piyush-garg** [comment]
Yes, exactly. I also ended up with the same resolution. Are you raising the PR or should I ?

**Comment by danielhelfand** [comment]
/assign

I'll raise one.

**Comment by faust64** [comment]
Hi,

CLI version: 0.5.0

```
$ tkn version
Client version: 0.5.0
```
