### ISSUE TITLE
Add default values when creating new resource

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#476]
When user creates new resource on starting a pipeline, it would be useful to suggest default values for resource name and some attributes which user could use by pressing enter. For example for Git branch "master" could be default.

**Comment by chmouel** [comment]
/kind feature

big +1

**Comment by cpanato** [comment]
this is still valid? can I try this one?

**Comment by chmouel** [comment]
@cpanato It is still valid, I think the main difficulty is what are "sane" defaults ?


For branch for sure we could use main/master. But what about the others? What should be a sane value for pushing to a container registry? 

They are maybe, but we would need to identify them

**Comment by cpanato** [comment]
/remove-lifecycle rotten

there is a draft PR waiting for some feedback
