### ISSUE TITLE
Can't specify the k8s context?

### ISSUE THREAD

**Issue by tsuna** [tektoncd/cli#477]
**tkn Version:** v0.5.1

`tkn` has a `--kubeconfig` flag but it doesn't seem to have a flag to specify which k8s context to use.  I have one config file and several contexts in it, and `tkn` only seems to use the default. Am I missing something or there is no way to tell it which context to use?

**Comment by chmouel** [comment]
there is way if you use the variable KUBECONFIG but we can add a specific `--kubeconfig` flag

**Comment by tsuna** [comment]
How do you specify the context to use with the `KUBECONFIG` variable?

**Comment by vdemeester** [comment]
@chmouel there is no `--context` flag though (`kubectl` has one)

```
       --context=""
           The name of the kubeconfig context to use
```

**Comment by chmouel** [comment]
Ah I stand corrected then, I usually would just use different KUBECONFIG and use kubens to change my default context in there, but that flag is much easier,

**Comment by waveywaves** [comment]
I would like to work on this if that is alright

**Comment by waveywaves** [comment]
@hrishin says /ilovethisissue will make it assign it to me
