### ISSUE TITLE
Bash/ZSH completion across namespaces (with -n) is not working

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#482]
# Version and Operating System

**tkn Version:**

compiled from latest

**Operating System:**  

OSX's brew

# Expected Behavior

Something like this, if I was adding a `-n` it would complete on the right namespace 

(fyi that's a custom patch i made on oc completion to get it right, not available by default)

[![asciicast](https://asciinema.org/a/8uk0Xk2IR8wsd7zxIgyfDvzaw.svg)](https://asciinema.org/a/8uk0Xk2IR8wsd7zxIgyfDvzaw)

# Actual Behavior

Complete only on the current namesapce

# Steps to Reproduce the Problem

1. source <(tkn completion zsh)
2. create a task in a namespace
3. set your context in the different namespace
4. try to complete from that different namespace to the other namespace

# Additional Info

**Comment by vdemeester** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale
@chmouel is it still something to look at ?
