### ISSUE TITLE
Start doing testing against nightly

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#496]
We are currently testing only against the stable version of pipeline.

When there is breaking change in pipeline, we rush it to get it fixed like
mad(wo)men to fix the CI.

Let's do two different jobs, one against nightly and one against stable version
of pipeline.

/area testing
/kind feature

/cc @vdemeester @hrishin @sthaha @danielhelfand

**Comment by chmouel** [comment]
@afrittoli do we have a nightly release.yaml ?

**Comment by vdemeester** [comment]
@chmouel yes we do :angel: Here it is : https://storage.googleapis.com/tekton-releases-nightly/pipeline/latest/release.yaml
