### ISSUE TITLE
Include Location of Official tkn Image in README

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#497]
We should have an official image for `tkn` and publish where it is available. We should also include available tags.

Is `gcr.io/tekton-releases/dogfooding/tkn` the location of the image?

/kind documentation
/kind question

**Comment by danielhelfand** [comment]
good first issue

**Comment by chmouel** [comment]
I think we should aim to provide ours with latest stable version done at RELEASE_PROCESS, the dogfooding one can be slow to get updated (ie: https://github.com/tektoncd/plumbing/pull/141)

**Comment by vdemeester** [comment]
@danielhelfand it will be once we have it :stuck_out_tongue_closed_eyes: I think right now it got pushed manually

This would also remove the need for https://github.com/tektoncd/plumbing/blob/master/tekton/images/tkn/Dockerfile
/cc @wlynch @afrittoli 

We should have a nightly one, and one done in releases :angel:

**Comment by chmouel** [comment]
when we have our own Dockerfile, we could go fancy and create a automatic PR update on [release](https://github.com/tektoncd/cli/blob/master/tekton/release.sh) with our [github token](https://github.com/tektoncd/cli/blob/2da5e0e14ebee51a1d917cf2e731dd15d79ee65d/tekton/release-pipeline.yml#L14) in pipeline

**Comment by danielhelfand** [comment]
> when we have our own Dockerfile, we could go fancy and create a automatic PR update on [release](https://github.com/tektoncd/cli/blob/master/tekton/release.sh) with our [github token](https://github.com/tektoncd/cli/blob/2da5e0e14ebee51a1d917cf2e731dd15d79ee65d/tekton/release-pipeline.yml#L14) in our release pipeline

Yup, I like it!
