### ISSUE TITLE
Flaky Unit Tests in CI

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#499]
The unit tests shown in the image below have been known to fail quite regularly. The typical approach has been to rerun the tests if these two tests are the only two that failed. We should look into what causes the occasional failures.

![image](https://user-images.githubusercontent.com/34258252/70142867-3cc25500-1668-11ea-81b6-dbd009d8a03b.png)

# Expected Behavior

Unit tests pass as part of CI for a pull request.

# Actual Behavior

Occasional failure of the tests mentioned above.

**Comment by chmouel** [comment]
Let's give a try to : 

https://github.com/google/goexpect

instead of the netflix one,

@pradeepitm12 is going to try to move the most flaky test to it 

/assign @pradeepitm12

**Comment by chmouel** [comment]
The problem is getting worse and worse, unless someone object, I'll just `t.Skip()` those tests..
