### ISSUE TITLE
tkn task start does not respect input parameters

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/cli#511]
tkn task start <task> does not take the input parameters provided 

### Actual Behaviour
tkn task start build -i=source=app-res -p=G_TASK=task
and try to get the description of the taskrun gives `Params No params`
### Expected Behaviour
given params should be respected
tkn task start build -i=source=app-res -p=G_TASK=task
description of taskrun should give `Params G_TASK task`

**Comment by piyush-garg** [comment]
This is also the issue with `pipeline start`. This started occurring after #483 

/assign
