### ISSUE TITLE
Refactoring pipeline start and log tests.

### ISSUE THREAD

**Issue by 16yuki0702** [tektoncd/cli#520]
/area testing

This is a kind of suggestion.
pipeline start, log tests are currently using ```pkg/cmd/pipeline/logs_testutil.go ```
but these seems can be replaced common utility of ```pkg/helper/test/util.go```
I think it would be better refactoring these tests to use common utility and remove each test utils.

**Comment by 16yuki0702** [comment]
I think ```pkg/cmd/pipelineresource/resource_testUtil.go ``` also can be removed.

But maybe looking into https://github.com/tektoncd/cli/issues/499 is still be working, so do I have to wait until this will be complete??

**Comment by chmouel** [comment]
in #499 we are just going to disable the interactive tests since those are way too flakeyness at the moment in there..

**Comment by 16yuki0702** [comment]
> in #499 we are just going to disable the interactive tests since those are way too flakeyness at the moment in there..

Thanks!! I confirmed the https://github.com/tektoncd/cli/pull/616/files , I think It's very good :+1:
I'll just try to only remove the ```pkg/cmd/pipelineresource/resource_testUtil.go```
not refactoring.
