### ISSUE TITLE
Mimic kubectl with command syntax

### ISSUE THREAD

**Issue by ncskier** [tektoncd/cli#527]
# Expected Behavior
Since I use `kubectl` a lot, I'm used to typing the `kubectl [command] [TYPE] [NAME] [flags]` command syntax. So, I sometimes expect the Tekton CLI to have the same syntax.

# Actual Behavior
If I understand correctly, the Tekton CLI has a `tkn [TYPE] [command] [NAME] [flags]` syntax. I know that the Tekton CLI isn't exactly analogous to `kubectl`, so it might not suit the Tekton CLI to use the `tkn [command] [TYPE] [NAME] [flags]` syntax. However, I think it might be nice to have a consistent syntax with `kubectl`. What do you think?

**Comment by vdemeester** [comment]
So, this is something that crossed our mind initially. There is a few reasons I can think of for why we didn't go there.

- if we were to mimic `kubectl` behavior, then what would be the value of `tkn` aside from a *glorified* `kubectl` "script"
- we are more or less in the same "spirit" as `kn` for Knative. We target the Tekton APIs, the fact that it's Kubernetes behind the curtain is an implementation detail. As for `kn`, at some point, our cli could target Tekton API served by something else (a cloud implementation, …)
- we shouldn't base our command line "flow" on what people are used to in Kubernetes ; we target developers and ci/cd system owners (#invent-your-persona :stuck_out_tongue_closed_eyes:), not kubernetes administrator/user (although the could be the same person).

The `tkn` cli is still kinda *bare*, as it currently reflects the types more or less and nothing more. This doesn't mean it's gonna be the case forever. We may have a little bit more opinionated flows in the future or sub-commands that do not reflect a given type but are something the user would like to have.

/kind question

**Comment by danielhelfand** [comment]
I tend to agree with what @ncskier is saying with regard to how I actually like to type commands. Something about `tkn delete task foo` feels more natural than `tkn task delete foo`. 

I am not sure how difficult that kind of refactoring would be for the whole project, but I think we are probably best served continuing with our current strategy. Apologies for all the context switching with tools. I do think we need to do more to make sure users are not constantly going back and forth between `kubectl` and `tkn`. We should have the experience users need more perfectly captured in `tkn` itself.

**Comment by vdemeester** [comment]
> I do think we need to do more to make sure users are not constantly going back and forth between `kubectl` and `tkn`. We should have the experience users need more perfectly captured in `tkn` itself.

Yes, that is definitely the goal :angel:
