### ISSUE TITLE
Proposal: Deprecate trigger Alias for Pipeline Start and Task Start

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#531]
We currently support the alias `trigger` for `tkn pipeline start` and `tkn task start`. I think it's not used very often, and it may become confusing as the CLI starts to add in features around the triggers project.

I think a simple process would be to make an announcement as part of our next release that trigger will be deprecated and then we officially remove it in `v0.8.0`. If we would like to go further and include some kind of message in the CLI, we could work on that for `v0.7.0`. 

# Version and Operating System

**tkn Version:** master branch

**Operating System:** N/A

**Comment by chmouel** [comment]
make sense +1 from me!
