### ISSUE TITLE
Clustertask list command fails on missing namespace

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#546]
When listing the `ClusterTask` after deleting a namespace, the command fails:
```
$ tkn clustertask list
Error: namespaces "pipelines-demo" not found

$ kubectl get clustertask
NAME                      AGE
buildah                   10m
```

**Comment by piyush-garg** [comment]
clustertask is a cluster-wide resource, we need to remove the namespace check for this [here](https://github.com/tektoncd/cli/blob/master/pkg/cmd/clustertask/list.go#L53)

/kind bug
/kind good-first-issue
