### ISSUE TITLE
Cannot re-run task with --last option

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/cli#553]
# Version and Operating System

**tkn Version:**
0.6

# Expected Behavior
**tkn task start -f <manifest.yaml>**

Taskrun started: task-volume-run-npvx4
Waiting for logs to be available...
.....

When we try to re-run the same task it throws, error
**tkn task start -f <manifest.yaml> --last**

**Error:** no taskruns related to task task-volume found in namespace default

**Reason:** When we run task with tkn, it creates taskrun with embedded taskSpec not TaskRef

**Comment by vdemeester** [comment]
> **Reason:** When we run task with tkn, it creates taskrun with embedded taskSpec not TaskRef

I am not sure I follow there, I would think it just recreates a new TaskRun from the previous one, without embedding the TaskSpec (if it was not the case before).

/kind bug

**Comment by danielhelfand** [comment]
It appears as if there is some dependency on needing the task to be created in the namespace for `tkn task start --last`. The whole idea behind `tkn task start -f` is that the task can be started without creating the task beforehand. We either need a way to connect the taskrun to the task despite the fact it doesn't exist, or we need to return an error message saying `-f` does not support `--last`. 

In my opinion, it doesn't really make sense to be able to use `--last` with `-f`. If the user wants to run the task again, I think what makes sense is to simply run `tkn task start -f manifest.yaml` again. 

I think the better option would be to have an error message for this case to let users know that `--last` isn't supposed to be used with `tkn task start -f`.

**Comment by danielhelfand** [comment]
Please feel free to look at the pull request I just opened @praveen4g0. Let me know if I am missing something different that we could do to approach this.
