### ISSUE TITLE
Short-hand command for latest pipelinerun logs

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#57]
Quite often a user would want to look at the latest pipelinerun of a certain pipeline. The current flow requires two steps:
1) fnd out the name of that pipelinerun via `tkn pipeline describe` or `tkn pr ls`
2) see logs using the `tkn pr logs [pipelinerun-name]` command. 

It would be helpful to simplify that by providing a shortcut command that shows the logs for the latest pipelinerun that is started for a given pipeline:
```
tkn pipeline logs [pipeline-name]
```

There could also be flags to allow choosing pipelineruns prior to the latest

**Comment by chmouel** [comment]
+100 to this, when there is nothing else let's choose the better default!

I'd love to have a easy flow as this in the CLI  : 

https://asciinema.org/a/oOg6fcDLmskA6tVi3gTacmKAp

**Comment by hrishin** [comment]
> There could also be flags to allow choosing pipelineruns prior to the latest

Do we really need it? because it could
* redundant for pr logs command
* command appears quite long  `tkn pipleine logs pipeline_name  -pr pr_name`
* not sure about autocompletion would support to give pipelinerun names for that pipeline only

WDYT @siamaksade @vdemeester @sthaha @pradeepitm12 ?

**Comment by sthaha** [comment]
> * redundant for pr logs command

yes, it does but I don't'think we have to follow [`TOOWTDI`](https://wiki.python.org/moin/TOOWTDI) and we don't adhere to that any since there are alias `pipelineruns | pr` 

> * `tkn pipleine logs pipeline_name -pr pr_name` too long 

but is a great way to `filter` by pipeline-name of  autocompletion

> * not sure about autocompletion would support to give pipelinerun names for that pipeline only

I don't see why this isn't technically possible

**Comment by hrishin** [comment]
Let's go ahead as discussed :+1:

**Comment by piyush-garg** [comment]
I think we have resolved this and the feature is available now. Can we close this issue ?
