### ISSUE TITLE
`tkn delete` should accept multiple argument

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#572]
# Version and Operating System

# Expected Behavior

Multiple argument to `tkn delete` would be handle

# Actual Behavior

Only the first one currently

# Steps to Reproduce the Problem

1. tkn delete pipeline1 pipeline2

# Additional Info

![image](https://user-images.githubusercontent.com/98980/71895690-089fef80-3152-11ea-8c35-8b30a901f364.png)

/kind feature

**Comment by sbwsg** [comment]
ok if i pick this up?

/assign

**Comment by chmouel** [comment]
Perfect @sbwsg thanks
