### ISSUE TITLE
Have Create and Apply Not Be Tied to Specific Resources

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#574]
As of v0.6.0, create commands are structured as follows:

`tkn <resource> <action>` (e.g. `tkn pipeline create`)

When it comes to creating multiple resources in the same file definition, our current approach will not support that. The question is whether to support several different Tekton resources in the same file (e.g. a `Pipeline` and a `Task`) and whether to support this as a non resource-specific command (e.g. `tkn create`/`tkn apply`).

**Comment by chmouel** [comment]
I think this should be at the topevel the same way we create and apply are toplevels in kubectl, 

i.e: we don't say `kubectl pods create` but `kubectl create pods`

**Comment by danielhelfand** [comment]
Agreed. This would also allow us to support different kinds defined within the same file.

**Comment by danielhelfand** [comment]
The current thought is to follow a [pattern used by `ko`](https://github.com/google/ko/blob/1fcfe62a9606a2781559ed10897a4ae7141d7628/pkg/commands/delete.go) to support top level `create` and `apply` commands through `tkn` that actually invoke `kubectl` commands. 

I will put together a proposal pr around this, and we can further debate if the idea makes sense.

**Comment by danielhelfand** [comment]
Closing this issue. tkn <resource> create -f commands will be removed by version 1.0.0. The recommendation is to use kubectl for creating and updating of resources.
