### ISSUE TITLE
Code Coverage on CI doesn't seem to be running anymore

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#576]
I don't think I have seen the PR code coverage anymore,

We need to figure out why is it disabled?

(and perhaps if that doesnt' work anymore see if we can fall back to https://codecovs.io)

/cc @vdemeester

**Comment by piyush-garg** [comment]
It's working I think. Comment from last night https://github.com/tektoncd/cli/pull/577#issuecomment-571721274

**Comment by danielhelfand** [comment]
I think it doesn't show if there is no difference in coverage? For instance, this [pr](https://github.com/tektoncd/cli/pull/580) is refactoring tests so it doesn't alter coverage.

**Comment by chmouel** [comment]
Ah yes you guys are right!! 
/close
