### ISSUE TITLE
Support limiting to a specific container when running logs

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#578]
# Expected Behavior

Currently we are showing the logs from all containers, it would be nice if we can limit to loging to only a step/container for `tkn taskrun` or to a specic taskrun in `tkn pipelinerun`

# Actual Behavior

Showing everything

/kind feature

**Comment by piyush-garg** [comment]
- [ ] step flag for the logs of the specific steps in the taskrun.

For specific taskrun of a pipelinerun, we already have `--only-tasks` flag to specify the tasks for which you want the logs.

cc @chmouel

**Comment by chmouel** [comment]
do we have? 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/98980/71976589-f50a8c80-3216-11ea-81f6-b7d5e1b31275.png">

**Comment by piyush-garg** [comment]
I mean we have a flag `--only-tasks` to show the logs for only tasks mentioned in `pipelinerun logs` command, but the `--only-steps` flag to show the logs for only steps mentioned in `taskrun logs` is what needs to be added.

```
$ tkn pr logs -h
Show the logs of PipelineRun

Usage:
tkn pipelinerun logs

Examples:
  Show the logs of PipelineRun named 'foo' from namespace 'bar':

    tkn pipelinerun logs foo -n bar

Show the logs of PipelineRun named 'microservice-1' for task 'build' only from namespace 'bar':

    tkn pr logs microservice-1 -t build -n bar

Show the logs of PipelineRun named 'microservice-1' for all tasks and steps (including init steps) from namespace 'foo':

    tkn pr logs microservice-1 -a -n foo
   

Flags:
  -a, --all                  show all logs including init steps injected by tekton
  -f, --follow               stream live logs
  -h, --help                 help for logs
      --limit int            lists number of pipelineruns (default 5)
  -t, --only-tasks strings   show logs for mentioned tasks only

Global Flags:
  -c, --context string      name of the kubeconfig context to use (default: kubectl config current-context)
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)
  -C, --nocolour            disable colouring (default: false)

**Comment by chmouel** [comment]
Ah yes right! I am not so sure about the flags nomination “—only-tasks” or “—only-steps” but I let better English speaker decide :)

**Comment by vdemeester** [comment]
right, I would naively think of `--task …` and `--step …` :angel: 
/cc @danielhelfand

**Comment by piyush-garg** [comment]
To me also `--tasks` and `--steps` looks better wrt naming and understanding

**Comment by danielhelfand** [comment]
We could potentially allow multiple `--step`/`--task` flags to specify which logs you would like included from a pipelinerun or taskrun:

`tkn pipelinerun logs run --task foo --task bar`

`tkn taskrun logs run --step foo --step bar`

**Comment by chmouel** [comment]
@danielhelfand your suggestion sounds good to me!
