### ISSUE TITLE
Feature Request: Delete TaskRuns Associated with a PipelineRun 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#588]
The CLI as of `v0.6.0` supports the ability to delete a Pipeline and its associated PipelineRuns as well as the ability to delete a Task and its TaskRuns. We should also add the ability to delete TaskRuns associated with a PipelineRun as part of deleting a PipelineRun.

This was [originally thought of](https://github.com/tektoncd/cli/pull/585#discussion_r364947660) as part of #585, which refactored resource deletion for all resources.

**Comment by sbwsg** [comment]
I believe this happens automatically when deleting a PipelineRun, at least from my initial testing:

```bash
λ kubectl get pipelineruns
NAME                  SUCCEEDED   REASON    STARTTIME   COMPLETIONTIME
demo-pipeline-run-1   Unknown     Running   7s          

λ kubectl get taskruns
NAME                                            SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
demo-pipeline-run-1-build-skaffold-app-588ps    Unknown     Pending     1s          
demo-pipeline-run-1-build-skaffold-web-z8fx8    Unknown     Pending     1s          
demo-pipeline-run-1-skaffold-unit-tests-997cv   True        Succeeded   9s          1s

λ tkn pr delete demo-pipeline-run-1
Are you sure you want to delete pipelinerun "demo-pipeline-run-1" (y/n): y
PipelineRun deleted: demo-pipeline-run-1

λ kubectl get pipelineruns
No resources found in default namespace.

λ kubectl get taskruns
No resources found in default namespace.

```

**Comment by danielhelfand** [comment]
@sbwsg Gotcha! Thanks for researching this and clearing this up. Sorry for the confusion with the pull request.
