### ISSUE TITLE
Describe Subcommands for Condition, EventListener, TriggerBinding, ClusterTriggerBinding, TriggerTemplate, and ClusterTask

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#594]
The following commands do not include `describe` subcommands: Condition, EventListener, ClusterTriggerBinding, TriggerBinding, TriggerTemplate, and ClusterTask.

These commands should follow the format we use for other describe commands (e.g. [`tkn task describe`](https://github.com/tektoncd/cli/blob/master/pkg/cmd/task/describe.go)). 

Shorthand for the command should be `desc` as is consistent with other describe subcommands.

The resource to be described is passed in as an argument from the command line.

Examples:

Describe condition named condition-name: 
`tkn condition describe condition-name`

Shorthand for describe eventlistener named el-name: 
`tkn eventlistener desc el-name`

## Progress:
- [x] ClusterTask #624 
- [x] TriggerBinding #912
- [x] ClusterTriggerBinding #923 
- [x] TriggerTemplate #928 
- [x] EventListener #933 
- [x] Condition #939

**Comment by supra08** [comment]
@danielhelfand I would like to work on this issue.

**Comment by danielhelfand** [comment]
Thanks @supra08!

**Comment by danielhelfand** [comment]
Updated list for #912

**Comment by piyush-garg** [comment]
/close

All subcommands done. Closing this cc @vdemeester @danielhelfand @savitaashture
