### ISSUE TITLE
Incoherencies between `tkn pipeline ls` and `tkn task ls`

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#596]
If we do a `tkn pipeline ls` we have the start, duration and status field.

![image](https://user-images.githubusercontent.com/98980/72273485-b4ea4600-362a-11ea-9817-eba819829ad9.png)

while if we do a `tkn task ls` we only have an age : 

![image](https://user-images.githubusercontent.com/98980/72273518-c3d0f880-362a-11ea-9fe2-8b6ba81f7956.png)

It could be nice to homogenize this

**Comment by vdemeester** [comment]
This was the initial decision, to not have latest `TaskRun` execution on tasks. A `Task` can be executed in a lot of ways, in a lot of different `Pipeline` (or on its own), and it didn't really make sense to display the "latest" one, as.. there is no context to it.

**Comment by chmouel** [comment]
yes but we can show the satus?

**Comment by danielhelfand** [comment]
> This was the initial decision, to not have latest `TaskRun` execution on tasks. A `Task` can be executed in a lot of ways, in a lot of different `Pipeline` (or on its own), and it didn't really make sense to display the "latest" one, as.. there is no context to it.

Can see the thought on why this was left out. I was going to make the argument that tasks are namespaced being a factor in why this makes sense (so it would be limited in terms of what it carries out), but I could see a use where multiple pipelines use the same task in a namespace.

I think an interesting thought would be whether this applies to ClusterTasks, but It seems like there is some [momentum for ClusterPipelines](https://github.com/tektoncd/pipeline/issues/1876). Not sure where the discussion is with [referencing tasks from other namespaces](https://github.com/tektoncd/pipeline/issues/1409), but that would further complicate this.

So while on the surface this looked like a good idea, I am having some second thoughts.
