### ISSUE TITLE
Consistent Approach to Referring to Tekton Resources Through CLI

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#605]
We should have a consistent approach to how resources are referenced in `tkn`. Currently, there are several different approaches used. An example is `TaskRun`:

TaskRun:
https://github.com/tektoncd/cli/blob/84e7da62e97c560aa2740db7346f17458c0e03b0/pkg/cmd/taskrun/list.go#L36

taskrun:
https://github.com/tektoncd/cli/blob/84e7da62e97c560aa2740db7346f17458c0e03b0/pkg/cmd/taskrun/list.go#L82

Taskrun:
https://github.com/tektoncd/cli/blob/4ae08d75c5f5de7a5f99c753e38738e202d157fc/pkg/cmd/task/start.go#L239

My thought would be to capitalize the resource name (`TaskRun`) or to lowercase the resource name completely (`taskrun`). 

While I am using `TaskRun` as an example, this applies to all resources in the CLI. I have no preference on how to refer to resources, but we should be consistent throughout the CLI.

**Comment by chmouel** [comment]
Camel case names i.e: `TaskRuns` feels more natural to me!

**Comment by danielhelfand** [comment]
All prs needed to close this issue should be open. Once they are merged, this can be closed.

**Comment by danielhelfand** [comment]
Closing this since all related prs are in.
