### ISSUE TITLE
tkn pipeline describe show the Tasks runafter with bracket

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#612]
Do we need to show those brackets? I think we can do better...

![image](https://user-images.githubusercontent.com/98980/72462622-c4f05a00-37d1-11ea-8158-a159ea63eec1.png)

/kind question

**Comment by danielhelfand** [comment]
It is how it’s defined in the YAML for RunAfter. I don’t have a strong preference on it, but no harm in removing the brackets I guess.

**Comment by chmouel** [comment]
My grip is really against the empty bracket.... this doesnt look very visually appealing....

**Comment by vdemeester** [comment]
Yeah, we can remove those and have a `,` separate list :angel:
