### ISSUE TITLE
Add flag to list taskruns of a pipelinerun

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#617]
`tkn tr list` lists all taskruns but it's not helpful when one is looking to list only tasksruns that are generated by a particular pipelinerun. One has to run `tkn tr list | grep` to achieve that.

A flag like `tkn tr list -pr [pipelinerun-name]` could be helpful for this usecase

**Comment by vdemeester** [comment]
/kind feature

I feel we need a `filter` option of some sort :angel:

**Comment by chmouel** [comment]
There is a great feature for filtering in kubectl called FieldSelection, you can do fancy things like this : 

```
k  get pods --field-selector status.phase=Running
```

Which we could use for `filtering`or for this feature.

It's unfortunately a server side thing, and it's not implemented in pipeline (by knative.pkg?). I'lll raise a PR in there..
