### ISSUE TITLE
Add a way to disable permanently the colors/emojis by configuration or env variables

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#619]
For visually impaired people having colors or emojis may not be such a good idea, let provide an environment variable to make sure it's always disabled.

/kind feature

**Comment by danielhelfand** [comment]
It seems we added an environment variable in #1152 to disable color/emojis throughout `tkn`. Only thing left might be to document this somewhere/share https://no-color.org/ docs. User just needs to set environment variable `NO_COLOR` to anything.
