### ISSUE TITLE
Commands with no verb specified should default to list

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#62]
When possible, if there are no verbs specified for a command then it should default to `list` if it is relevant for that command.

For example the following should show the list of pipelines.

```
tkn pipeline
```

Currently it defaults to the `-h` and prints the help docs.

**Comment by vdemeester** [comment]
@siamaksade @chmouel @sthaha I am really not sure about this one. Usually if `tkn pipeline` returns me something (other than an error or a list of subcommand), I won't look if it has subcommands. 

@siamaksade Do you have reference on other cli tools that do things the way you describe ? (I couldn't find any I use)

**Comment by chmouel** [comment]
agreed with @vdemeester that doesn't feel right,

**Comment by sthaha** [comment]
I agree this adds potential for errors than the savings it brings (` ls` - 3 chars) . The errors could be  something like the below which may be used in a script
```
res=$(tkn p $sub_cammand)  #typo sub_command
```
and should return a error but now returns all the pipelines.

**Comment by siamaksade** [comment]
Alright. Let’s discard this one.
