### ISSUE TITLE
Update Copyright License year

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#621]
Yearly boring work to update the Copyright Year to 2020

**Comment by danielhelfand** [comment]
Do we need to define a year for copyright? I have seen it in some cases in Kubernetes where year is left out, but maybe that shouldn't be? There are definitely also 2018 references in pipeline. Wondering what the rule is for them?

**Comment by vdemeester** [comment]
I think it's when we update the files (2019-2020, then 2019-2021 in a year, …) ?

**Comment by popcor255** [comment]
resolved
/closed
