### ISSUE TITLE
Add description to task and clustertask list

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#625]
It would be useful for tasks and clustertask to have a description which could then be displayed by cli and other toolings to inform the user on what each task does

```
$ tkn task list

NAME              DESCRIPTION                        AGE          
buildah           Dockerfile builds with Buildah...  4 hours ago  
maven             Apache Maven build tool for Ja...  4 hours ago  
openshift-client  OpenShift CLI (oc)                 4 hours ago 
```

The description could possibly be an annotation on `Task` and `ClusterTask`. Or alternatively in the `TaskSpec`.

**Comment by chmouel** [comment]
I don't think this is supported yet by pipeline....

**Comment by vdemeester** [comment]
Upstream issue is tektoncd/pipeline#993
