### ISSUE TITLE
Add `--watch` features to list commands

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#63]
`tkn` should provide the same feature as `kubectl get … --watch`, aka watching changes for list.

```
-w, --watch=false: After listing/getting the requested object, watch for changes. Uninitialized objects are excluded
if no object name is provided.
```

This applies to the runtime field
- [ ] `taskrun`
- [ ] `pipelinerun`

/kind enhancement

**Comment by chmouel** [comment]
what difference would that compared to  `kubectl watch` ?
