### ISSUE TITLE
Add --all to the delete commands

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#634]
I think it could be nice to have a --all to the delete commands, the same way
kubectl has it. I can surely use kubectl for it but i guess we want it on tkn
commands..

/kind feature

**Comment by danielhelfand** [comment]
Assuming something like below deletes all tasks in namespace `ns`:

`tkn task delete --all -n ns`

**Comment by csantanapr** [comment]
I'm in desperate need 🙏 of this command `tkn taskrun delete --all -n ns` for taskruns

This will allow me to clean all the pods hundreds)   and avoid having to switch cli `kubectl delete taskrun --all -n ns`

**Comment by danielhelfand** [comment]
@csantanapr Yeah, it’s a good use case for it. We’re releasing a new version this week that will unfortunately not have this, but we can include in the next release and shouldn’t be too difficult to put in place.

**Comment by searsaw** [comment]
In the meantime, here's a small snippet I use to clean them all up.

`tkn pr ls | awk '{print $1}' | xargs -n 1 tkn pr delete -f`

**Comment by chmouel** [comment]
@searsaw fyi i think you will get the headers if you do this (i.e: NAME)

you can use the kubernetes command too, here is somethng that works : 

```
tkn pr delete -f $(tkn pr ls -o jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}")
````

**Comment by bitsofinfo** [comment]
agreed, right now you have to each one by one

**Comment by danielhelfand** [comment]
@bitsofinfo You can delete more than one at a time, but it requires you to write out each resource you would like to delete as of `v0.7.1`. For example:

```
tkn pr delete pr1 pr2 pr3 -f
```

We recently added `--all` for TaskRun deletion, and I'll be opening a pr today for deleting PipelineRuns. This will be available in master soon.
