### ISSUE TITLE
Tkn prevents us from overriding the default pod template for pipelineruns/taskruns  

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/cli#637]
# Version and Operating System

**tkn Version:**
0.6.0

**Operating System:** 
Linux

# Expected Behavior
When I override the default pod template via the config-defaults config map and run a pipeline/task through tkn, it doesn't assign an empty pod template to the run in question, by allowing Tekton to apply the default pod template declared in the config-defaults. 

# Actual Behavior
Tkn is assigning an empty pod template to pipelineruns. As Tekton doesn't merge pod templates, tkn ends up preventing us from running the pipeline/task with the custom pod template defined in the config-defaults. 
# Steps to Reproduce the Problem

1. Override the default pod template as described at: https://github.com/tektoncd/pipeline/blob/master/docs/install.md.
2. Create an arbitrary pipeline.
3. Run this pipeline through tkn pipeline start.

# Additional Info

 I've sent a question about why Tekton wasn't respecting the custom pod template in this à[thread](https://tektoncd.slack.com/archives/CK3HBG7CM/p1579950688015700) and @eddycharly pointed the aforementioned issue.

**Comment by danielhelfand** [comment]
It does not look like `tkn` accounts for pod templates with `tkn pipeline start` at this time. The code for where the pipeline run is defined begins [here](https://github.com/tektoncd/cli/blob/32ac7b89a86dfeb9dcfff5a33acdd6bbc8a1a95f/pkg/cmd/pipeline/start.go#L378). 

We need to check for if the podspec is set in the config-defaults and apply it if present.

**Comment by eddycharly** [comment]
@danielhelfand you could just set the podtemplate property to nil. Pipeline will take care of applying the default pod template.

**Comment by vdemeester** [comment]
@eddycharly we need to bump the dependency on pipeline and do a release this week, we will definitely need to take that into account :sweat_smile:

**Comment by eddycharly** [comment]
Just curious, why not put the tkn cli in the same repo as pipeline ?

**Comment by danielhelfand** [comment]
> @danielhelfand you could just set the podtemplate property to nil. Pipeline will take care of applying the default pod template.
> 
> The podtemplate property of TaskRun and PipelineRun has become a pointer since 0.10.

You can directly define the podspec on the pipelinerun definition though, so we wouldn't want to nil this out. Not everyone will define this via config defaults.

> Just curious, why not put the tkn cli in the same repo as pipeline ?

I think it makes sense to break the components of the project in to individual repos. Kubernetes/OpenShift are also breaking off their CLIs in to different repos than k8s/ocp.

**Comment by eddycharly** [comment]
> You can directly define the pod template on the pipelinerun definition though, so we wouldn't want to nil this out. Not everyone will define this via config defaults.

Sure, i don't know how to specify a pod template with `tkn pipeline start` though.

Anyway, no need to explicitely set it to `nil`, it is either not specified and therefore is `nil` by nature, or it is specified and it will be part of the `PipelineRun` spec. In both cases, pipeline will take care of applying the default pod template or the one supplied.

Just my 2 cents, the less logic in the cli the better imho.

**Comment by vdemeester** [comment]
@eddycharly yeah I think that will work that way. The main problem with 0.6.0 (and master as of today) is that we depend on 0.9.2, which doesn't have the pointer, hence always sent a `PodTemplate` struct. The bump should fix it :angel:

**Comment by danielhelfand** [comment]
@eddycharly 

> Anyway, no need to explicitely set it to `nil`, it is either not specified and therefore is `nil` by nature, or it is specified and it will be part of the `PipelineRun` spec. In both cases, pipeline will take care of applying the default pod template or the one supplied.

Ah, I follow what you're saying. Thank you for clarifying. Agree that makes sense.

We may want a way to specify the pod template more explicitly via `tkn` as a separate feature.

**Comment by chmouel** [comment]
Let's prepare an update to the dep after 0.10.1 being release?

**Comment by piyush-garg** [comment]
@alan-ghelardi @eddycharly We have bumped the pipeline dep to 0.10.1 in #658 I checked this and the issue is not anymore happening for me on the latest master.

Can you confirm once with the latest master? I am closing the issue now. Feel free to open it if this is still happening. Thanks

Fix with pipeline dep bump in #658 

/close
