### ISSUE TITLE
Start pipeline from last should use the same generateName

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#639]
When starting a pipeline using the last pipelinerun configurations, the `generateName` attribute should be copied over so that the pipelinerun names are consistent.:

For example the following pipelineruns are all for the same pipeline but using the `tkn p start --last` for the last one creates an inconsistent name since it resets the `generateName` based on the pipeline name instead of the last pipelinerun:
```
$ tkn pr list

NAME                    STARTED          DURATION    STATUS
maven-build-run-ftdvj   10 minutes ago   8 minutes   Succeeded
petclinic-run-pnlsl     18 minutes ago   8 minutes   Succeeded
petclinic-run-fsdgl     25 minutes ago   8 minutes   Succeeded
petclinic-run-lhie      28 minutes ago   8 minutes   Succeeded
```

**Comment by piyush-garg** [comment]
@16yuki0702 Can you try commenting `/assign`
