### ISSUE TITLE
Add a `check` command

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/cli#649]
# Version and Operating System

All supported versions and operating systems.

# Expected Behavior

`tkn` provides a `check` subcommand that will look at your currently configured cluster and ensure the following:

1. k8s is reachable
2. the k8s version is compatible
3. tekton's controller and webhook is up and running
4. any configured sibling projects (e.g. triggers) are up and running
4. (Maybe?) run a very simple dummy pipeline as a smoke test

A failure at any step could result in some clear notice being written to the screen to tell the user which 

This feature was suggested by @bobcatfish after working with LinkedD's check command: https://linkerd.io/2/reference/cli/check/

**Comment by chmouel** [comment]
I like it !! 

thanks to @waveywaves I think we have the version on the server now and that should not be difficult to implement.

The thing I think we should probably think about  : 

- Define and formalize compatibility i.e: (current-2)
- if controller and webhook is running, do we care about multiple tekton versions? (I guess not cause that's not really supported?)
- We need emojis on each check test output 😋
