### ISSUE TITLE
Move Chocolatey Package to More Public Area

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#652]
Currently the Chocolatey package is located at https://github.com/danielhelfand/chocolatey-tektoncd-cli

At some point, it would make sense to move it to a more public location. It could either have its own repo like the [homebrew repo](https://github.com/tektoncd/homebrew-tools), or we could come up with a more central location for all the Tekton packages.

**Comment by chmouel** [comment]
make me think that we should depreacte our homebrew repo at some point
since homebrew-core does a pretty decent job to update our formulas quite
quickly..

**Comment by nikhil-thomas** [comment]
/remove-lifecycle rotten
this issue is still valid

**Comment by danielhelfand** [comment]
I can pr the [repo](https://github.com/danielhelfand/chocolatey-tektoncd-cli) for the package to `tkn` repo. I can also figure out permissions through Chocolatey to add maintainers in case anyone is interested in maintaining the package. But also happy to keep it up to date.
