### ISSUE TITLE
`tkn pr logs` doesn't support --last

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#664]
`tkn pipeline logs` does have a --last which I find quite handy but not for pr
logs (and probably others)

/kind feature
/assign

**Comment by 16yuki0702** [comment]
This issue maybe same 
https://github.com/tektoncd/cli/issues/312

(so can closing two issues at same time!!)

**Comment by chmouel** [comment]
thanks @16yuki0702 🙇 , will pick the `tr` issue when i get the one  about `pr` merged!
