### ISSUE TITLE
Listing TaskRuns doesn't supports `name` output

### ISSUE THREAD

**Issue by searsaw** [tektoncd/cli#675]
# Version and Operating System

**tkn Version:**

```
$ tkn version
Client version: 0.7.0
```

**Operating System:** 

```
$ uname -srmpio
Darwin 19.3.0 x86_64 i386 MacBookPro15,1 Darwin
```

# Expected Behavior

When running `tkn tr ls -o name`, I expected all the TaskRuns to be outputted with just their name.

# Actual Behavior

I got the error:

```
Error: list types are not supported by name printing: *v1alpha1.TaskRunList
```

# Steps to Reproduce the Problem

1. Run a TaskRun
2. Run the command `tkn tr ls -o name`
3. View the error and cry

**Comment by danielhelfand** [comment]
/kind bug

Should follow same pattern for `tkn pr ls -o name` in #661
