### ISSUE TITLE
TektonCD CLI official container image

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#680]
We don't have our own as from the cli project own, plumbing is building this for us:

 https://github.com/tektoncd/plumbing/blob/master/tekton/images/tkn/Dockerfile

We currently use this image on the `tkn` catalog task :

https://gcr.io/tekton-releases/dogfooding/tkn

should we start owning our images to be released at release time? with some proper tags and such that we can integrate into our release_process[1]

cc @vdemeester @afrittoli 

[1] Although part of the release process document is to update the Dockerfile to latest released version.

**Comment by vdemeester** [comment]
+:100:, we should have the Dockerfile in there, and have nightly and releases task building and publishing this image from here :angel:

**Comment by piyush-garg** [comment]
@vdemeester I think we have done this, can i close this
