### ISSUE TITLE
Objects filtering

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#684]
We have some prior discussion about filtering in this issue : 

https://github.com/tektoncd/cli/issues/617

or this PR:

https://github.com/tektoncd/cli/pull/608

The commands that needs to list match multiple objects (object as Pipeline, Task, etc...) are : 

`list`, `delete`

There is a great feature implemented in kubectl called `FieldSelection` where you can do fancy things like this on the yaml :  

```
k  get pods --field-selector status.phase=Running
```

Since it's exposed in client-go i have started added it but realised only after that It is unfortunately a server side thing that doesnt seem to be implemented for tekton and could not make it work with kubectl.

And more and more I experimented with it more it was limited since some stuff are not possible (like or and etc...)

so i guess we are down to implement our own :(

/kind feature
/kind question

**Comment by waveywaves** [comment]
This would be very useful to have.

**Comment by SM43** [comment]
Tracker for --field-selector in different list commands

- [ ] TaskRun
- [ ] PipelineRun
- [ ] Task
- [ ] Pipeline
- [ ] PipelineResource
- [ ] ClusterTask
- [ ] TriggerBinding
- [ ] TriggerTemplate
- [ ] ClusterTriggerBinding
- [ ] EventListener
- [ ] Condition
