### ISSUE TITLE
Add sub-command to manage secrets

### ISSUE THREAD

**Issue by cuonglm** [tektoncd/cli#690]
# Version and Operating System

**tkn Version:**
Client version: 0.6.0

**Operating System:** 
Darwin Cuongs-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

# Expected Behavior

Managing secrets via a sub-command, the same as `drone secret`.

# Actual Behavior

No available sub-command to manage secrets.

# Steps to Reproduce the Problem

# Additional Info

**Comment by ImJasonH** [comment]
What is your ideal UX for this surface? `tkn secrets create <secret> ...`? What would this surface do that `kubectl` doesn't today?

**Comment by danielhelfand** [comment]
@cuonglm I am not familiar with `drone secret`. Would you mind explaining key features of it that you find useful?

I do agree that it would be great to add something for managing secrets, but my thought would be that it would need to be something that `kubectl` does not offer with regard to working with Tekton. Similar thoughts to @ImJasonH  on this.

**Comment by chmouel** [comment]
Agreed in general that we should not reimplement kubectl.

But perhaps whenever we are going to have an interactive "tkn pipeline
create" we could help the user creating a ServiceAccount with secrets
attached to it for ssh/git or others....

That's probably should be discussed on the issue whenever we start the work
on an interactive tkn "pipeline/tr create"

**Comment by cuonglm** [comment]
> What is your ideal UX for this surface? `tkn secrets create <secret> ...`? What would this surface do that `kubectl` doesn't today?

From developer point of view, it will be easier if I can manage everything from tekton side. Example in my code base, I use this function to query pipeline run of given pipeline:

```
func getPipelineRunName(p cli.Params, pipelineName string) (string, error) {
        lOpts := metav1.ListOptions{
                LabelSelector: fmt.Sprintf("tekton.dev/pipeline=%s", pipelineName),
        }

        prs, err := prhelper.GetAllPipelineRuns(p, lOpts, 1)
        if err != nil {
                return "", err
        }

        if len(prs) == 0 {
                return "", fmt.Errorf("No pipeline run found")
        }

        return strings.Fields(prs[0])[0], nil

}
```

For now, if I want to create a secret and attach it to a service account, I have to create a kubernetes client.

**Comment by cuonglm** [comment]
> @cuonglm I am not familiar with `drone secret`. Would you mind explaining key features of it that you find useful?
> 
> I do agree that it would be great to add something for managing secrets, but my thought would be that it would need to be something that `kubectl` does not offer with regard to working with Tekton. Similar thoughts to @ImJasonH on this.

`drone secret` allow you to create/remove/update/list/get details secrets.

**Comment by ImJasonH** [comment]
> For now, if I want to create a secret and attach it to a service account, I have to create a kubernetes client.

I'm not sure I understand exactly what you're asking for, but we shouldn't replicate a K8s API to avoid users having to create a second client. I'm also not sure that's related to the CLI?

Today, `kubectl` also allows you to manage secrets, is there something specifically it's missing for your use case?

**Comment by patcito** [comment]
> Today, `kubectl` also allows you to manage secrets, is there something specifically it's missing for your use case?

We have a multi-tenant project where each git repo has its own secrets and we don't want one git repo to have access to the others secrets. We either need several SAs or do some juggling with just one SA.

It's hard for developer to manage it, because we have to re-construct the yaml k8s file everytime you want create/update/remove secrets. To answer your question, it's not impossible to do so using kubectl but it's very inconvenient and could be prone to bugs.

If we had the interface to manage secret by tekton itself, one SA for all repo or one SA per repo wouldn't be an issue as tekton would take care of it for us.
