### ISSUE TITLE
Timeout Option for tkn pipeline start

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#706]
Similar to `tkn task start --timeout`, which lets a user define a TaskRun timeout in seconds, a Timeout option should exist for `tkn pipeline start`. 

Timeout can be defined on the PipelineRunSpec in the exact same way as how it is defined on the [TaskRunSpec](https://github.com/tektoncd/cli/blob/728fd3c4ae9d45014dce18f32303499f1d3005c2/pkg/cmd/task/start.go#L197). The unit of time used for TaskRun timeout is seconds and can be used here as well. 

The [default value](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#syntax) of 1 hour for timeout for TaskRuns also applies to PipelineRuns as well.

**Comment by danielhelfand** [comment]
To follow up on this, I am actually thinking it would make more sense to have Timeout be a string so that a user could enter a duration in the format `hour minute second` (e.g., `1h30m2s`). 

This could then be parsed using `time.ParseDuration`, which would take the string and convert it to a duration and return an error in the event the user enters an invalid duration format.

So basically, it would be 

```golang
timeoutDuration, err := time.ParseDuration(opt.Timeout)
if err != nil {
    return err
}

...

tr.Spec.Timeout = &metav1.Duration{Duration: timeoutDuration}
```

Think it makes sense too for `tkn task start` since this is the format that is used to define a Timeout on a [PipelineRun](https://github.com/tektoncd/pipeline/blob/f1bfda69a04ae3bb159b9c8669136eab2b78f3b5/examples/pipelineruns/no-ci/pipeline-timeout.yaml#L26)/TaskRun via a yaml definition.

**Comment by pradeepitm12** [comment]
The last point is really appreciated, we must maintain consistency among the commands.
