### ISSUE TITLE
Pipelines beta support v1beta1

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#731]
[`tektoncd/pipeline`](https://github.com/tektoncd/pipeline) APIs will soon be bumped to `v1beta1`. This issue is to track work to do in the cli to support that.

See https://github.com/tektoncd/pipeline/pull/2035

**Comment by vdemeester** [comment]
For what is worth, https://github.com/tektoncd/dashboard/compare/master...vdemeester:bump-v1beta1 shows more or less the dependency "version/branches" that can be used to test against tektoncd/pipeline#2035

**Comment by vdemeester** [comment]
https://github.com/tektoncd/triggers/compare/master...vdemeester:v1beta1-bump is the "temporary" bump for triggers (it does not fix the webhook but it's ok enough for cli dep)
https://github.com/tektoncd/cli/compare/master...vdemeester:v1beta1-bump for bumping the deps on the cli.. from there, we can decide how we support both

We can use `Discovery().ServiceGroups` to detect available version and act upon it. From there, we should be able to tell each command what client/struct to use. The real trick is, how to have, *potentially* two different implementation (v1alpha1 and v1beta1) with the least amount of duplication (while still being readable)…

We could also go the route of not supporting v1alpha1 starting from the next release (aka `0.9.0`), but the same question will rise from v1beta1 to v1. Is investing time in this multi api version support worth now or later ?

/cc @chmouel @piyush-garg @hrishin @danielhelfand

**Comment by piyush-garg** [comment]
/close

All the tasks have been bumped. We will file issues separately if found anything. :tada:
