### ISSUE TITLE
Docs: confusing description of --param flag

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#733]
# Version and Operating System

**tkn Version:**

0.7.1

**Operating System:** 

all

# Expected Behavior

`-h` provides clear description of flags

# Actual Behavior

`-p` or `--param` contains `pass the param as key=value or key=value1,value2`. The later part is confusing... IMHO one param cannot have two values and one taskrun or pipelinerun cannot have two params with the same name so I'm not sure how to use it

# Steps to Reproduce the Problem

1. `tkn clustertask start -h`
2. `tkn task start -h`
3. tkn pipeline start -h

# Additional Info

**Comment by vdemeester** [comment]
/kind documentation

> IMHO one param cannot have two values and one taskrun or pipelinerun cannot have two params with the same name so I'm not sure how to use it

Actually, if there is more than 2 values passed in `-p`, this means we are using an `array` parameter (hence multiple values)

**Comment by ppitonak** [comment]
@vdemeester that makes sense, can we reword it?

**Comment by piyush-garg** [comment]
@ppitonak Params are of two types string and array. So they are an example for both use case

1. For string type, pass param as `key=value`
2. For array type, pass param as `key=value1,value2,value3...`
