### ISSUE TITLE
UX: don't ask the user to input value for params with a default value

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#736]
# Version and Operating System

**tkn Version:**

0.7.1

**Operating System:** 

All

# Expected Behavior

When I start a pipeline and I don't specify all params, use default values.

# Actual Behavior

* It asks me for parameter value and shows me the default value.
* It is not possible to create a pipeline in non-interactive way although `tkn` has all data it needs.

# Steps to Reproduce the Problem

1. create everything but pipeline run from https://github.com/tektoncd/pipeline/blob/4b6a3901ecf753ee56ab9b67fe8296134bdbd426/examples/pipelineruns/conditional-pipelinerun.yaml
2. `tkn p start conditional-pipeline --showlog -s default -r source-repo=pipeline-git`

result: 
```
? Value for param `path` of type `string`? (Default is `README.md`) (README.md)
```

# Additional Info

**Comment by piyush-garg** [comment]
You can just press enter and it will take the default value.

But it is nice use-case to run without interactiveness and we already have an issue for that in #571

**Comment by ckadner** [comment]
Not prompting for parameters that have default values would also help when trying to start a pipeline in a script (#820)

**Comment by ppitonak** [comment]
/remove-lifecycle stale

`tkn task start` and `tkn pipeline start` have parameter `--use-param-defaults` but it's missing in `tkn clustertask start`
