### ISSUE TITLE
tkn condition create doesn't exist

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#737]
# Version and Operating System

**tkn Version:**

0.7.1

**Operating System:** 

All

# Expected Behavior

I can create a condition from yaml file using `tkn`

# Actual Behavior

I need to use either `kubectl` or `oc`

# Steps to Reproduce the Problem

1. `tkn condition`

# Additional Info

**Comment by danielhelfand** [comment]
In all honesty, I am wondering if it makes more sense for `tkn` to not support create commands at all and to deprecate the existing commands. I think most people are using `kubectl` for creation, and I can't see a reason for adding/supporting all these commands since what we're looking for already exists via `kubectl`.

**Comment by ppitonak** [comment]
@danielhelfand what about `tkn res create` that can work in both interactive and non-interactive mode?

**Comment by danielhelfand** [comment]
@ppitonak My personal thought is that interactive creation for tkn resource should remain, but that the -f option should be removed until there is a clearer strategy around non-interactive creation. 

I think the goal has always been to eventually have more interactive creation for all resources tkn supports. 

There were discussions at one point around wrapping create and apply commands from kubectl into tkn to allow users to run something like tkn create -f file.yaml, but there was some pushback on whether that approach made sense.

**Comment by danielhelfand** [comment]
`tkn` will not support creation commands moving forward. See #816 for more information.
