### ISSUE TITLE
UX: unify the meaning of the -f flag

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#739]
# Version and Operating System

**tkn Version:**

0.7.1

**Operating System:** 

All

# Expected Behavior

The long form of `-f` flag should be the same for all commands.

# Actual Behavior

* In `tkn t create`, `tkn p create` and `tkn res create`, the flag `-f` is equal to `--from` flag but 
* in `tkn t start` it is equal to `--filename`
* in `oc create`, `oc apply`, `kubectl create` and `kubectl apply` it means `--filename`

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by danielhelfand** [comment]
Please see comment [here](https://github.com/tektoncd/cli/issues/737#issuecomment-587048475). We have had a lot of discussion on the value of creation commands for `tkn` and the create commands with `--from` were added at a time when this seemed like a worthwhile approach. 

This issue makes sense in the event these commands are kept, but I think it's still up in the air as to whether they will be kept moving forward.

**Comment by supra08** [comment]
@danielhelfand I would like to work on this.

**Comment by danielhelfand** [comment]
@supra08 Thank you for your interest in this. I am personally leaning toward removing all `tkn create -f` commands and will be proposing removing the commands by `v1.0.0` at the CLI's next working group to see if there are strong objections to this. So I am going to recommend not picking up this issue.

I think our preference is that `kubectl create/apply` be the preferred create and update methods moving forward. The problem with supporting a `create -f` approach with `tkn`'s current command structure is that it doesn't allow the user to create several resources in one file as is a pretty common use case with `kubectl`. 

I think the better use case for `tkn` is to support interactive creation approaches and other approaches that `kubectl` does not offer. Please feel free to say if you feel differently about this issue/why the commands should be kept.

**Comment by chmouel** [comment]
Completely agree with you @danielhelfand

**Comment by supra08** [comment]
I too agree with you @danielhelfand . `kubectl` provides a robust approach and implementing approaches in `tekton` where `kubectl` lacks is a good option. 
I would pick up another issue.

**Comment by vdemeester** [comment]
Discussed during the Working Group call, we all agree on @danielhelfand's comment, so let's move forward with deprecating and removing the `create` sub-command
