### ISSUE TITLE
Add option to sort pipelines/taskruns etc oldest to newest

### ISSUE THREAD

**Issue by tomgeorge** [tektoncd/cli#742]
# Version and Operating System

**tkn Version:** 0.5.0

**Operating System:**  Fedora 31

# Expected Behavior

Something like `tkn tr list --reverse`?

# Actual Behavior

`tkn tr list` shows all taskruns oldest to newest.  As the list of taskruns grows bigger than the size of a screen, you have to do a lot of scrolling or pipe the output to `tac` to quickly see the latest taskrun, for example.  It would be nice to see the output oldest -> newest.

Edit: flip expected/actual behavior

**Comment by chmouel** [comment]
#579  would make things much easier for this too....

and I think `--reverse` would be nice to have an option..
