### ISSUE TITLE
Provide List and delete command for ClusterTriggerBinding

### ISSUE THREAD

**Issue by sudhirverma** [tektoncd/cli#752]
Issue: https://github.com/redhat-developer/vscode-tekton/issues/147

Like we have a command list and delete for `TriggerTemplate`,  `TriggerBinding`, `EventListener`.

A similar command should be provided for `ClusterTriggerBinding` to get the list and delete it.

**Comment by piyush-garg** [comment]
@sudhirverma ClusterTriggerBinding are not yet in any released version, they will be available with Triggers 0.3 release, we will add these commands after next bump. Thanks
