### ISSUE TITLE
Provide tkn command to get the condition for particular taskrun.

### ISSUE THREAD

**Issue by sudhirverma** [tektoncd/cli#763]
Issue: https://github.com/redhat-developer/vscode-tekton/issues/149

It would be good to have a command to get the list of condition names for the particular taskrun.

```
for e.g:
    tkn condition list --taskrun taskRunName

it should give me all the condition name which are associated with taskRunName. 
``` 
cc:
@siamaksade @evidolob

**Comment by piyush-garg** [comment]
A condition is executed in different taskrun when a pipelinerun is created. So we can provide the task in which condition is executed.

**Comment by piyush-garg** [comment]
@sudhirverma I am closing this issue. Feel free to reopen if required
