### ISSUE TITLE
Improve e2e Testing Coverage for CLI

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#769]
- Get #505 merged to convert e2e testing to Go 
- We should do an assessment of what scenarios we have covered for e2e testing and figure out where additional testing is needed

/kind feature

**Comment by danielhelfand** [comment]
Closing for now as #505 has been merged, we have added e2e testing capabilities for both pipelines/triggers, and have begun asking for e2e tests are part of adding new features/addressing bugs. 

Our goal moving forward should be to maintain/improve tests and continue building out coverage.
