### ISSUE TITLE
Make tkn easier to automate: add run name output, add status check

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/cli#771]
# Version and Operating System

**tkn Version:**
0.8.0

# Expected Behavior

I want to automate task/pipeline runs with tkn.
So i want to be able to do smth like
```bash
run_name=$(tkn p start -o name pipeline_name)
tkn pr logs -f $run_name
exit $(tkn pr status $run_name)
```

or shorter
```bash
tkn p start --showlog --watch pipeline_name
```

So it would be nice to add:
- option "only output a name of new created run" to run command
- status command to find out how run ended
- optionally: add "watch and exit with run status" option to run command

I know that i now can get all data from pipeline run body, but name/status fields seem to be standard enough to deserve separate call in command line.

**Comment by vdemeester** [comment]
(I guess `tkn version` is 0.8.0 though, and the pipeline instance is 0.10.x)

/kind feature

**Comment by dbazhal** [comment]
oh, soz, it really is 0.8.0 :D

**Comment by chmouel** [comment]
Even tho that doesnt address fully your use case there is the `--last` option as well..

**Comment by chmouel** [comment]
/lifecycle frozen

would be useful indeed,

**Comment by dbazhal** [comment]
is issue bumping legal? i'd like to bump :)

**Comment by chmouel** [comment]
Yeah i think there was a PR floating around about it, we need to check how to revive this.

**Comment by mgreau** [comment]
+1 on this feature.

Today we are using the following script
```
tkn pr describe $run_name -o json | jq -c '.status.conditions[] | select(.type | contains("Succeeded")?) | .status'
```

> Yeah i think there was a PR floating around about it, we need to check how to revive this.

@chmouel are you referring to this PR https://github.com/tektoncd/cli/pull/1433 (but for the name, not the status)?

**Comment by chmouel** [comment]
@mgreau correct! I'd love to have this feature too,
