### ISSUE TITLE
tkn taskrun logs not showing logs for cancelled taskruns

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#777]
# Version and Operating System

**tkn Version:**
v0.8.0

**tekton pipelines Version:**
0.10.7
**Operating System:** 
Linux

# Expected Behavior
When as taskrun is cancelled `tkn taskrun log` should show the logs for the cancelled taskrun

# Actual Behavior
Getting the below error message
`$ tkn taskrun logs check-shell-script-run-pdqzk -f

Error: task check-shell-script failed: pods "check-shell-script-run-pdqzk-pod-lhtpf" not found. Run tkn tr desc check-shell-script-run-pdqzk for more details.`

# Steps to Reproduce the Problem

1. Create a simple task and start the task 
2. run `tkn taskrun logs -f` to see the logs 
3. make sure that the taskrun starts displaying logs
4. Once the taskrun displays the logs, cancel the taskrun using command `tkn taskrun cancel`
5. Try to get the logs for the canceled taskrun by running the command `tkn taskrun logs`

# Additional Info

**Comment by 16yuki0702** [comment]
Maybe canceld pod is deleted, so logs can't be got.
(error pod is remain)

why this happend, I wanna look into it more detail.

**Comment by vdemeester** [comment]
@16yuki0702 yeah, I think the way `tektoncd/pipeline` works for cancelling is that it straight destroy the `Pod`.. That might be something we want to re-design :thinking: 

/kind feature

**Comment by 16yuki0702** [comment]
> @16yuki0702 yeah, I think the way tektoncd/pipeline works for cancelling is that it straight destroy the Pod.. That might be something we want to re-design 🤔

Yes, I found the code it delete imediately the pod. https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/taskrun/cancel.go#L49

I don't know why only canceling pod is deleted currently... 🤔
