### ISSUE TITLE
Change ClusterTask Timeout from Int to String and Remove -t Shorthand

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#784]
Similar to #779, `tkn clustertask start --timeout` should be changed to a string duration format (i.e. `1h30m2s`). Currently it is an [integer](https://github.com/tektoncd/cli/blob/b5d1f0c796344d92b6a63f206ca7aa93536d4f7a/pkg/cmd/clustertask/start.go#L54) that is used to [specify a timeout in seconds](https://github.com/tektoncd/cli/blob/b5d1f0c796344d92b6a63f206ca7aa93536d4f7a/pkg/cmd/clustertask/start.go#L133).

Similarly, the `-t` shorthand should be removed to keep consistency across all timeout commands.

Unfortunately, this was missed in our previous round of deprecation/behavior change notices around timeout, so this change cannot take place until `v1.0.0`. We should log a warning message to users about this change in version `v0.9.0`. It can be the exact same format as what was used in #753.

### v0.9.0 Changes

Log warning message to user whenever `--timeout` is used with `tkn ct start`:

```
WARNING: The --timeout flag will no longer be specified in seconds in v1.0.0. Learn more here: https://github.com/tektoncd/cli/issues/784
WARNING: The -t shortand for --timeout will no longer be available in v1.0.0.
```

### v1.0.0 Changes

The overall goal here will be to specify a Timeout via `tkn` as follows:

```
tkn clustertask start ctName --timeout 30m2s
```

**Comment by danielhelfand** [comment]
@kadern0, I think you have to assign yourself to the issue.

**Comment by kadern0** [comment]
Done!

O mér., 11 de mar. de 2020 ás 13:42, Daniel Helfand (<
notifications@github.com>) escribiu:

**Comment by vdemeester** [comment]
/assign @kadern0 

(this works as soon as you commented once, I think)
