### ISSUE TITLE
Support --all-namespaces flag for list commands

### ISSUE THREAD

**Issue by pradeepitm12** [tektoncd/cli#785]
Cli should support `--all-namespaces` for all the `list` subcommands.

Currently, cli `list` subcommands take flag `-n` namespace as an input, which lists the given resource of a given namespace
  `tkn foo list -n bar`

Support to `all-namespaces` flag will help the user to list a particular resource in all the namespaces.
  `tkn task list --all-namespaces`

Adding to this, if `all-namespaces` flag is enabled then cli should show an extra column which tells the namespace too.

**Comment by waveywaves** [comment]
- [x] TaskRun https://github.com/tektoncd/cli/pull/791
- [x] PipelineRun https://github.com/tektoncd/cli/pull/791
- [ ] Task
- [ ] Pipeline
- [ ] PipelineResource
- [ ] TriggerBinding
- [ ] TriggerTemplate
- [ ] EventListener
- [ ] Condition

**Comment by danielhelfand** [comment]
This was accidentally closed via #791 but should remain open until other resources also support this flag.

**Comment by waveywaves** [comment]
https://github.com/tektoncd/cli/pull/840 opened to which covers the requirement for tasks and pipelines

**Comment by pratikjagrut** [comment]
Opened PR #1234 to add --all--namespaces flag in triggerbinding list command.

**Comment by pratikjagrut** [comment]
* [x]  TaskRun #791
* [x]  PipelineRun #791
* [x]  Task #840
* [x]  Pipeline #840
* [x]  PipelineResource #971
* [x]  TriggerBinding #1234 
* [x]  TriggerTemplate #1235 
* [x]  EventListener #1236 
* [ ]  Condition

**Comment by danielhelfand** [comment]
Closing this cause of #1241
