### ISSUE TITLE
 Add interactive workspace support when starting a pipeline or task

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#786]
If there is a workspace in the Pipeline or Task, ask for the type and then auto-complete based on the type (list configmap, or secret, or PVC).

/kind feature

**Comment by ckadner** [comment]
@vdemeester -- is this already being worked on? I see this in the `0.9.0` milestone. Is it possible to get an early preview from the master branch?

**Comment by ppitonak** [comment]
@ckadner you can follow https://github.com/tektoncd/cli/pull/826

**Comment by vdemeester** [comment]
Should be closed by #869
/close
