### ISSUE TITLE
Hiding section with empty results

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#790]
We are currently showing sections that doesn't have object with a message that looks like this :

```
No resources
```

For example for input resources we have :

```
No input resources
```

Should we perhaps hide them?

/kind question

**Comment by danielhelfand** [comment]
I can get behind the less is more approach of this. To clarify, this is specifically for `describe` commands, correct?

So instead of the following for a `TaskRun` describe:

```
Name:        echo-task-run-5clpq
Namespace:   lab-tekton-fundamentals-w01-s001
Task Ref:    echo-task

🌡️  Status

STARTED          DURATION     STATUS
28 minutes ago   10 seconds   Succeeded

📨 Input Resources

No resources

📡 Output Resources

No resources

⚓ Params

No params

🦶 Steps

 NAME            STATUS
 ∙ echo-first    Completed
 ∙ echo-second   Completed

🚗 Sidecars

No sidecars
```

The change here would be:

```
Name:        echo-task-run-5clpq
Namespace:   lab-tekton-fundamentals-w01-s001
Task Ref:    echo-task

🌡️  Status

STARTED          DURATION     STATUS
28 minutes ago   10 seconds   Succeeded

🦶 Steps

 NAME            STATUS
 ∙ echo-first    Completed
 ∙ echo-second   Completed
```

**Comment by danielhelfand** [comment]
Discussed in working group on 5/12. We'll move forward with this approach and this issue can be picked up. Ideally, this would all be added in the same release for all describe commands.

**Comment by vinamra28** [comment]
I guess this can still be done
/reopen
/remove-lifecycle rotten
