### ISSUE TITLE
Cancelling a completed pipelinerun is showing output as Pipelinerun cancelled

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#794]
# Version and Operating System

**tkn Version:**
v0.8.0

**tekton pipelines Version:**
0.10.8

**Operating System:** 
Linux

# Expected Behavior
Output should be something like "**pipelinerun already completed, cannot cancel now**"

# Actual Behavior
Output shows **"Pipelinerun cancelled"**

# Steps to Reproduce the Problem

1. Create a pipeline and start the pipelinerun
2. Wait for pipeline run to get completed
3. Once the pipeline run gets completed, try to cancel the pipelinerun using the command `tkn pipelinerun cancel`

# Additional Info
Same issue is observed with cancelling completed taskrun
Below are the command logs

```
[varadhya@localhost testing]$ tkn pr ls
NAME                      STARTED        DURATION   STATUS               
pipeline-test-run-pgczq   1 minute ago   1 minute   Succeeded   
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pr cancel pipeline-test-run-pgczq
Pipelinerun cancelled: pipeline-test-run-pgczq
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pr ls
NAME                      STARTED         DURATION   STATUS               
pipeline-test-run-pgczq   2 minutes ago   1 minute   Succeeded   
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$

**Comment by danielhelfand** [comment]
/kind bug

I have verified this. We do have a check in [pipelinerun cancel](https://github.com/tektoncd/cli/blob/ef6182293737960272c61febd1fe6b2c78ee99f9/pkg/cmd/pipelinerun/cancel.go#L81) for this, but we'll need to look into why this is no longer being caught in v0.8.0.

**Comment by danielhelfand** [comment]
/assign

This appears to be related to adding colored statuses. Because the if statement hasn't added color to the conditions it's checking for, it's not able to correctly apply the error.
