### ISSUE TITLE
Change Cancelled(PipelineRunCancelled) and Cancelled(TaskRunCancelled) to Just Cancelled

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#798]
When a TaskRun or PipelineRun is cancelled, `tkn` shows the following status for the TaskRun or PipelineRun:

```
NAME                 STARTED       DURATION     STATUS                                     
pipeline-run-fbhtd   2 hours ago   9 seconds    Cancelled(PipelineRunCancelled)
```

Is there any particular reason for adding `(PipelineRunCancelled)` or `(TaskRunCancelled)`? My thought is it should be apparent based on the command being used (i.e. `pipelinerun` or `taskrun`) what the resource in question is. Would it make more sense to simply show `Cancelled` since this is what [pipelines itself](https://github.com/tektoncd/pipeline/blob/ea8ddd8c1eff23b291596b6ea2bb3f658d96d140/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L48) has as its reason for cancelling?

I think not having the added `TaskRunCancelled`/`PipelineRunCancelled` for the CLI is less verbose and still communicates the same thing. This would also allow us to use `resources.ReasonCancelled` in case this ever changes for pipeline instead of relying on strings such as in #795 [here](https://github.com/tektoncd/cli/blob/f3d25bda0ac5a47fe68565a07adb9fa5fe6c6db8/pkg/cmd/taskrun/cancel_test.go#L77).

**Comment by vdemeester** [comment]
@savitaashture @danielhelfand is it still an issue ?

**Comment by danielhelfand** [comment]
This is still an issue. However, it's a bit confusing to know how to proceed since PipelineRun/TaskRuns has different formats for cancellations. It would be nice to have the approach here align with how Pipelines handles this, but it can't be done due to the difference. I have documented more in https://github.com/tektoncd/pipeline/issues/3110.

I think my personal preference would be to just have `Cancelled` as the status, but I could see advantages in distinguishing between a PipelineRun and TaskRun cancellation. I think this should be discussed a bit further in pipelines before moving forward with this.
