### ISSUE TITLE
Add --no-headers flag for all list commands

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#799]
# Version and Operating System

**tkn Version:**
0.8.0

**Operating System:** 
all systems

# Expected Behavior
When using `tkn`, I should be able to list resources without header, i.e. `tkn ct list --no-headers` would produce something like

```
buildah                    23 hours ago
buildah-v0-10-0            23 hours ago
jib-maven                  23 hours ago
kn                         23 hours ago
```

instead of 

```
NAME                       AGE
buildah                    23 hours ago
buildah-v0-10-0            23 hours ago
jib-maven                  23 hours ago
kn                         23 hours ago
```

# Actual Behavior

Header is always printed

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

Both `kubectl` and `oc` have this flag
```
--no-headers=false: When using the default or custom-column output format, don't print headers (default print headers).
```

**Comment by waveywaves** [comment]
Tracker for --no-header in different `list` commands
- [ ] TaskRun
- [ ] PipelineRun
- [ ] Task
- [ ] Pipeline
- [ ] PipelineResource
- [ ] TriggerBinding
- [ ] TriggerTemplate
- [ ] EventListener
- [ ] Condition

**Comment by piyush-garg** [comment]
We can add the same for clustertriggerbinding and clustertask also

**Comment by waveywaves** [comment]
@piyush-garg Added ClusterTriggerBinding and ClusterTask to the tracker

**Comment by ppitonak** [comment]
What's the plan for ClusterTriggerBinding, ClusterTask, TriggerBinding, TriggerTemplate, EventListener and Condition?

**Comment by ppitonak** [comment]
@waveywaves do you have estimate when the rest will be implemented?

**Comment by pratikjagrut** [comment]
Tracker for `--no-headers` in different `list` commands
* [x]  TaskRun #834
* [x]  PipelineRun #834
* [x]  Task #840
* [x]  Pipeline #840
* [x]  PipelineResource #971
* [x]  ClusterTriggerBinding #1243 
* [x]  ClusterTask #1244 
* [ ]  TriggerBinding
* [ ]  TriggerTemplate
* [ ]  EventListener
* [ ]  Condition

**Comment by piyush-garg** [comment]
All subtasks done

/close
