### ISSUE TITLE
The TaskRun list in the pipelinerun describe has undefined order

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#81]
The list of `TaskRun` present in the `pipelinerun describe` command are appearing in random order.  I think they should always appear in the same order.

```shell
$ tkn pr desc cli-release-pipeline-run2gjrn
Name:              cli-release-pipeline-run2gjrn
Namespace:         default
Pipeline Ref:      cli-release-pipeline
# […]

Taskruns
NAME                                             STARTED        DURATION     STATUS
cli-release-pipeline-run2gjrn-build-n66sl        19 hours ago   50 seconds   Succeeded
cli-release-pipeline-run2gjrn-lint-twqdk         19 hours ago   22 seconds   Succeeded
cli-release-pipeline-run2gjrn-release-8z6l5      19 hours ago   3 minutes    Succeeded
cli-release-pipeline-run2gjrn-unit-tests-flcth   19 hours ago   1 minute     Succeeded
$ tkn pr desc cli-release-pipeline-run2gjrn
Name:              cli-release-pipeline-run2gjrn
Namespace:         default
Pipeline Ref:      cli-release-pipeline
# […]
Taskruns
NAME                                             STARTED        DURATION     STATUS
cli-release-pipeline-run2gjrn-lint-twqdk         19 hours ago   22 seconds   Succeeded
cli-release-pipeline-run2gjrn-release-8z6l5      19 hours ago   3 minutes    Succeeded
cli-release-pipeline-run2gjrn-unit-tests-flcth   19 hours ago   1 minute     Succeeded
cli-release-pipeline-run2gjrn-build-n66sl        19 hours ago   50 seconds   Succeeded
```

**Comment by girishramnani** [comment]
we can sort it by recently started or by name to preserve order @vdemeester

**Comment by danielhelfand** [comment]
@girishramnani Might make sense to do it by start time as this is how it is implemented for `tkn tr ls` by default for `0.2.0`.

**Comment by vdemeester** [comment]
@girishramnani @danielhelfand Definitely by start time :angel:

**Comment by girishramnani** [comment]
I can work on this

**Comment by hrishin** [comment]
@vdemeester wouldn't it be better to sort `TaskRuns` order as per `Pipeline` `Tasks` order? so the user could relate the order as defined in `pipeline`.

**Comment by vdemeester** [comment]
@hrishin ah good point :sweat_smile: I forgot it was on the `pipelinerun` script… :thinking: I am not sure anymore then

**Comment by girishramnani** [comment]
I have opened a WIP PR so I can change the necessary implementation if needed
https://github.com/tektoncd/cli/pull/201

**Comment by danielhelfand** [comment]
Agree with @hrishin

**Comment by girishramnani** [comment]
so should I change my implementation in #201 @danielhelfand @vdemeester @hrishin

**Comment by siamaksade** [comment]
@hrishin  The order defined in the pipeline does not really imply anything since they tasks would execute in whatever that is described via `after`, `input` and `output`. Order of execution I'd say is more imporant.

**Comment by sthaha** [comment]
@siamaksade do you mean the output should be a `bfs` walk of the pipeline graph? 

e.g.

```
(t1) --> (t2a) ----> (t3) ---> (t4)
   \                 /
    `----> (t2b) ->-'
```
it should print 
 -  t1
 - t2a 
 - t2b
 - t3
 - t4

**Comment by hrishin** [comment]
@siamaksade yes more precisely :+1:

**Comment by vdemeester** [comment]
I think the easiest path is by start time imho :stuck_out_tongue_closed_eyes:

**Comment by siamaksade** [comment]
@sthaha start time :)

**Comment by girishramnani** [comment]
Awesome, I will resolve the failures in the PR :smile:

**Comment by girishramnani** [comment]
Please close this as PR was merged https://github.com/tektoncd/cli/pull/201
