### ISSUE TITLE
DAG Report: Order of executions

### ISSUE THREAD

**Issue by naiduasn** [tektoncd/cli#811]
# Expected Behavior
When we use DAG with tekton pipelines, we may execute a few tasks in parallel and few in sequential.
How will I show how these tasks are executed in the pipeline? The current command displays only tasks executed and its status.
# Actual Behavior
https://github.com/tektoncd/cli/issues/314 

# Steps to Reproduce the Problem
1.Execute any pipeline with DAG
2.Check tkn pipeline describe

# Additional Info
Would like to know if i can get this info from any tekton API.
I would like to use tekton and wrap it with my custom UI flows.

**Comment by piyush-garg** [comment]
I think the actual behavior is already an issue here. #314

**Comment by vdemeester** [comment]
Indeed, let's close this as a duplicate
/close
