### ISSUE TITLE
Should PipelineRun describe list the Task in addition (or with) the TaskRun

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#82]
Currently, `tkn pipelinerun describe my-run` display the TaskRun attached to the PipelineRun.

This means:
- The list varies depending on the status of the PipelineRun as it only display the TaskRun that have been created.
- If the PipelineRun, there is no way to see how many Task(s) succeeded before the failure.

I think we should show the Pipeline Task for the PipelineRun, either merged with the TaskRun part (aka, listing the Task and attaching the TaskRun status to it) or in a separate table

/kind question

cc @siamaksade

**Comment by siamaksade** [comment]
Also related https://github.com/tektoncd/pipeline/issues/994

It makes sense to show the tasks and attach their task runs
