### ISSUE TITLE
Display TaskRun and PipelineRun labels

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/cli#831]
# Version and Operating System

**tkn Version:**
Client version: 0.8.0

**Operating System:** 
MacOS Catalina

# Expected Behavior

When describing at a TaskRun and PipelineRun I should be able to see labels associated to it.
This will greatly help filtering similar taskruns and pipelineruns.

Similar issue on the dashboard side: https://github.com/tektoncd/dashboard/issues/1181

**Comment by danielhelfand** [comment]
Closed by #851
