### ISSUE TITLE
tkn task/pipeline describe shows the taskrun/pipelinerun sorted by taskrun/pipelinerun name instead of STARTED

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#839]
# Version and Operating System

**tkn Version:**
v0.8.0

**Operating System:** 
Linux

# Expected Behavior
tkn task/pipeline describe should show the taskrun/pipelinerun STARTED (In descending order)

# Actual Behavior
tkn task/pipeline describe shows the taskrun/pipelinerun sorted by taskrun/pipelinerun name instead of STARTED

# Steps to Reproduce the Problem

1. Create task and pipeline
2. Start the pipeline several times
3. Describe the pipeline/task and observe the pipelinerun/taskrun history

# Additional Info
User will be mostly worried about the latest results of the task/pipeline

```
$ tkn pipeline describe build-and-deploy 
Name:        build-and-deploy
Namespace:   test-tekton

📦 Resources

 NAME         TYPE
 ∙ git-repo   git
 ∙ image      image

⚓ Params

 NAME                TYPE     DEFAULT VALUE
 ∙ deployment-name   string   ---

🗒  Tasks

 NAME                  TASKREF             RUNAFTER
 ∙ build-image         buildah             
 ∙ apply-manifests     apply-manifests     build-image
 ∙ update-deployment   update-deployment   apply-manifests

⛩  PipelineRuns

 NAME                           STARTED          DURATION    STATUS
 ∙ build-and-deploy-run-4z7zw   17 minutes ago   3 minutes   Failed
 ∙ build-and-deploy-run-68nnm   1 minute ago     ---         Running
 ∙ build-and-deploy-run-mbtnh   16 minutes ago   2 minutes   Failed
 ∙ build-and-deploy-run-x6lds   8 minutes ago    4 minutes   Succeeded
 ∙ build-and-deploy-run-zdmvm   8 minutes ago    4 minutes   Succeeded

**Comment by danielhelfand** [comment]
Full list of resources affected:

- [ ] PipelineRun describe:
- [x] Task describe #881 
- [ ] Pipeline describe
- [ ] ClusterTask describe

**Comment by danielhelfand** [comment]
It looks like we actually already support this with [`PipelineRun`](https://github.com/tektoncd/cli/blob/6dad772d2bd697c0f66ec404a4db73b449b2cfa3/pkg/pipelinerun/description/description.go#L111), so this should be resolved.
