### ISSUE TITLE
Propogate deletion of PipelineRuns if Pipeline is deleted via flag

### ISSUE THREAD

**Issue by waveywaves** [tektoncd/cli#850]
# Version and Operating System

**tkn Version:**
0.8.0
**Operating System:** 
Fedora 29

# Expected Behavior
Propogate deletion of associated PipelineRuns if Pipeline is deleted.
Details on origin of this concept is given in the comment below.
https://github.com/tektoncd/pipeline/issues/2223#issuecomment-600617363

Some things to things about.
- Allow users to set this as default behavior in `tkn` ?
- What would be the name of the flag ? `--propogate-to-children` ? Not a great name but I am out of ideas.
- Can this also be applied to Tasks and TaskRuns ?

# Actual Behavior
`None currently`

**Comment by danielhelfand** [comment]
This does exist as `--all` (i.e., `tkn pipeline delete pipelineName --all`) in `v0.8.0` but will be renamed to `tkn pipeline delete pipelineName --prs` in `v0.9.0`. `--all` has be repurposed for deleting all pipelines in a namespace. 

This also exists for TaskRuns as `tkn task delete taskName --all` in `v0.8.0` and will be `tkn pipeline delete taskName --trs`.

Whether or not this should be configurable through the CLI will depend on what the approach taken by pipeline is, which is unknown at this time. I am going to close this for now, and it can be reopened as a different issue focused on whatever is implemented with pipeline in the future.
