### ISSUE TITLE
timeout is not respected when using use-pipelinerun or --last

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#862]
when using `tkn pipeline start pipl1 --use-pipelinerun piplr1` the timeout that
was set previously is not set on the newly created pipeline.

/kinds bugs

**Comment by danielhelfand** [comment]
/assign

We just need to add the `--timeout` from `usepr` similar to what is done [here](https://github.com/tektoncd/cli/blob/ff0a567e4834c43ad06ee8bf136e86d298f98100/pkg/cmd/pipeline/start.go#L240).
