### ISSUE TITLE
Set config-defaults via tkn

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#874]
# Expected Behavior

A ConfigMap called `config-defaults` can be created in the `tekton-pipelines` namespace that specifies information about defaults, such as timeouts, service accounts, etc. for PipelineRuns/TaskRuns. `tkn` should offer a way for users to both create/manage these defaults.

Perhaps the subcommand could be `tkn config` and initial actions for the command could be `create` to create a ConfigMap with default values and `update` to change the defaults ConfigMap. 

My initial thought would be to support an interactive approach to doing this as `kubectl` can allow users to create and update a ConfigMap defined via yaml. But there may even be an opportunity here to offer a `--dry-run` option that outputs a yaml file to help a user properly format the config-defaults ConfigMap to be created.

This issue is more to begin the discussion about possibilities for managing config-defaults via `tkn` and should also factor in possible changes via the following pipeline issues:
* https://github.com/tektoncd/pipeline/issues/2334
* https://github.com/tektoncd/pipeline/issues/2335

**Comment by danielhelfand** [comment]
After discussing in the working group on 4/14/20, the thought process here is to support and interactive create and update option. While tektoncd/pipeline#2335 has not been put in place as far as supporting namespaced configs, the initial implementation of this feature could be to support the cluster-wide config-default approach that Tekton currently has. This feature should also factor in https://github.com/tektoncd/pipeline/pull/2260, which makes the ConfigMap name customizable as opposed to only supporting the name config-defaults.

**Comment by vdemeester** [comment]
/reopen
We should discuss this still
