### ISSUE TITLE
New PipelineRun fails due to serviceAccount vs serviceAccountName

### ISSUE THREAD

**Issue by soukron** [tektoncd/cli#879]
# Version and Operating System

**tkn Version:**
Client Version 0.4.0

**Operating System:** 
Linux

# Expected Behavior
$ tkn pipeline start build-and-deploy \
    -r git-repo=api-repo \
    -r image=api-image \
    -p deployment-name=vote-api

Pipelinerun started: build-and-deploy-run-z2rz8

In order to track the pipelinerun progress run:
tkn pipelinerun logs build-and-deploy-run-z2rz8 -f -n pipelines-tutorial

# Actual Behavior
$ tkn pipeline start build-and-deploy \
    -r git-repo=api-repo \
    -r image=api-image \
    -p deployment-name=vote-api

Error: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccount"

# Steps to Reproduce the Problem

1. Install OpenShift 4.3.8
2. Install Pipelines (dev-preview, currently 0.10.7) using OperatorHub
3. Follow the tutorial https://github.com/openshift/pipelines-tutorial 
4. As soon as you start the pipeline it fails with the previous error

# Additional Info
Refer to https://github.com/tektoncd/pipeline/issues/1219. It seems, but I haven't reviewed in detail, that tkn is sending a wrong resource and the webhook rejects it as it has a unknown field. The error is quite descriptive in this case.

**Comment by danielhelfand** [comment]
@soukron Is there any reason for using `tkn v0.4.0`? I would update to a more recent version of `tkn`. The current version of `tkn` is `v0.8.0` and uses the correct attribute, which is `serviceAccountName` instead of `serviceAccount` as was originally implemented with pipelines.

**Comment by soukron** [comment]
I'm following https://openshift.github.io/pipelines-docs/docs/0.10.5/proc_installing-cli.html documentation for the tutorial and it refers to 0.4.0. I wasn't even aware that there's a newer version of the client.

I have tried with it and as expected, it works. 

Can you help with the page I've sent? If you can't I'll figure how to get the documentation page fixed.

**Comment by danielhelfand** [comment]
@soukron Yeah, the documentation appears way out of date. I believe the docs are maintained [here](https://github.com/openshift/pipelines-docs). The actual tutorial you are following, which is more up to date, is [here](https://github.com/openshift/pipelines-tutorial). I think either repo is a good place to raise this issue.
