### ISSUE TITLE
Fix log command tech depts (refactoring)

### ISSUE THREAD

**Issue by hrishin** [tektoncd/cli#88]
- Replace[ step sorter](https://github.com/tektoncd/cli/pull/76#discussion-diff-294167529R107) (pods container iteration) with `taskrun status`
  [#Ref](https://github.com/tektoncd/pipeline/commit/8552f8bdead8e304611ef12d71489248e96d246d#diff-ccd231265a8c68ecb3e8bae3a6e565cf)
- [Extract](https://github.com/tektoncd/cli/pull/76#discussion_r293479646) the `log_reader` and `log_writter` to respective packages like `taskun`, `pipelinerun`

- Use [better dep](https://github.com/tektoncd/cli/blob/master/go.mod#L15) for color logs printing

**Comment by hrishin** [comment]
It could involve other enhancements like https://github.com/tektoncd/cli/issues/83

**Comment by vdemeester** [comment]
@hrishin what is the status of this one ?

**Comment by vdemeester** [comment]
ping @hrishin :angel:

**Comment by hrishin** [comment]
@vdemeester sorry I missed this later :bowing_man: . Will bump the priority of it and try to get it done.
