### ISSUE TITLE
Better Description for --workspace/-w Option for Pipeline/Task Start

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#895]
Regardless of a user's level of expertise with workspaces, the following descriptions of the `--workspace` options for `tkn pipeline start`/`tkn task start` are not the most informative as part as what is to be included as arguments to these options:

**Pipeline:**

https://github.com/tektoncd/cli/blob/fdf5a9e7e38939bc46f67a0c239b521e6f272e89/pkg/cmd/pipeline/start.go#L156

**Task:**

https://github.com/tektoncd/cli/blob/fdf5a9e7e38939bc46f67a0c239b521e6f272e89/pkg/cmd/task/start.go#L162

The following questions should be answered by this description in a brief way:
1. What is the option for?
2. What arguments should be included to make use of the option?
3. What's an example of arguments specified?

Supplementary documentation:
* https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#workspaces
* https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#workspaces

**Comment by chmouel** [comment]
Yeah I believe there is room for usability here, the issue is mostly about UX since this can be quite complicated 

maybe we can follow on #1169 which is still open,
