### ISSUE TITLE
Trigger pipeline

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#9]
**Input (Required):** pipeline name

**Input:** pipeline resources (infer values when possible e.g. git from current dir)

**Input:** pipeline parameters

**Output:** create a pipeline-run and the resources and print the name of the pipeline-run

 

Ideally, it should be possible to run a minimal command like `tkn trigger foo-pipeline` in order to trigger a pipeline with resources being populated automatically

**Comment by siamaksade** [comment]
More details on the trigger use-cases added in this [Google Doc](https://docs.google.com/document/d/1M52K5PhWkNXXw8Mfg1CEzDHP4NUmZZs0Z2okq0rrsAM/edit?usp=sharing)

**Comment by vdemeester** [comment]
/close
`start` is implemented
