### ISSUE TITLE
Emoticons and colors are not displaying properly on Windows 

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#914]
# Version and Operating System

**tkn Version:**
Latest dev

**Operating System:** 
Microsoft Windows-10 Enterprise(10.0.15063)

# Expected Behavior
Emoticons and colors should display properly on Windows-10 machine

# Actual Behavior
Emoticons and colors are not getting displayed properly on Windows-10 machine

# Steps to Reproduce the Problem

1. Create and start a task using `tkn task start` command
2. List the tasks using the command `tkn task ls` and observe the `STATUS` field
3. Describe the task using the command `tkn task describe` and observe the output

#Note: 
1. The output for `list` and `describe` command looks fine when we use `-C` option

# Additional Info
Screenshots for the output of `list` and `describe` are below
![Screenshot from 2020-04-20 09-17-04](https://user-images.githubusercontent.com/13780748/79716020-002f8700-82f3-11ea-9cd2-dbd3f1ae1ff3.png)

![Screenshot from 2020-04-20 10-39-52](https://user-images.githubusercontent.com/13780748/79716145-6caa8600-82f3-11ea-9462-592913f870e1.png)

Tested with powershell, the emoticons in `describe` are not getting displayed properly but output of `tkn tr ls` looks fine
![Screenshot from 2020-04-20 16-47-55](https://user-images.githubusercontent.com/13780748/79746051-faec2f80-8326-11ea-977c-0b1492d6c668.png)

**Comment by chmouel** [comment]
We probably should disable it if we are on windows

**Comment by VeereshAradhya** [comment]
Tested with powershell and updated the description

**Comment by ppitonak** [comment]
> We probably should disable it if we are on windows

IMHO there should be a CLI switch for disabling it explicitly (+ disable by default on Win) because sometimes you don't want emoticons and color when exporting logs to external systems.

**Comment by chmouel** [comment]
if you do `--nocolour` it will disable emoticon as well.... 

And even tho if you do a redirection (i.e: not terminal stty) to a file the emoticons and colours will be disabled by default....

**Comment by chmouel** [comment]
@VeereshAradhya is it something you can do ? As I don't have a windows machine, I won't be able to fix it  (but i can disable it if we run on windows)

**Comment by chmouel** [comment]
@VeereshAradhya can you test https://drive.google.com/open?id=1IWYIMlwqTr4tCLiUAcTmB245h72-dM9d please ?

thanks!

**Comment by VeereshAradhya** [comment]
Tested the executable given by @chmouel . Both color and emoticons are disabled 
**Command Prompt**:
![Screenshot from 2020-04-21 14-22-23](https://user-images.githubusercontent.com/13780748/79846468-1c5b2300-83dc-11ea-8444-6fff3b446474.png)

**Powershell**
![Screenshot from 2020-04-21 14-25-00](https://user-images.githubusercontent.com/13780748/79846591-41e82c80-83dc-11ea-9fd0-389caac0b4b3.png)
