### ISSUE TITLE
tkn tr/pr logs command is turning the command prompt into green on Windows

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#915]
# Version and Operating System

**tkn Version:**
Latest dev

**Operating System:** 
Microsoft Windows-10 Enterprise(10.0.15063)

# Expected Behavior
Once the logs are printed (green) the command prompt should continue to be in previous color (white)

# Actual Behavior
Once the logs are printed (green) the command prompt is getting displayed in green color

# Steps to Reproduce the Problem

1. Create a task and start the task
2. Print the logs of the taskrun using the command `tkn tr logs`
3. Observe the command prompt once the logs are displayed

**Note**: The command works fine with `-C` option

# Additional Info
Screenshot is below
![Screenshot from 2020-04-20 11-52-03](https://user-images.githubusercontent.com/13780748/79720039-6d481a00-82fd-11ea-9a36-bf2ab98dafb5.png)

In powershell the `tkn tr logs` command is not turning the prompt to green
![Screenshot from 2020-04-20 16-52-13](https://user-images.githubusercontent.com/13780748/79746354-7b129500-8327-11ea-8a3b-167315df0d2c.png)

**Comment by chmouel** [comment]
What about if you are using `--nocolour` flag, does it still turn the prompt in green?

**Comment by VeereshAradhya** [comment]
If we are using `-C, --nocolor` flag, it works fine. I have mentioned that in  **Note** section in description

**Comment by chmouel** [comment]
we are using `fatih/color` library, since it has been archived and can't fix it, we can either : 

1) disable colour and emojis on windows
2) try to find another library supporting windows terminal colours

I think we should do 1 until someone cares enough about windows support to go down the road of 2)

**Comment by VeereshAradhya** [comment]
Tested with powershell and updated the description

**Comment by chmouel** [comment]
the README of fatih/color actually says that it support windows terminal colors, so it maybe how we use it that's buggy

**Comment by chmouel** [comment]
/assign

Let's disable the colouring until a dev who has windows and can fix it...
