### ISSUE TITLE
Inconsistent Experience Between Using Interactive tkn task/pipeline Logs 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#916]
When using `tkn pipeline logs` interactive mode, if only one Pipeline exists in a namespace, the PipelineRuns for that Pipeline are instantly displayed for a user to select from:

```
tkn p logs
? Select pipelinerun:  [Use arrows to move, type to filter]
> deploy-pipeline-hello2-run-tw856 started 18 hours ago
  deploy-pipeline-hello2-run-ngwtm started 18 hours ago
  deploy-pipeline-hello2-run-wghrc started 18 hours ago
```

This same experience does not exist when using `tkn task logs`. If only one Task exists in the namespace, it still asks the user to select the Task before TaskRuns are displayed:

```
tkn t logs
? Select task:  [Use arrows to move, type to filter]
> sleep1s
```

# Steps to Reproduce the Problem

1. Create exactly one Pipeline and Task in a namespace. 
2. Run `tkn pipeline logs`. If there are PipelineRuns for the Pipeline you have created, expect to see a list of PipelineRuns. If not PipelineRuns are created, expect to see `No pipelineruns found for pipeline: pipelineName`.
3. Run `tkn task logs`. See the prompt to select a Task. 

# Additional Info

Whichever experience above is preferred, I am open to, but there should be consistency across the commands.

**Comment by piyush-garg** [comment]
I will rather mark it as a feature, we implemented it for the pipeline but not for task and we can add that
