### ISSUE TITLE
Negative Started and aged time is shown in Windows

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#920]
# Version and Operating System

**tkn Version:**
Latest dev

**Operating System:** 
Microsoft Windows-10 Enterprise(10.0.15063)

# Expected Behavior
Time should be positive

# Actual Behavior
Negative time is shown

# Steps to Reproduce the Problem

1. Create a task
2. Start the task with command `tkn task start`
3. Immediately list the task using `tkn taskrun list` and observe the `STARTED` field

# Additional Info
Command prompt screenshots below
![Screenshot from 2020-04-21 17-03-54](https://user-images.githubusercontent.com/13780748/79871370-dfa22280-8401-11ea-994e-6f9349d60f70.png)

![Screenshot from 2020-04-21 17-47-40](https://user-images.githubusercontent.com/13780748/79871376-e16be600-8401-11ea-86ec-6a5c6302883b.png)

Powershell screenshot below
![Screenshot from 2020-04-21 17-12-19](https://user-images.githubusercontent.com/13780748/79871374-e0d34f80-8401-11ea-8487-b86913093660.png)

**Comment by vdemeester** [comment]
@VeereshAradhya might be a small delay between the server and the client clocks too :sweat_smile:

**Comment by VeereshAradhya** [comment]
Working as expected
