### ISSUE TITLE
Add params description to the describe command

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/cli#929]
The following commands do not include params description in the describe subcommands: ClusterTask, Pipeline,Task, TriggerTemplate.

# Additional Info

- [x] ClusterTask https://github.com/tektoncd/cli/pull/930
- [x] Pipeline https://github.com/tektoncd/cli/pull/930
- [x] Task https://github.com/tektoncd/cli/pull/930
- [x] TriggerTemplate https://github.com/tektoncd/cli/pull/928

**Comment by piyush-garg** [comment]
/close

fixed with #930
