### ISSUE TITLE
Version command should return the version

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#95]
The `tkn version` command currently returns `dev` instead of the cli version:

```
$ tkn version                                                                                                                                                            
Client version: dev
```

**Comment by chmouel** [comment]
This is fixed in https://github.com/tektoncd/cli/commit/2e29b9fb8abf7d5c1b41729720ec9b86451324f7 I believe we would need to make a new release to be able to "apply" it

**Comment by vdemeester** [comment]
[`v0.1.1`](https://github.com/tektoncd/cli/releases/tag/v0.1.1) is release with that fix :angel:
We can close :wink:.
