### ISSUE TITLE
Adapt --filename Option to Also Start TaskRuns/PipelineRuns from a Local or Remote File

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#950]
# Expected Behavior

The `--filename` or `-f` option for `tkn pipeline start` and `tkn task start` currently only allow users to start a PipelineRun/TaskRun from a file with a Pipeline/Task defined. The `-f` option should also allow users to pass as input a PipelineRun/TaskRun to start. This would help with issues like #668 for specifying a PodTemplate as part of a TaskRun/PipelineRun. 

Examples:

`tkn t start --filename taskrun.yaml`

`tkn p start --filename https://www.github.com/user/repo/pipelinerun.yaml`

# Additional Info

Questions about this feature that should be discussed:

1. Should this actually be `tkn pipelinerun start pipelinerun.yaml`/`tkn tr start https://www.github.com/user/repo/taskrun.yaml`?
2. Should this feature work with options that override runtime values, such as `-i`, `-o`, `-p`, `-s`, `-r`, etc.?

**Comment by danielhelfand** [comment]
Discussed in working group on 5/12/20. Will look into using [`kustomize`](https://github.com/kubernetes-sigs/kustomize#kustomize) here to help with PodTemplate support.

**Comment by lmserrano** [comment]
Also, it could be interesting to allow 2 different flags, one for specifying the `task.yaml` (`-f`, as you currently have it), and another for specifying the `taskrun.yaml` with all its parameters (`-F`, for example).

As a suggestion, an early version of this could simply invoke `kubectl create -f taskrun.yaml` underneath, but with the advantage of giving the nice output of the `tkn`:

```
$ tkn task start some-task -n "tekton-projects" -f ./some-task.yaml -F ./some-task-run.yaml
Taskrun started: some-task-run-kzb78

In order to track the taskrun progress run:
tkn taskrun logs some-task-run-kzb78 -f -n some-namespace
```
