### ISSUE TITLE
Trigger resources are not listed

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#955]
`tkn` doesn't list triggertemplates:

```
$ kubectl get triggertemplate
NAME                                   AGE
petclinic-deployment-triggertemplate   4m

$ tkn triggertemplate list
No triggertemplates found
```

Neither does it for EventListeners and TriggerBindings.

**Comment by vdemeester** [comment]
@siamaksade which version ? :angel:

**Comment by danielhelfand** [comment]
Seems to work with 0.9.0:

```
$ kubectl get tt
NAME                AGE
pipeline-template   22s

$ tkn triggertemplate list
NAME                AGE
pipeline-template   29 seconds ago
```

**Comment by piyush-garg** [comment]
There is the apiVersion change from `tekton.dev` to `triggers.tekton.dev` in triggers `0.4.0` CRDs and that change happened in CLI with `0.9.0`

**Comment by siamaksade** [comment]
Can't reproduce on a new cluster. Closing for now
