### ISSUE TITLE
task start with --dry-run does not throw any error if the task expects params and not provided

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#956]
# Version and Operating System

**tkn Version:**
v0.9.0

**Operating System:** 
All

# Expected Behavior
the command should output some error message saying task expects params

# Actual Behavior
the command is generating taskrun without throwing any error

# Steps to Reproduce the Problem

1. Create a task which takes param and which does not have have any default value for param
2. run the command `tkn task start <task name> --dry-run"` without providing the param value
3. Observe the output

# Additional Info
Below are the command logs
```
$ tkn task describe python-script-task 
Name:          python-script-task
Namespace:     veeresh-testing
Description:   python task

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 NAME           TYPE     DESCRIPTION          DEFAULT VALUE
 ∙ test-param   string   this is test param   ---

🦶 Steps

 ∙ step-one

🗂  Taskruns

 No taskruns

$ tkn task start python-script-task --dry-run
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: python-script-task-run-
  namespace: veeresh-testing
spec:
  resources: {}
  serviceAccountName: ""
  taskRef:
    name: python-script-task
status:
  podName: ""
[varadhya@localhost testing]$ 
```

**Note**: The start command throws error message for --dry-run, when we provide invalid param with value
```
$ tkn task start python-script-task -p abcd=efh --dry-run
Error: param 'abcd' not present in spec
```

**Comment by danielhelfand** [comment]
This is not just for `--dry-run`. This is what happens for starting a Task without `--dry-run` as well. It seems there isn't the same validation of resources/params for `tkn task start` like there is for `tkn pipeline start`, which provides an interactive mode for specifying param values if none are provided. However, `tkn pipeline start` doesn't validate this case if `--use-param-defaults` is specified in a similar manner to what you are describing above. 

Basically, this comes down to the question of where this validation should take place. As implemented, the idea seems to be that this validation should be the responsibility of pipelines to send back an error. However, I agree with the idea that this seems inconsistent with the way `tkn` validates params/resources.

The downside of this would be reimplementing more logic into the cli that is already being handled by pipelines. The positive of this would be reducing failed TaskRuns/PipelineRuns that would be created on a cluster. 

I guess I would support some kind of validation here, but I think this warrants a discussion first to determine if it's worthwhile/what the approach would be. I think this would lead into conversations about supporting interactive prompt support for resources for `task start`/`clustertask start` and also require this type of validation for not just `tkn task start` but also `pipeline start`/`clustertask start`.

**Comment by vdemeester** [comment]
We should try to use server-side dry-run support (like `kubectl`) if present, as it runs the admission controller on those (defaults, conversions, validation,…), see https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/
