### ISSUE TITLE
Workspace Option for tkn clustertask start

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#958]
# Expected Behavior

Similar to what was implemented in #826 and #854 for `tkn pipeline start` and `tkn task start`, there should be a `workspace` option for `tkn clustertask start` implemented exactly as #826 and #854 were implemented to connect a workspace when using `tkn clustertask start`. 

This also should account for whether `tkn clustertask start` with workspaces should support an interactive option. Currently only `tkn pipeline start` supports an interactive option for providing a workspace, but both `tkn task start` and `tkn clustertask start` should also have this feature as well if `tkn pipeline start` supports this.

**Comment by piyush-garg** [comment]
@anshulvermapatel If you have not worked on it yet, I think PR #1051 resolves this also

**Comment by piyush-garg** [comment]
cc @danielhelfand @vinamra28

**Comment by vinamra28** [comment]
@piyush-garg I agree with you. #1051 resolves this also.

**Comment by anshulvermapatel** [comment]
@piyush-garg , yes, it resolves it. we should close this issue then.
