### ISSUE TITLE
Unable to start task with -f flag if the task definition file contains params with no default value

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#959]
# Version and Operating System

**tkn Version:**
v0.9.0

**Operating System:** 
All

# Expected Behavior
Taskrun should get created

# Actual Behavior
The command is throwing the error `Error: param 'test-param' not present in spec`

# Steps to Reproduce the Problem

1. Create a task definition in a yaml file with params with no default values
2. Start the taskrun using the command `tkn task start -f <yaml file> -p <param name>=<param value>`

# Additional Info
Below are command logs
```
$ cat script-task-python.yaml 
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-script-task-test
spec:
  description: python task
  params:
    - name: test-param
      description: this is test param
  steps:
    - name: step-one
      image: python  
      script: |
        #!/usr/bin/env python3
        print("$(params.test-param)")
        print("Hello from Python!")
        import time
        for i in range(50):
          print("this is task", flush=True)
          time.sleep(2)


$ cat script-task-python.yaml 
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-script-task-test
spec:
  description: python task
  params:
    - name: test-param
      description: this is test param
  steps:
    - name: step-one
      image: python  
      script: |
        #!/usr/bin/env python3
        print("$(params.test-param)")
        print("Hello from Python!")
        import time
        for i in range(50):
          print("this is task", flush=True)
          time.sleep(2)

$ tkn task start -f script-task-python.yaml -p test-param="this is test param"
Error: param 'test-param' not present in spec
[varadhya@localhost testing]$ 
```

**Comment by danielhelfand** [comment]
The params will be on the TaskSpec in this case as opposed to the TaskRunSpec, which is causing the issue:

https://github.com/tektoncd/cli/blob/f7706b51b48d3fb0b0c87ce209a4b8e8cf67bed0/pkg/cmd/task/start.go#L323

**Comment by danielhelfand** [comment]
This also affects `tkn pipeline start`:

https://github.com/tektoncd/cli/blob/f7706b51b48d3fb0b0c87ce209a4b8e8cf67bed0/pkg/cmd/pipeline/start.go#L270

**Comment by pradeepitm12** [comment]
I tried with the older version of pipeline and CLI, the bug exists there as well.

**Comment by danielhelfand** [comment]
@pradeepitm12 Yes, I think this was missed from the original implementation of this.
