### ISSUE TITLE
`tkn task delete <t1> <t2> ..<tn> --trs` does not delete all the taskruns of the tasks `<t1> <t2>..<tn>`

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#970]
# Version and Operating System

**tkn Version:**
v0.9.0

**Operating System:** 
All

# Expected Behavior
`tkn task delete <t1> <t2>..<tn> --trs` should delete all the taskruns of `<t1> <t2>..<tn>`

# Actual Behavior
`tkn task delete <t1> <t2>..<tn> --trs` is not deleting all the taskruns of the tasks `<t1> <t2>..<tn>`

# Steps to Reproduce the Problem

1. Create Multiple tasks with params
2. Start the created tasks in step 1 multiple times to create multiple taskruns without providing params
3. Start the created tasks in step 1 multiple times to create multiple taskruns
4. Run the command `tkn task delete <t1> <t2>..<tn> --trs`

**Note**: The issue is not reproducible all the times 
# Additional Info
Below are the command logs
Below is the list of taskruns for the tasks `first-task`, `second-task` and `third-task`
```
$ tkn tr ls
NAME                    STARTED          DURATION   STATUS
second-task-run-6jj57   3 seconds ago    ---        Failed(TaskRunValidationFailed)
third-task-run-ppdh6    8 seconds ago    ---        Running(Pending)
second-task-run-qcg9s   14 seconds ago   ---        Running(Pending)
first-task-run-sxzwj    21 seconds ago   ---        Running
second-task-run-lfsb5   27 seconds ago   ---        Running
second-task-run-xdzpp   38 seconds ago   ---        Running
third-task-run-qsmgj    41 seconds ago   ---        Running
third-task-run-g45j8    44 seconds ago   ---        Failed(TaskRunValidationFailed)
third-task-run-xg4d4    46 seconds ago   ---        Running
third-task-run-zg2qs    48 seconds ago   ---        Failed(TaskRunValidationFailed)
third-task-run-k7hq4    49 seconds ago   ---        Failed(TaskRunValidationFailed)
second-task-run-s826b   54 seconds ago   ---        Failed(TaskRunValidationFailed)
first-task-run-sl2bn    1 minute ago     ---        Failed(TaskRunValidationFailed)
third-task-run-p5t5z    1 minute ago     ---        Running
third-task-run-c89gp    1 minute ago     ---        Running
third-task-run-vjffd    1 minute ago     ---        Running
second-task-run-rxkxq   1 minute ago     ---        Running
second-task-run-vxbk7   1 minute ago     ---        Running
second-task-run-wxcdn   1 minute ago     ---        Running
first-task-run-z59g9    1 minute ago     ---        Running
first-task-run-d69xb    1 minute ago     ---        Running
first-task-run-mnzq5    1 minute ago     ---        Running
first-task-run-bb9pc    2 minutes ago    ---        Failed(TaskRunValidationFailed)
first-task-run-fdbx4    2 minutes ago    ---        Failed(TaskRunValidationFailed)
second-task-run-6xsc2   2 minutes ago    ---        Failed(TaskRunValidationFailed)
second-task-run-xk5s7   2 minutes ago    ---        Failed(TaskRunValidationFailed)
second-task-run-gbln9   2 minutes ago    ---        Failed(TaskRunValidationFailed)

```
Deleting the tasks `first-task`, `second-task` and `third-task` with `--trs` flag
```
$ tkn task delete first-task second-task third-task --trs
Are you sure you want to delete task and related resources "first-task", "second-task", "third-task" (y/n): y
TaskRuns deleted: "first-task-run-bb9pc", "first-task-run-d69xb", "first-task-run-fdbx4", "first-task-run-mnzq5", "first-task-run-sxzwj", "first-task-run-z59g9", "second-task-run-6xsc2", "second-task-run-lfsb5", "second-task-run-qcg9s", "second-task-run-rxkxq", "second-task-run-s826b", "second-task-run-vxbk7", "second-task-run-wxcdn", "second-task-run-xdzpp", "third-task-run-c89gp", "third-task-run-g45j8", "third-task-run-k7hq4", "third-task-run-p5t5z", "third-task-run-ppdh6", "third-task-run-qsmgj", "third-task-run-vjffd", "third-task-run-xg4d4", "third-task-run-zg2qs"
Tasks deleted: "first-task", "second-task", "third-task"
```
Listing the taskruns again
```
$ tkn tr ls
NAME                    STARTED          DURATION   STATUS
second-task-run-6jj57   43 seconds ago   ---        Failed(TaskRunValidationFailed)
first-task-run-sl2bn    1 minute ago     ---        Failed(TaskRunValidationFailed)
second-task-run-xk5s7   2 minutes ago    ---        Failed(TaskRunValidationFailed)
second-task-run-gbln9   2 minutes ago    ---        Failed(TaskRunValidationFailed)
```

**Comment by anshulvermapatel** [comment]
@VeereshAradhya , I too see that it does not delete all the related tr, Let me check this.

**Comment by anshulvermapatel** [comment]
@VeereshAradhya , I observed that the TR which does not get deleted does not contain the label 'tekton.dev/task:<task_name>' in them. Can you please check from your side if you are observing the same?

**Comment by anshulvermapatel** [comment]
This may be related to https://github.com/tektoncd/cli/issues/858

**Comment by anshulvermapatel** [comment]
https://github.com/tektoncd/cli/pull/993 seems to resolve this issue.
The `TaskRuns` were selected by using labels but sometimes the labels do not get applied to some of the `TaskRuns` like what is mentioned in https://github.com/tektoncd/cli/issues/858 for `Pipelines`, because of which they do not get included in the `TR` list for deletion.
The PR mentioned above selects the `TaskRun` on the basis of `taskRef` which is getting applied correctly. 
Please build a latest version and check if you still see this issue.

**Comment by VeereshAradhya** [comment]
@anshulvermapatel Usually the taskruns with status ` Failed(TaskRunValidationFailed)` were not getting deleted with `--trs`. Now `tkn task start` has become interactive and because of that I am not able to create any taskruns with status ` Failed(TaskRunValidationFailed)` hence I am not able to reproduce the issue.

**Comment by anshulvermapatel** [comment]
@VeereshAradhya , Yaa I agree with you, they were not getting deleted, because previously the deletion used to happen on the basis of labels if a `TaskRun` had a label referring a particular `Task` (which is being deleted), only those `TaskRuns` were getting deleted. The main issue here was that the `Tasks` when started, did not properly add labels to all the `TaskRuns` because of which while deleting the `Tasks` with `--trs` option, those `TaskRuns` without labels did not get deleted.
After this `PR`,  it deletes the relevant `TaskRuns` by filtering them on the bases of `TaskRef` that is why all the relevant `TaskRuns` get deleted properly.
I hope it's clear now.

**Comment by VeereshAradhya** [comment]
Yeah.. Since I am unable to reproduce the issue now, I am closing the issue.
