### ISSUE TITLE
Add installed triggers version information to tkn version command

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/cli#980]
**Background:** 

If the running cluster have Triggers installed the `tkn version` command should display the installed triggers version
# Version and Operating System

**tkn Version:**
latest (from master branch)

**Operating System:** 
All

# Expected Behavior
```
./tkn version
Client version: dev
Pipeline version: v0.12.0
Triggers version: v0.4.0
```

# Actual Behavior
```
./tkn version
Client version: dev
Pipeline version: v0.12.0
```

/kind feature

**Comment by danielhelfand** [comment]
I believe this was addressed by #981. Feel free to reopen if I am mistaken.
