### ISSUE TITLE
`tkn pipeline start -f <file-name>` does not validate the pipeline definition properly

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/cli#982]
# Version and Operating System

**tkn Version:**
v0.9.0

**Operating System:** 
All

# Expected Behavior
`tkn pipeline start -f <file-name>` should validate the file and should throw error if spec is not proper

# Actual Behavior
`tkn pipeline start -f <file-name>` does not validate the pipeline definition properly

# Steps to Reproduce the Problem

1. Create tasks `t1` and `t2` and condition `c1`
2. Create a pipeline definition yaml file such that `t2` will be run after `t1`
3. Change the field `runAfter` to `runaftr` and `conditions` to `conditons` and save the file
4. Start the pipeline using the command `tkn p start -f <file-name>

# Additional Info
Below are the command logs
```
$ tkn pr ls
No PipelineRuns found
$ 
$ tkn tr ls
No TaskRuns found
$ 
$ cat pipeline_invalid.yaml 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-invalid
spec:
  tasks:
    - name: run-python-script
      taskRef:
        kind: Task
        name: first-task
      conditons:
        - conditionRef: condition-task
    - name: run-python-script-2
      taskRef:
        kind: ClusterTask
        name: first-clustertask
      runaftr:
        - run-python-script
$ 
$ kubectl apply --filename=pipeline_invalid.yaml 
Error from server (BadRequest): error when creating "pipeline_invalid.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "conditons"
$ 
$ 
$ tkn p start -f pipeline_invalid.yaml
Pipelinerun started: pipeline-invalid-run-rtqxn
In order to track the pipelinerun progress run:
tkn pipelinerun logs pipeline-invalid-run-rtqxn -f -n veeresh-testing
$ 
$ 
$ tkn pr ls
NAME                         STARTED         DURATION   STATUS
pipeline-invalid-run-rtqxn   9 seconds ago   ---        Running
$ 
$ tkn tr ls
NAME                                                   STARTED          DURATION   STATUS
pipeline-invalid-run-rtqxn-run-python-script-2-96njr   15 seconds ago   ---        Running
pipeline-invalid-run-rtqxn-run-python-script-vvdzh     16 seconds ago   ---        Running
```

**Comment by danielhelfand** [comment]
@VeereshAradhya `kubectl apply -f pipeline.yaml` is not equal to `tkn pipeline start -f pipeline.yaml`. `tkn pipeline start -f` starts a pipelinerun that does not exist on a cluster. `kubectl apply -f pipeline.yaml` would create a pipeline on a cluster.

I am going to assume your PipelineRun fails at which point the server should return an error saying why. If that is the case, then I think this is behaving as expected.

**Comment by danielhelfand** [comment]
That being said, this fits into the conversation of #956 and perhaps can be added to the discussion of that issue.

**Comment by VeereshAradhya** [comment]
@danielhelfand I just used `kubectl apply -f pipeline_invalid.yaml` to show that the pipeline definition file is not proper. The pipeline run in the above scenario does not fail, it neglects the `conditons` and `runaftr` and starts both the tasks `run-python-script` and `run-python-script-2` in parallel and finishes successfully.

 if the user does some typo on  `conditions` or `runAfter` and starts the pipelinerun using spec file, the user will be in assumption that it will be working fine, but in the backend it would be running something else

**Comment by danielhelfand** [comment]
> @danielhelfand I just used `kubectl apply -f pipeline_invalid.yaml` to show that the pipeline definition file is not proper. The pipeline run in the above scenario does not fail, it neglects the `conditons` and `runaftr` and starts both the tasks `run-python-script` and `run-python-script-2` in parallel and finishes successfully.

Then it's very possible that it's a server-side validation issue. Can you reproduce this scenario with kubectl using a PipelineRun?

> if the user does some typo on `conditions` or `runAfter` and starts the pipelinerun using spec file, the user will be in assumption that it will be working fine, but in the backend it would be running something else

Agreed, just a matter of where that validation takes place/if pipelines is doing so properly.

**Comment by VeereshAradhya** [comment]
Ah ok.. I will try and update

**Comment by danielhelfand** [comment]
The key is to create the PipelineRun similar to how we would do it with `tkn`:

https://github.com/tektoncd/cli/blob/27f9e03ece51cdd4ae6b4f4189759dde383a57ee/pkg/cmd/pipeline/start.go#L218

Basically including the PipelineSpec as part of the PipelineRun's PipelineSpec.

**Comment by piyush-garg** [comment]
@danielhelfand @VeereshAradhya 

It seems like an issue with our `Unmarshal` in the pipeline struct. If you see https://github.com/tektoncd/cli/blob/27f9e03ece51cdd4ae6b4f4189759dde383a57ee/pkg/cmd/pipeline/start.go#L763 it ignores the invalid field and takes the valid one only.

So we are getting incomplete file and pipelinerun proceeds if something got ignored which is optional lie `runafter`

**Comment by VeereshAradhya** [comment]
@danielhelfand , Tried the same scenario with the pipelinerun, `kubectl` is throwing error: `Error from server (BadRequest): error when creating "pipelinerun_invalid.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "conditons"`

Below are the command logs
```
$ tkn tr ls
No TaskRuns found
$ tkn pr ls
No PipelineRuns found
$ 
$ cat pipelinerun_invalid.yaml 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-invalid-run-5hlrp
  namespace: veeresh-testing
spec:
  pipelineSpec:
    tasks:
    - name: run-python-script
      taskRef:
        kind: Task
        name: first-task
      conditons:
        - conditionRef: condition-task
    - name: run-python-script-2
      taskRef:
        kind: ClusterTask
        name: first-clustertask
      runaftr:
        - run-python-script
$ 
$ 
$ kubectl apply -f pipelinerun_invalid.yaml 
Error from server (BadRequest): error when creating "pipelinerun_invalid.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "conditons"
$ 

```
