### ISSUE TITLE
Move brew taps from chmouel/homebrew-tektoncd-cli to something more official

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#99]
We currently have the brews in https://github.com/chmouel/homebrew-tektoncd-cli/
and we should have it to something more official :

Suggestions :

1. Move it to homebrew [core](https://docs.brew.sh/Acceptable-Formulae) (what does it involves)
2. Move it in a `Formula` folder  in `tektoncd/cli` (is it possible ?)
3. Move it to the `tektoncd` organisation as `tektoncd/homebrew-tektoncd-cli/`

/kind question

**Comment by hrishin** [comment]
feels right :+1:

**Comment by chmouel** [comment]
@hrishin which solution feels right?

**Comment by siamaksade** [comment]
1 and 2 feel more right :)

**Comment by siamaksade** [comment]
Homebrew Casks is also another option: https://github.com/Homebrew/homebrew-cask

Not sure if it has the same limitation (for automation) as homebrew core

**Comment by chmouel** [comment]
@siamaksade i moved the discussion to https://github.com/tektoncd/plumbing/issues/43 feel free to comment in there,

**Comment by chmouel** [comment]
reading thru https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md : 

```
The app is both open-source and CLI-only (i.e. it only uses the binary artifact). In that case, and in the spirit of deduplication, submit it first to Homebrew/core as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).
```

I am going to try to submit it to homebrew/core first instead of homebrew/cask

**Comment by chmouel** [comment]
Let's see how that works: 

https://github.com/Homebrew/homebrew-core/pull/43360
