### ISSUE TITLE
Resource validation using the CLI? 

### ISSUE THREAD

**Issue by NikeNano** [tektoncd/cli#999]
# Version and Operating System
 - 
**tkn Version:**
- 
**Operating System:** 
- 
# Expected Behavior
Is it possible to validate resources using the tekton CLI? Is this something that are investigated?  

It would be great to validate resources structures offline in order to improve workflow and speed. 

# Actual Behavior
- 
# Steps to Reproduce the Problem
- 

# Additional Info
 -

**Comment by danielhelfand** [comment]
@NikeNano Thanks for opening this!

Could you expound on what you mean by `validate resources structures`? Perhaps this is similar to #965 in that we need something similar to [`kubectl`'s server-side dry-run](https://github.com/tektoncd/cli/issues/956#issuecomment-627304006)?

**Comment by NikeNano** [comment]
It is related to this work for kubeflow/kfp-tekton, https://github.com/kubeflow/kfp-tekton/issues/137. Is sound similar, the goal is to be able to validate resources both a sperate command or dry-run command which validates sounds good. Is it today possible to do dry runs for pipeline resources in order to check it the resources are valid, didint really understand from the converstation how to do it and what is validated.  thank you @danielhelfand!

**Comment by NikeNano** [comment]
friendly ping @danielhelfand

**Comment by vdemeester** [comment]
Right, `tektoncd/pipeline` does support server-side `dry-run` now as far as I know, so we could add support for this in `tkn`, but this means we need a working kubernetes api-server (and tekton deployed) to validate things. As the validation code is part of the struct we are using, we could also code this directly in `tkn`

**Comment by NikeNano** [comment]
Would it be of interest to add the validation directly in the CLI, I could work on a contribution if this is something that would fit in to the CLI? For the use case of Kubeflow and kubeflow/kfp-tekton the offline validation is what we are looking for. Thanks

**Comment by vdemeester** [comment]
This is something we can discuss during today's call (or the next one), but I think it could make sense yeah.

/kind wg-discuss

**Comment by NikeNano** [comment]
Great @vdemeester. I will sadly not be able to join the meeting but look forward to hear the outcome!

**Comment by vdemeester** [comment]
So, in a gist, for now, `tkn` doesn't handle creation of definition types (we let this on `kubectl`). As discussed a bit during the working group, this would be a bit out of place if we allow validation generated yamls using `tkn` but not allowing for creation. Additionally, this is something we will need for  `tektoncd/catalog` test infrastructure (a bit like https://github.com/tektoncd/catalog/issues/7 but for validation). 

In a gist it is something useful to have, but might not be in `tkn` scope (at least as of today)

**Comment by NikeNano** [comment]
Thanks for the update!

**Comment by NikeNano** [comment]
Would it be of interest to contribute it in the sens of tektoncd/catalog instead? I am pushing this a bit in order to achieve something that will be updated over time instead of use building something that create a big burden to update for Kubeflow/kfp-tekton

**Comment by vdemeester** [comment]
> Would it be of interest to contribute it in the sens of tektoncd/catalog instead? I am pushing this a bit in order to achieve something that will be updated over time instead of use building something that create a big burden to update for Kubeflow/kfp-tekton

yeah it would, not sure where to put the code yet :stuck_out_tongue: (most likely more in `experimental` than `catalog` as we don't really want to hold re-usable code in the `catalog`, only re-usable tekton resources :stuck_out_tongue_closed_eyes: )

**Comment by danielhelfand** [comment]
Sorry to come back to this so late, but I think this might be worthwhile to add directly to tkn even if we don’t support creation. I without doubt think it’s an area we could improve on versus kubectl, which doesn’t always provide the most informative parsing errors. 

Would definitely be interested in discussing further in working group to see if it would be a good fit to be maintained here.

**Comment by NikeNano** [comment]
Ok, @danielhelfand are these meetings public? I would be happy to attend if possible to hear about how we progress with it.

**Comment by danielhelfand** [comment]
@NikeNano Meetings are public. If you can make it or would like to suggest something beforehand, either way would be great.

https://github.com/tektoncd/community/blob/master/working-groups.md#cli

**Comment by NikeNano** [comment]
@danielhelfand As I understand from the meeting yesterday validation in the CLI will be pursued if it is easy to do, based upon that the server allow for dry runs. I also understood it as you where going to check the API to investigate if it was implemented or not. I would be happy to help out with the work.

**Comment by chmouel** [comment]
👍, thanks for the help @NikeNano

**Comment by NikeNano** [comment]
@danielhelfand I have tried to figure out if the backend supports dry run but have not been successful(guess it could be because it don't). Have you had the opportunity to look at it?

**Comment by danielhelfand** [comment]
@NikeNano I have not had the chance to attempt yet with kubectl, but will attempt tomorrow and give an update. I haven’t found any pr or issue with pipeline to indicate it’s been added yet though.

**Comment by danielhelfand** [comment]
So I have been able to use `kubectl create -f <resource>.yaml --dry-run=server` with success, and it does appear to also support validation:

```
Error from server (BadRequest): error when creating "clustertask.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "mage"
```

So it does appear that server-side dry-runs should be supported, but maybe what `tkn` could offer here is better UX around the error message assuming a resource fails validation like above.

**Comment by NikeNano** [comment]
Cool @danielhelfand I am on vacation but will bick this up wen I am back!
